/**
 * @file test_nrr_model.cpp
 * @brief NRR Model Execution Test
 *
 * Tests ONNX model loading and inference through the NRR API using the
 * real sample models generated by tools/gen_sample_model.py.
 */

#include "nrr.h"
#include "onnx_runtime.h"
#include <iostream>
#include <fstream>
#include <vector>
#include <cmath>

#ifndef NRR_SAMPLE_MODEL
#define NRR_SAMPLE_MODEL "models/nrr_upscaler_v0.1.onnx"
#endif
#ifndef NRR_PASSTHROUGH_MODEL
#define NRR_PASSTHROUGH_MODEL "models/nrr_passthrough_2x.onnx"
#endif

static bool file_exists(const char* path) {
    std::ifstream f(path);
    return f.good();
}

static void print_metadata(nrr::ONNXRuntime& onnx) {
    std::cout << "  Info: " << onnx.get_model_info() << std::endl;
    std::cout << "  Inputs: " << onnx.get_input_count() << std::endl;
    std::cout << "  Outputs: " << onnx.get_output_count() << std::endl;
    for (int i = 0; i < onnx.get_input_count(); i++) {
        std::cout << "    Input " << i << ": " << onnx.get_input_name(i) << " [";
        auto shape = onnx.get_input_shape(i);
        for (size_t j = 0; j < shape.size(); j++) {
            if (j) std::cout << ", ";
            std::cout << shape[j];
        }
        std::cout << "]" << std::endl;
    }
    for (int i = 0; i < onnx.get_output_count(); i++) {
        std::cout << "    Output " << i << ": " << onnx.get_output_name(i) << " [";
        auto shape = onnx.get_output_shape(i);
        for (size_t j = 0; j < shape.size(); j++) {
            if (j) std::cout << ", ";
            std::cout << shape[j];
        }
        std::cout << "]" << std::endl;
    }
}

int main() {
    std::cout << "=== NRR Model Execution Test ===" << std::endl << std::endl;

    if (!file_exists(NRR_SAMPLE_MODEL)) {
        std::cerr << "Sample model not found: " << NRR_SAMPLE_MODEL << std::endl;
        std::cerr << "Run tools/gen_sample_model.py first." << std::endl;
        return 1;
    }
    if (!file_exists(NRR_PASSTHROUGH_MODEL)) {
        std::cerr << "Passthrough model not found: " << NRR_PASSTHROUGH_MODEL << std::endl;
        std::cerr << "Run tools/gen_sample_model.py first." << std::endl;
        return 1;
    }

    nrr::ONNXRuntime onnx;

    // --- Phase 1: Initialize + warm up with the sample upscaler model ------
    std::cout << "[1] Initializing ONNX Runtime..." << std::endl;
    if (!onnx.initialize()) {
        std::cerr << "Failed to initialize ONNX Runtime" << std::endl;
        onnx.shutdown();
        return 1;
    }
    std::cout << "  ONNX Runtime initialized" << std::endl << std::endl;

    std::cout << "[2] Loading sample upscaler model: " << NRR_SAMPLE_MODEL << std::endl;
    if (!onnx.load_model(NRR_SAMPLE_MODEL)) {
        std::cerr << "  Failed to load sample model" << std::endl;
        std::cerr << "  Info: " << onnx.get_model_info() << std::endl;
        onnx.shutdown();
        return 1;
    }
    std::cout << "  Sample model loaded" << std::endl;
    print_metadata(onnx);
    std::cout << std::endl;

    // --- Phase 2: Unload and load the passthrough model --------------------
    std::cout << "[3] Unloading sample model..." << std::endl;
    onnx.unload_model();
    std::cout << "  Unloaded" << std::endl << std::endl;

    std::cout << "[4] Loading passthrough model: " << NRR_PASSTHROUGH_MODEL << std::endl;
    if (!onnx.load_model(NRR_PASSTHROUGH_MODEL)) {
        std::cerr << "  Failed to load passthrough model" << std::endl;
        std::cerr << "  Info: " << onnx.get_model_info() << std::endl;
        onnx.shutdown();
        return 1;
    }
    std::cout << "  Passthrough model loaded" << std::endl;
    print_metadata(onnx);
    std::cout << std::endl;

    // --- Phase 3: Run inference ---------------------------------------------
    std::cout << "[5] Running inference on passthrough model..." << std::endl;
    const int64_t H = 32;
    const int64_t W = 32;
    std::vector<float> input_data(1 * 3 * H * W, 0.5f);
    std::vector<float> output_data;
    std::vector<int64_t> input_shape = {1, 3, H, W};
    std::vector<int64_t> output_shape = {1, 3, 2 * H, 2 * W};
    if (!onnx.run_inference(input_data, output_data, input_shape, output_shape)) {
        std::cerr << "  Inference failed!" << std::endl;
        onnx.shutdown();
        return 1;
    }
    std::cout << "  Output size: " << output_data.size() << " floats" << std::endl;
    std::cout << "  Expected:    " << (1 * 3 * 2 * H * 2 * W) << " floats" << std::endl;
    float sum = 0.0f;
    for (float v : output_data) sum += v;
    float avg = sum / output_data.size();
    std::cout << "  Average output: " << avg << std::endl;
    if (avg > 0.4f && avg < 0.6f) {
        std::cout << "  PASS: output average within expected range (0.4-0.6)" << std::endl;
    } else {
        std::cout << "  WARN: output average outside expected range" << std::endl;
    }
    std::cout << std::endl;

    // --- Phase 4: Cleanup ---------------------------------------------------
    std::cout << "[6] Cleaning up..." << std::endl;
    onnx.unload_model();
    onnx.shutdown();
    std::cout << std::endl << "Test completed successfully!" << std::endl;
    return 0;
}