#!/usr/bin/env python3
"""embed_spirv.py - turn compiled SPIR-V into a C++ header the runtime embeds.

The kernels are compiled from runtime/vulkan/shaders/*.comp by glslc at build time (see the SPIR-V
arm in CMakeLists.txt) and embedded here, so the runtime carries bytecode that was produced from the
checked-in source rather than a blob nobody can re-derive. The header records each shader's source
file and the SHA-256 of its SPIR-V; a machine that has a compiler re-derives those hashes and the
tests fail if they differ, which is the difference between "checked in" and "verified" - the M4 item
about "unchecked-in blobs".

Usage:
    embed_spirv.py <output-header> <name>=<file.spv> [<name>=<file.spv> ...]
"""

import hashlib
import pathlib
import sys

MAGIC = 0x07230203


def read_shader(spec):
    name, _, path = spec.partition("=")
    if not name or not path:
        raise SystemExit(f"bad argument '{spec}', expected <name>=<file.spv>")
    raw = pathlib.Path(path).read_bytes()
    if len(raw) % 4:
        raise SystemExit(f"{path}: SPIR-V size {len(raw)} is not a multiple of 4")
    words = [int.from_bytes(raw[i:i + 4], "little") for i in range(0, len(raw), 4)]
    if not words or words[0] != MAGIC:
        raise SystemExit(f"{path}: not SPIR-V (first word 0x{words[0]:08X})")
    return name, pathlib.Path(path).name, hashlib.sha256(raw).hexdigest(), words


def main(argv):
    if len(argv) < 3:
        print(__doc__)
        return 2
    out_path = pathlib.Path(argv[1])
    shaders = [read_shader(spec) for spec in argv[2:]]

    lines = [
        "/* Generated by tools/embed_spirv.py from runtime/vulkan/shaders/*.comp - do not edit. */",
        "#ifndef NRR_VULKAN_SHADERS_GENERATED_H",
        "#define NRR_VULKAN_SHADERS_GENERATED_H",
        "",
        "#include <cstdint>",
        "",
        "namespace nrr {",
        "namespace vk {",
        "",
        "/** One embedded kernel: the name it is dispatched by, the source it was compiled from, and",
        " *  the SHA-256 of the SPIR-V in it (which a machine with glslc re-derives and a test compares). */",
        "struct EmbeddedShader {",
        "    const char* name;",
        "    const char* source;",
        "    const char* sha256;",
        "    const uint32_t* words;",
        "    uint32_t word_count;",
        "};",
        "",
    ]
    for name, source, sha, words in shaders:
        lines.append(f"/* {source} - sha256 {sha} */")
        lines.append(f"static const uint32_t shader_words_{name}[] = {{")
        for i in range(0, len(words), 8):
            lines.append("    " + ", ".join(f"0x{w:08X}u" for w in words[i:i + 8]) + ",")
        lines.append("};")
        lines.append("")
    lines.append("static const EmbeddedShader kEmbeddedShaders[] = {")
    for name, source, sha, words in shaders:
        lines.append(f'    {{ "{name}", "{source}", "{sha}", shader_words_{name}, '
                     f"static_cast<uint32_t>(sizeof(shader_words_{name}) / sizeof(uint32_t)) }},")
    lines.append("};")
    lines.append("static const uint32_t kEmbeddedShaderCount = "
                 "static_cast<uint32_t>(sizeof(kEmbeddedShaders) / sizeof(kEmbeddedShaders[0]));")
    lines.append("")
    lines.append("} // namespace vk")
    lines.append("} // namespace nrr")
    lines.append("")
    lines.append("#endif /* NRR_VULKAN_SHADERS_GENERATED_H */")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    for name, source, sha, words in shaders:
        print(f"  embedded {name}: {source}, {len(words)} words, sha256 {sha[:16]}...")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
