#!/usr/bin/env python3
"""regen_jitter_fixture.py - regenerate the constants pinned by tests/unit/test_jitter.cpp.

The C++ correction is a second implementation of the trainer's, and the test that keeps them equal
pins numbers generated by Python on the same fixture. When the fixture or the correction changes, the
constants have to be regenerated from the Python side rather than read off the C++ side - otherwise the
test degenerates into the implementation agreeing with itself.

Fixture, mirrored exactly from the test: a 64x64 ramp scene[y][x] = (x + 0.25*y)/64, a capture whose
content is displaced by (0.3, 0.2) pixels, and clamped bilinear sampling on both sides.
"""
import os
import sys

import numpy as np
import torch

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)
import train_nrr as trainer  # noqa: E402

W = H = 64
OX, OY = 0.3, 0.2


def scene():
    ys, xs = np.meshgrid(np.arange(H, dtype=np.float32), np.arange(W, dtype=np.float32), indexing="ij")
    return (xs + 0.25 * ys) / 64.0


def sample_at(frame, dx, dy):
    """Clamped bilinear sample of `frame` at (x + dx, y + dy) - the C++ bilinear_taps, mirrored.

    The leading axis trick is avoided on purpose: a (H,W,1) weight array broadcast against an (H,W)
    image produces an (H,W,H) result rather than a per-pixel weighting, which scrambles the fixture
    while looking like it works.
    """
    ys, xs = np.meshgrid(np.arange(H, dtype=np.float32), np.arange(W, dtype=np.float32), indexing="ij")
    u = np.clip(xs + dx, 0.0, W - 1.0)
    v = np.clip(ys + dy, 0.0, H - 1.0)
    x0 = np.floor(u).astype(np.int32)
    y0 = np.floor(v).astype(np.int32)
    x1 = np.minimum(x0 + 1, W - 1)
    y1 = np.minimum(y0 + 1, H - 1)
    lx = u - x0
    ly = v - y0
    top = frame[y0, x0] * (1 - lx) + frame[y0, x1] * lx
    bottom = frame[y1, x0] * (1 - lx) + frame[y1, x1] * lx
    return top * (1 - ly) + bottom * ly


def capture(scene_image, ox, oy):
    """input(x) = scene(x - offset), clamped bilinear - the C++ jf_capture, mirrored."""
    return sample_at(scene_image, -ox, -oy)


def de_jitter(frame, ox, oy):
    tensor = torch.from_numpy(frame[None, None]).float()
    plane = torch.zeros(1, 2, H, W)
    plane[:, 0] = ox
    plane[:, 1] = oy
    return trainer.dejitter(tensor, plane)[0, 0].numpy()


def main():
    target = scene()

    # Validation first: rebuild the OLD convention with this same fixture code and check it
    # reproduces the constants that were pinned before the flip. If it does not, the replication is
    # wrong and any new number it produces is worthless - which is exactly what happened the first
    # time this script was written (a (H,W,1) weight array broadcast an (H,W) image into (H,W,H)).
    old_captured = sample_at(target, OX, OY)          # the old fixture: scene(x + offset)
    old_corrected = sample_at(old_captured, -OX, -OY)  # the old correction: sample at x - offset
    old_ignored = old_captured
    old_backwards = sample_at(old_captured, OX, OY)
    print("validation against the pre-flip constants:")
    print("  corrected %.9f (was 0.000145804)" % float(np.abs(old_corrected - target).mean()))
    print("  withheld  %.9f (was 0.005383286)" % float(np.abs(old_ignored - target).mean()))
    print("  backwards %.9f (was 0.010742154)" % float(np.abs(old_backwards - target).mean()))
    old_samples = [float(old_corrected[y, x]) for y, x in ((0, 0), (10, 20), (32, 32), (63, 63), (5, 50))]
    print("  samples   %s (was 0.005468741, 0.351562500, 0.625000000, 1.226562500, 0.800781250)"
          % ", ".join("%.9f" % value for value in old_samples))

    captured = capture(target, OX, OY)
    corrected = de_jitter(captured, OX, OY)
    ignored = de_jitter(captured, 0.0, 0.0)
    backwards = de_jitter(captured, -OX, -OY)

    # The trainer and this mirror must agree, or the constants below pin something the runtime does not do.
    mirror = sample_at(captured, OX, OY)
    print("  trainer vs mirror on the corrected frame: max %.3e" % float(np.abs(corrected - mirror).max()))

    print("mean errors (C++ asserts these):")
    print("  corrected  %.9f" % float(np.abs(corrected - target).mean()))
    print("  withheld   %.9f" % float(np.abs(ignored - target).mean()))
    print("  backwards  %.9f" % float(np.abs(backwards - target).mean()))
    print("interior samples of the corrected frame:")
    for y, x in ((0, 0), (10, 20), (32, 32), (63, 63), (5, 50)):
        print("  (y=%d,x=%d)  %.9f" % (y, x, float(corrected[y, x])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
