# ---------------------------------------------------------------------------
# run_parity.ps1 - the one command that produces docs/parity.md.
#
#   powershell -File tools\run_parity.ps1                 # the table, from whatever arms exist
#   powershell -File tools\run_parity.ps1 -Nrr            # measure NRR's own frame first, then the table
#   powershell -File tools\run_parity.ps1 -Xess           # run the XeSS sample (capability + latency)
#   powershell -File tools\run_parity.ps1 -XessOurFrames  # run XeSS over our frames (the quality row)
#   powershell -File tools\run_parity.ps1 -DlssOurFrames  # run DLSS over our frames (the quality row)
#   powershell -File tools\run_parity.ps1 -Dlss           # record the Godot fork's Streamline status
#   powershell -File tools\run_parity.ps1 -SuiteLog <log> # extract the runtime frame budget from a suite log
#
# The full table is `-Nrr -Xess -Dlss`: the three switches run the arms, and a plain run re-uses the arm
# directories and the benchmark report those switches left behind under work/parity/.
#
# It is written for Windows PowerShell 5.1 (there is no pwsh on the development host) and parses under
# both, which matters the same way tools/build.ps1 does: the runner has to work on the CI shell too.
#
# Why a runner as well as a harness: an arm that "exists" as code and has never produced a frame is
# exactly the claimed capability this project refuses to count. So the arms are *run* here, and each
# deposits a directory under work/parity/arms/<name>/ carrying arm.json - what it is, what resolution,
# what preset, what it cost - which the harness ingests. An arm that could not run still gets a row,
# and that row carries the reason.
#
# work/ is gitignored: these directories are regenerated by re-running this script.
# ---------------------------------------------------------------------------

[CmdletBinding()]
param(
    [string]$Data = "models/training-data/godot-v6-warp",
    [string]$Model = "models/phase4/upscale_msreal_scale.onnx",
    # ^ the release artifact and the baseline: it is scale-agnostic (a token carries the tier), so one graph is
    # measured at both tiers rather than one model per tier. `models/phase4/upscale_mid.onnx` remains the
    # strongest per-tier artifact at 256->512 and is what to pass when the question is the high tier alone.
    [int]$Limit = 24,
    [string]$Python = "",
    [string]$SuiteLog = "",
    [switch]$Xess,
    [switch]$XessOurFrames,
    [switch]$Dlss,
    [switch]$DlssOurFrames,
    [switch]$Nrr,
    [int]$NrrFrames = 30,
    [double]$NrrMotion = 0.0,
    # A tag for a second tier: it moves the arm directories, the work directories and the report/table names, so
    # two resolutions can be measured without either run's arms being read by the other. Empty for the default
    # tier, which keeps the paths every earlier run used.
    [string]$Suffix = "",
    [switch]$SkipTable
)

$ErrorActionPreference = "Continue"
$repo = Split-Path -Parent $PSScriptRoot
Push-Location $repo
$failed = @()

# The tiers both arms are measured at, named input->output. That name is the only one the two arms can agree
# on: the XeSS sample is handed the *output* size and derives its input from the preset, while NRR is handed
# the *input* grid, so "1080p" alone would mean opposite ends in the two rows.
$parityTiers = @(
    @{ input = "960x540";   output = @(1920, 1080) },
    @{ input = "1920x1080"; output = @(3840, 2160) }
)

# The interpreter matters: the offline arms need torch for the trainer's exact bilinear baseline and
# onnxruntime for the model, which the training virtualenv has and a bare system python does not. The
# choice is resolved and printed rather than assumed.
if (-not $Python) {
    $candidate = "G:\venvs\nrr-train\Scripts\python.exe"
    $Python = if (Test-Path $candidate) { $candidate } else { "python" }
}
Write-Output "python: $Python"

function New-ArmDirectory($name) {
    # The suffix moves the whole arms root, so a second tier's arms are never discovered by the first tier's run.
    $dir = Join-Path $repo ("work\parity\arms" + $Suffix + "\" + $name)
    New-Item -ItemType Directory -Force -Path $dir | Out-Null
    return $dir
}

# cmake, resolved the way tools/build.ps1 resolves it: PATH first (preferring a real CMake install over the
# copy Strawberry Perl also exposes), then a pip-installed CMake under a Python site-packages tree.
function Find-CMake {
    $found = @(Get-Command cmake -CommandType Application -ErrorAction SilentlyContinue |
        ForEach-Object { $_.Source } | Where-Object { $_ })
    $preferred = @($found | Where-Object { $_ -like '*\CMake\bin\cmake.exe' })
    if ($preferred.Count -gt 0) { return $preferred[0] }
    if ($found.Count -gt 0) { return $found[0] }
    $roots = @('C:\Python313', 'C:\Python312', 'C:\Python311', 'C:\Python310',
               (Join-Path $env:LOCALAPPDATA 'Programs\Python\Python313'),
               (Join-Path $env:LOCALAPPDATA 'Programs\Python\Python312'))
    foreach ($root in $roots) {
        $candidate = Join-Path $root 'Lib\site-packages\cmake\data\bin\cmake.exe'
        if (Test-Path $candidate) { return $candidate }
    }
    return ""
}

# The CUDA runtime DLLs are fetched but not on PATH, which is exactly how a GPU benchmark silently becomes a
# CPU one: ONNX Runtime fails to load onnxruntime_providers_cuda.dll (it needs cublasLt64_12.dll) and falls
# back to the CPU provider. The arm below therefore puts them on PATH itself, and the benchmark still reports
# which provider actually attached rather than what was asked for.
function Get-CudaRuntimeDir {
    $candidate = Get-ChildItem (Join-Path $repo "third_party\cuda-runtime-*\bin") -Directory -ErrorAction SilentlyContinue |
        Select-Object -First 1
    if ($candidate) { return $candidate.FullName }
    return ""
}


# ---------------------------------------------------------------------------
# The XeSS arm: Intel's own Super Resolution sample, the only runnable XeSS-SR
# this machine can drive. Note what it can and cannot give us: it reports frame
# times with its own device and driver, and it cannot dump its frames, so its
# quality columns stay empty and its row says why.
# ---------------------------------------------------------------------------
function Invoke-XessArm {
    $sdk = Join-Path $repo "third_party\xess-3.0.2\bin"
    if (-not (Test-Path (Join-Path $sdk "libxess.dll"))) {
        Write-Output "xess: SDK not present - run: powershell -File tools\fetch_xess.ps1"
        return $false
    }
    $dir = New-ArmDirectory "xess-vk"
    $entries = @()
    $device = ""; $driver = ""
    foreach ($tier in $parityTiers) {
        $tierName = "$($tier.input)->$($tier.output[0])x$($tier.output[1])"
        $outW = $tier.output[0]; $outH = $tier.output[1]
        $stem = "frames-" + ($tierName -replace '[^0-9A-Za-z]', '-')
        $csv = Join-Path $dir ("$stem.csv")
        Write-Output "xess: $tierName ($($outW)x$($outH) output, preset Performance)"
        $env:Path = $sdk + ";" + $env:Path
        # The call operator, not Start-Process: it quotes each argument for a native command, and this
        # repository path contains a space ("Program Prototype"), which an argument list handed to
        # Start-Process does not survive - the sample then writes its results somewhere else entirely.
        # No log file is kept for the sample's own output: it writes to the console handle rather than to
        # stdout, so a redirect produces an empty file. Its results CSV is the record instead.
        Push-Location $sdk
        & (Join-Path $sdk "basic_sample_super_resolution_vk.exe") `
            --benchmark --benchwarmup 3 --benchruntime 10 `
            -w $outW -h $outH `
            --benchframetimes --benchfilename $csv | Out-Null
        $code = $LASTEXITCODE
        Pop-Location
        if ($code -ne 0) { $script:failed += "xess $tierName (exit $code)" }
        if (-not (Test-Path $csv)) { $script:failed += "xess $tierName (no results file)"; continue }

        # The sample's own results file, exactly as benchmark.hpp writes it: a
        # `device,driverversion,duration (ms),frames,fps` header, then the device row, then `frame,ms` rows.
        $lines = Get-Content $csv
        if ($lines.Count -ge 2) {
            $parts = $lines[1].Split(',')
            $device = $parts[0]; $driver = $parts[1]
        }
        $times = @()
        foreach ($line in ($lines | Select-Object -Skip 1)) {
            if ($line -match '^\d+,([\d.]+)$') { $times += [double]$Matches[1] }
        }
        if ($times.Count -lt 100) { $script:failed += "xess $tierName (only $($times.Count) frame times)"; continue }
        $sorted = $times | Sort-Object
        $entries += [ordered]@{
            tier = $tierName
            ms = [math]::Round(($times | Measure-Object -Average).Average, 3)
            p50 = [math]::Round($sorted[[int]($sorted.Count * 0.50)], 3)
            p99 = [math]::Round($sorted[[int]($sorted.Count * 0.99)], 3)
            kind = "end-to-end-frame"
            output = @($outW, $outH)
            frames = $times.Count
            source = "basic_sample_super_resolution_vk.exe --benchmark, $($times.Count) frames"
        }
        Write-Output ("  avg {0} ms  p50 {1} ms  p99 {2} ms  ({3} frames)" -f $entries[-1].ms, $entries[-1].p50,
                      $entries[-1].p99, $entries[-1].frames)
    }
    if ($entries.Count -eq 0) { return $false }
    $dll = (Get-Item (Join-Path $sdk "libxess.dll")).VersionInfo.FileVersion
    # VkPhysicalDeviceProperties.driverVersion is vendor-packed; NVIDIA's is major << 22 | minor << 14.
    # Decoding it here keeps the table's driver column a readable version without anyone typing it by hand.
    [int64]$driverRaw = 0
    $driverText = $driver
    if ([int64]::TryParse($driver, [ref]$driverRaw)) {
        if ($device -match 'NVIDIA') {
            $driverText = "{0}.{1}" -f ($driverRaw -shr 22), (($driverRaw -shr 14) -band 0xff)
        } else {
            $driverText = "0x{0:x}" -f $driverRaw
        }
    }
    # Kept as statement-level strings: a multi-line value inside a hash literal does not parse in
    # PowerShell 5.1, and a continued line has to *end* with its operator, not start with it.
    $qualityReason = "the SDK sample renders its own scene and cannot dump its frames, so there is no " +
                     "pair of outputs to score against our targets with"
    $note = "device $device, driver $driverText (Vulkan driverVersion $driver). The sample's own scene is a " +
            "triangle with a moving object, so this is XeSS's cost on a near-empty frame at this " +
            "resolution - a lower bound on what it would cost over content, not an upper one."
    $arm = [ordered]@{
        # Named `xess-sample`, not `xess`: this is Intel's own sample rendering its own scene. The quality row
        # for XeSS comes from benchmarks/xess_host running the same library over *our* frames, so one product
        # gets two rows and each name says which measurement it is.
        arm = "xess-sample"
        version = "XeSS SDK 3.0.2 (libxess.dll $dll)"
        backend = "Vulkan, DP4a (no XMX on this GPU)"
        preset = "performance"
        ratio = 2.0
        output = @(1920, 1080)
        same_frames = $false
        scene = "xess-sample"
        quality = "unavailable"
        quality_reason = $qualityReason
        latency_ms = $entries
        latency_tier = $entries[0].tier
        notes = $note
    }
    $arm | ConvertTo-Json -Depth 6 | Set-Content -Path (Join-Path $dir "arm.json") -Encoding UTF8
    Write-Output "xess: arm.json written to $dir"
    return $true
}


# ---------------------------------------------------------------------------
# The DLSS arm. What it needs is knowable and checkable, so the check runs and
# the outcome is recorded either way. The chain is: the fork must be built, its
# Streamline driver must load the interposer, and the interposer plus Streamline's
# own plugin DLLs must be findable at runtime. A missing link becomes a reason in
# the table, never a quietly absent row.
# ---------------------------------------------------------------------------
function Invoke-DlssArm {
    # Named `dlss-fork`, not `dlss`: the row named `dlss` is the quality row produced by benchmarks/dlss_host
    # (DLSS over *our* frames through NGX). What this function checks is the *fork's* ability to drive Streamline,
    # which is a different claim - and one that would otherwise overwrite the quality arm's arm.json.
    $dir = New-ArmDirectory "dlss-fork"
    $forkRoot = "G:\godot-nvpt"
    $forkExe = Join-Path $forkRoot "bin\godot.windows.editor.x86_64.exe"
    $driver = Join-Path $forkRoot "drivers\streamline\streamline_context.cpp"
    $ngx = Join-Path $repo "third_party\dlss-unity\nvngx_dlss.dll"

    # The integration, as the fork's own source states it, rather than as guessed from the binary.
    $loadsInterposer = $false
    if (Test-Path $driver) {
        $loadsInterposer = [bool](Select-String -Path $driver -Pattern 'LoadLibraryA\("sl\.interposer\.dll"\)' -Quiet)
    }
    # The runtime: Streamline's redistributable DLLs, which the fork's thirdparty/streamline carries as
    # headers only, so they have to be beside the exe (or somewhere the loader will look).
    $runtime = @()
    foreach ($where in @((Join-Path $forkRoot "bin"), $forkRoot)) {
        $runtime += Get-ChildItem $where -Filter "sl.*.dll" -File -ErrorAction SilentlyContinue
    }
    $interposer = $runtime | Where-Object { $_.Name -eq "sl.interposer.dll" } | Select-Object -First 1

    $blockers = @()
    if (-not (Test-Path $forkExe)) { $blockers += "the fork is not built at $forkExe" }
    if (-not $loadsInterposer) { $blockers += "the fork has no Streamline integration (its driver does not load sl.interposer.dll)" }
    if (-not $interposer) {
        $blockers += "the Streamline runtime is absent: no sl.interposer.dll beside the exe or under the fork, " +
                     "and the fork's thirdparty/streamline ships headers only"
    }
    if (-not (Test-Path $ngx)) { $blockers += "nvngx_dlss.dll is not staged in third_party/dlss-unity" }

    if ($blockers.Count -eq 0) {
        $reason = "the runtime pieces are present; the live arm has not been driven through " +
                  "engine_plugins/godot_verify/benchmark_dlss.gd on this run"
    } else {
        # Not a blocker for the table's `dlss` row: that row is measured by benchmarks/dlss_host through NGX,
        # which needs none of this. Streamline is what the *Godot fork* needs to render with DLSS in-engine.
        $reason = "the Godot fork cannot drive Streamline yet - " + ($blockers -join "; ") +
                  " (the table's dlss row does not depend on this: it is measured through NGX by " +
                  "benchmarks/dlss_host)"
    }
    $note = "fork $forkExe" + "; LoadLibraryA(sl.interposer.dll) in the driver: $loadsInterposer" +
            "; Streamline DLLs found: " + $(if ($runtime.Count) { ($runtime | ForEach-Object { $_.Name }) -join ", " } else { "none" }) +
            ". docs/nvidia-streamline-godot.md records the state of this seam."

    $arm = [ordered]@{
        arm = "dlss"
        version = "NGX 310.5.3.0 (nvngx_dlss.dll from the Unity install)"
        backend = "D3D12 through Streamline, in the NVIDIA Godot fork"
        preset = "quality"
        ratio = 2.0
        output = @(1920, 1080)
        same_frames = $false
        scene = "godot-fork"
        quality = "unavailable"
        quality_reason = $reason
        latency_reason = $reason
        notes = $note
    }
    $arm | ConvertTo-Json -Depth 6 | Set-Content -Path (Join-Path $dir "arm.json") -Encoding UTF8
    Write-Output "dlss: $reason"
    Write-Output "dlss: $note"
    return $true
}

# ---------------------------------------------------------------------------
# The NRR arm: our own benchmarker, benchmarks/nrr_bench.cpp.
#
# This is the counterpart the table was missing. XeSS is measured by running Intel's sample application at a
# chosen tier; until now NRR's `end-to-end-frame` numbers could only come out of the unified test suite, which
# runs all 194 tests and reports an average over five samples. Here the arm is built (Release - a Debug frame
# is not the frame anyone ships), run at the same two tiers by name, and measured over a frame count with the
# distribution XeSS reports.
#
# It also puts the CUDA runtime DLLs on PATH before running, because without them ONNX Runtime quietly falls
# back to the CPU provider and the row would say "NRR" while measuring something else entirely. The JSON keeps
# the provider the runtime reported, which is what the table cites.
# ---------------------------------------------------------------------------
function Invoke-NrrArm {
    $cmake = Find-CMake
    if (-not $cmake) { Write-Output "nrr: cmake not found; see tools/build.ps1"; return $false }
    $buildDir = Join-Path $repo "build"
    $exe = Join-Path $buildDir "Release\nrr_bench.exe"
    if (-not (Test-Path $buildDir)) { Write-Output "nrr: no build directory at $buildDir"; return $false }

    Write-Output "nrr: building nrr_bench (Release)"
    & $cmake --build $buildDir --config Release --target nrr_bench *> (Join-Path $repo "work\parity\nrr-build.log")
    if ($LASTEXITCODE -ne 0 -or -not (Test-Path $exe)) {
        Write-Output "nrr: the benchmarker did not build; see work\parity\nrr-build.log"
        return $false
    }

    $outDir = Join-Path $repo ("work\parity\nrr-bench" + $Suffix)
    New-Item -ItemType Directory -Force -Path $outDir | Out-Null
    $json = Join-Path $repo ("work\parity\nrr-bench" + $Suffix + ".json")
    $cuda = Get-CudaRuntimeDir
    if ($cuda) { $env:Path = $cuda + ";" + $env:Path }
    else { Write-Output "nrr: no CUDA runtime under third_party; the row may be a CPU measurement" }

    $model = Join-Path $repo $Model
    if (-not (Test-Path $model)) { Write-Output "nrr: no model at $model"; return $false }

    $arguments = @("--model", $model, "--frames", "$NrrFrames", "--warmup", "5",
                   "--motion", "$NrrMotion", "--csv", $outDir, "--json", $json)
    foreach ($tier in $parityTiers) { $arguments += @("--tier", $tier.input) }
    Write-Output ("nrr: $(($parityTiers | ForEach-Object { $_.input }) -join ', ') over $NrrFrames frames (Release, CUDA runtime on PATH)")
    & $exe @arguments
    if ($LASTEXITCODE -ne 0 -or -not (Test-Path $json)) {
        $script:failed += "nrr arm"
        return $false
    }
    Write-Output "nrr: $json"
    return $true
}

if ($Xess) { if (-not (Invoke-XessArm)) { $failed += "xess arm" } }
if ($Dlss) { if (-not (Invoke-DlssArm)) { $failed += "dlss arm" } }
if ($Nrr)  { if (-not (Invoke-NrrArm))  { $failed += "nrr arm" } }

# XeSS over *our* frames: the arm that makes the comparison a comparison rather than two capability notes.
# It runs benchmarks/xess_host (the library, in our process, over this dataset's own validation frames) and
# leaves an arm directory whose frames the harness scores against the same targets NRR is scored against.
if ($XessOurFrames) {
    $arguments = @("tools\xess_over_our_frames.py", "--data", $Data, "--limit", "$Limit", "--model", $Model,
                   "--arm", "work/parity/arms$Suffix/xess-our-frames", "--work", "work/parity/xess-run$Suffix")
    & $Python @arguments
    if ($LASTEXITCODE -ne 0) { $failed += "the XeSS-over-our-frames arm" }
}

# DLSS over *our* frames, the same way: benchmarks/dlss_host drives the NGX runtime over this dataset's own
# validation frames, and the harness scores the result against the targets NRR is scored against.
if ($DlssOurFrames) {
    $arguments = @("tools\dlss_over_our_frames.py", "--data", $Data, "--limit", "$Limit", "--model", $Model,
                   "--arm", "work/parity/arms$Suffix/dlss", "--work", "work/parity/dlss-run$Suffix")
    & $Python @arguments
    if ($LASTEXITCODE -ne 0) { $failed += "the DLSS-over-our-frames arm" }
}

if ($SuiteLog) {
    $budget = Join-Path $repo "work\parity\nrr-frame-budget.json"
    & $Python "tools\parity_harness.py" --frame-budget-log $SuiteLog --frame-budget-out $budget
    if ($LASTEXITCODE -ne 0) { $failed += "frame budget extraction" }
}

if (-not $SkipTable) {
    $online = @()
    if (Test-Path "work\parity\arms$Suffix") {
        $online = Get-ChildItem "work\parity\arms$Suffix" -Directory |
            Where-Object { Test-Path (Join-Path $_.FullName "arm.json") } |
            ForEach-Object { $_.FullName }
    }
    $arguments = @("tools\parity_harness.py", "--data", $Data, "--limit", "$Limit",
                   "--out", "work\parity\report$Suffix.json", "--markdown", "docs\parity$Suffix.md")
    if (Test-Path $Model) {
        $arguments += @("--model", $Model)
    } else {
        Write-Output "note: $Model is absent, so the table carries no nrr row"
    }
    if (Test-Path "work\parity\nrr-frame-budget$Suffix.json") {
        $arguments += @("--nrr-frame-budget", "work\parity\nrr-frame-budget$Suffix.json")
    }
    if (Test-Path "work\parity\nrr-bench$Suffix.json") {
        $arguments += @("--nrr-bench", "work\parity\nrr-bench$Suffix.json")
    }
    foreach ($arm in $online) { $arguments += @("--online", $arm) }
    & $Python @arguments
    if ($LASTEXITCODE -ne 0) { $failed += "the table" }
}

Pop-Location
if ($failed.Count -gt 0) { Write-Output "FAILED: $($failed -join ', ')" }
Write-Output "run_parity: $($failed.Count) failure(s)"

