#!/usr/bin/env python3
"""train_nrr.py - train the in-house upscaler on pairs generated by gen_training_pairs.py.

Why this exists: models/nrr_upscaler_v0.1.onnx is a skeleton whose refinement output is zero, so it is
an identity-preserving bilinear upsample with no learned weights. This is the first model in the
repository whose weights come from data we own and whose quality is measured against the baseline it
has to beat.

What is trained: a small 2x upscaler - feature extraction, depth and motion fusion, PixelShuffle
upsampling, two residual blocks, output projection, and a bilinear skip. The skip is deliberate: the
network learns the *correction* to the naive baseline rather than the image, so "beats bilinear" is a
statement about something learned, and a zero residual is exactly the baseline - which the gates below
detect instead of assuming.

The gates, all measured on held-out scenes rather than read off the training loss:
    beats the baseline   val L1 must be at least MIN_IMPROVEMENT below the bilinear upscale's
    is not the baseline  the output must differ from the bilinear upscale by more than BASELINE_FLOOR
    uses conditioning    zeroing depth, and zeroing motion, must each change the output. A model that
                         ignores an input the roadmap asked for has not been trained on it, and no
                         training loss would ever reveal that.
    reproducible         the same seed reproduces the same validation numbers

Usage:
    python tools/train_nrr.py --data models/training-data/v1 --out models/nrr_upscaler_trained.onnx
    python tools/train_nrr.py --self-test    # the gates must reject a model that is the baseline

Requires: pip install torch, numpy, onnx. onnxruntime is optional and used only to confirm that the
exported graph agrees with PyTorch.

GPU: `--device auto` (the default) uses the GPU whenever torch can provide one, `--device cuda` refuses
to run on the CPU rather than pretend, and because a CPU-only torch wheel is the usual cause of a
"GPU training" session that never touches the GPU, the run records the device, the driver's own
utilization samples (nvidia-smi, sampled while training) and torch's peak allocation in its report. The
CPU-only wheel used for the first runs lives in the system Python; the CUDA wheel used here is in a
separate environment (G:\venvs\nrr-train, torch 2.3.1+cu121) so the two can be compared without
reinstalling anything:

    G:\venvs\nrr-train\Scripts\python.exe tools/train_nrr.py --data models/training-data/v1 \\
        --out models/nrr_upscaler_trained.onnx --epochs 45 --channels 48 --device auto
"""

import argparse
import hashlib
import json
import os
import subprocess
import sys
import threading
import time

import numpy as np
import torch
import torch.nn as nn

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import quality_metrics  # noqa: E402  (path set above; PSNR/SSIM mirror runtime/nrr_quality.cpp)

# The names the C++ runtime reads out of the graph (runtime/onnx_runtime.cpp reads the session's own
# input and output names, and these are the ones models/architecture.md specifies).
INPUT_NAMES = ("color", "depth", "motion")
OUTPUT_NAME = "output"

# Measured thresholds, not preferences: each one is a floor below which the claim would be cosmetic.
MIN_IMPROVEMENT = 0.05      # at least 5% below the bilinear baseline on held-out scenes
BASELINE_FLOOR = 1e-3       # output must differ from the bilinear baseline by more than this
CONDITIONING_FLOOR = 1e-4   # zeroing an input must change the output by more than this
# The training loss must fall by at least this fraction from the first epoch to the last. Five of eight
# stage-4 runs sat at exactly the untrained-model loss and would otherwise have been reported as results;
# a run that does not learn is a fact about the run, and it belongs in the gate set rather than in prose.
MIN_TRAIN_PROGRESS = 0.10


def resolve_device(requested, log):
    """Chooses the device and refuses to pretend. Asking for cuda where torch cannot provide it is an
    error, not a quiet CPU run: a silent fallback is how a GPU result gets reported that never touched a
    GPU, which is the failure the C++ provider tests already forbid on the runtime side."""
    available = torch.cuda.is_available()
    if requested == "cuda" and not available:
        raise SystemExit(
            "--device cuda was requested but torch reports no usable CUDA device (torch %s, built with "
            "CUDA: %s, device_count: %d). Install a CUDA wheel, for example torch==2.3.1+cu121 from "
            "https://download.pytorch.org/whl/cu121, and re-run. Refusing to fall back to CPU silently."
            % (torch.__version__, torch.version.cuda, torch.cuda.device_count()))
    if not available:
        log("  device: cpu (torch %s has no CUDA support; cuda build is %s)"
            % (torch.__version__, torch.version.cuda))
        return torch.device("cpu"), {"used": "cpu", "requested": requested, "cuda_available": False,
                                     "torch": torch.__version__, "cuda_build": torch.version.cuda}
    device = torch.device("cuda" if requested == "auto" else requested)
    props = torch.cuda.get_device_properties(0)
    facts = {"used": device.type, "requested": requested, "cuda_available": True,
             "torch": torch.__version__, "cuda_build": torch.version.cuda,
             "device_name": torch.cuda.get_device_name(0),
             "capability": "sm_%d%d" % torch.cuda.get_device_capability(0),
             "total_memory_mb": round(props.total_memory / (1 << 20))}
    log("  device: %s (%s, %s, %d MB, torch %s built for CUDA %s)"
        % (device.type, facts["device_name"], facts["capability"], facts["total_memory_mb"],
           torch.__version__, torch.version.cuda))
    return device, facts


class GpuSampler(threading.Thread):
    """Samples the driver while training runs. A launched CUDA kernel is not the same thing as a used
    GPU: this asks nvidia-smi what the device was actually doing, so "the GPU was used" is a measurement
    rather than an inference from the device's presence."""

    def __init__(self, interval=0.4):
        super().__init__(daemon=True)
        self.interval = interval
        # Not named _stop: threading.Thread has an internal _stop() method, and an attribute of that name
        # shadows it, so Thread.join() fails with "TypeError: 'Event' object is not callable".
        self._halt = threading.Event()
        self.samples = []

    def run(self):
        while not self._halt.is_set():
            try:
                lines = subprocess.run(
                    ["nvidia-smi", "--query-gpu=utilization.gpu,memory.used",
                     "--format=csv,noheader,nounits"],
                    capture_output=True, text=True, timeout=5).stdout.strip().splitlines()
                for line in lines:
                    parts = [part.strip() for part in line.split(",")]
                    if len(parts) == 2:
                        self.samples.append((float(parts[0]), float(parts[1])))
            except Exception:
                pass  # a sampling gap is not a training failure
            self._halt.wait(self.interval)

    def stop(self):
        self._halt.set()
        self.join(timeout=5)

    def summary(self):
        if not self.samples:
            return {"samples": 0,
                    "note": "nvidia-smi produced no samples, so utilization was not measured"}
        usage = [sample[0] for sample in self.samples]
        memory = [sample[1] for sample in self.samples]
        return {"samples": len(self.samples),
                "utilization_percent": {"mean": round(sum(usage) / len(usage), 1), "max": max(usage)},
                "memory_used_mb": {"mean": round(sum(memory) / len(memory)), "max": max(memory)}}


def load_dataset(data_dir):
    """Loads the manifest and the pairs it names, as float32 tensors in NCHW order."""
    manifest_path = os.path.join(data_dir, "manifest.json")
    if not os.path.exists(manifest_path):
        raise SystemExit("%s has no manifest.json - run tools/gen_training_pairs.py first" % data_dir)
    with open(manifest_path, encoding="utf-8") as handle:
        manifest = json.load(handle)

    buckets = {"train": [], "val": []}
    for entry in manifest["pairs"]:
        path = os.path.join(data_dir, entry["file"])
        with np.load(path) as pair:
            item = {
                "color": torch.from_numpy(pair["input"].transpose(2, 0, 1)[None].copy()),
                "depth": torch.from_numpy(pair["depth"][None, None].copy()),
                "motion": torch.from_numpy(pair["motion"].transpose(2, 0, 1)[None].copy()),
                "target": torch.from_numpy(pair["target"].transpose(2, 0, 1)[None].copy())}
            # history and validity exist in captures (tools/pack_godot_pairs.py) but not in procedural
            # pairs. Their absence is not an error - a run that does not ask for them must still work - and
            # their presence is what makes the history comparison possible at all.
            if "history" in pair:
                item["history"] = torch.from_numpy(pair["history"].transpose(2, 0, 1)[None].copy())
            buckets[entry["split"]].append(item)

    for split in ("train", "val"):
        if not buckets[split]:
            raise SystemExit(
                "the dataset has no %s pairs (train=%d, val=%d) - regenerate with a smaller "
                "--val-every, or more pairs" % (split, len(buckets["train"]), len(buckets["val"])))

    keys = ["color", "depth", "motion", "target"]
    # A dataset is either captured (every pair has history) or procedural (none does): a mixture would
    # concatenate different channel counts together, so it is refused rather than half-supported.
    history_counts = {("history" in item) for items in buckets.values() for item in items}
    if len(history_counts) > 1:
        raise SystemExit("the dataset mixes pairs with and without history; use one capture per dataset")
    has_history = history_counts == {True}
    if has_history:
        keys.append("history")

    dataset = {"has_history": has_history}
    for split, items in buckets.items():
        dataset[split] = {key: torch.cat([item[key] for item in items], dim=0) for key in keys}
    dataset["sizes"] = {split: len(items) for split, items in buckets.items()}
    return manifest, dataset


def take(batch, index, keys):
    """Slices a split down to one batch. `keys` comes from the dataset so a pair with history is sliced
    with it and one without is not."""
    return {key: batch[key][index] for key in keys}


def check_gates(numbers, zeroed=None, inputs=("color", "depth", "motion")):
    """Returns the reasons a model fails to qualify, as a list, so a run reports every failure rather
    than only the first. Called before anything is exported, and used by the self-test.

    `zeroed` names an input that this run deliberately ablated: a model cannot be blamed for ignoring an
    input it was never given, so that one gate is skipped. `inputs` is what the model actually consumes,
    because a colour-only model has no history weights to ignore and must not be failed for not using
    something it does not have."""
    failures = []
    # Checked first, because every other number below is meaningless if the run never learned: a stalled
    # model reports the untrained-model loss, and its held-out figure would otherwise be compared as if it
    # were a result of a different input set.
    if numbers.get("train_progress", 1.0) < MIN_TRAIN_PROGRESS:
        failures.append(
            "training made no progress: residual L1 went from %.5f to %.5f, a fall of %.1f%% (needs >= "
            "%.0f%%) - this run is degenerate and its numbers are not a comparison result"
            % (numbers.get("train_first_loss", 0.0), numbers.get("train_last_loss", 0.0),
               numbers.get("train_progress", 0.0) * 100.0, MIN_TRAIN_PROGRESS * 100.0))
    if numbers["val_l1"] > numbers["val_baseline_l1"] * (1.0 - MIN_IMPROVEMENT):
        failures.append(
            "does not beat the baseline: val L1 %.5f against the bilinear baseline's %.5f, which is "
            "not at least %.0f%% lower" % (numbers["val_l1"], numbers["val_baseline_l1"],
                                           MIN_IMPROVEMENT * 100.0))
    if numbers["drift"] <= BASELINE_FLOOR:
        failures.append(
            "is the baseline: its output differs from the bilinear upscale by only %.6f (needs > "
            "%.4f), so nothing was learned" % (numbers["drift"], BASELINE_FLOOR))
    for field in ("depth_ablation", "motion_ablation", "history_ablation"):
        name = field.split("_")[0]
        if name not in inputs or (zeroed and field.startswith(zeroed)):
            continue
        if numbers[field] <= CONDITIONING_FLOOR:
            failures.append(
                "ignores %s: zeroing it changes the output by only %.6f (needs > %.4f)"
                % (name, numbers[field], CONDITIONING_FLOOR))
    return failures


def export_onnx(model, out_path, size, inputs, opset=17):
    """Exports with the input names models/architecture.md specifies and dynamic H/W, so the runtime is not
    tied to the size this model happened to be trained at. The tensor list follows the selected inputs,
    because a colour-only model must not declare three inputs the runtime would have to invent.

    The example tensors are built on the model's own device. They were built on the CPU, which was
    invisible while training ran on the CPU and became an immediate failure the moment it moved to the GPU:
    "Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same"."""
    widths = {"color": 3, "depth": 1, "motion": 2, "history": 3}
    ordered = [name for name in ("color", "depth", "motion", "history") if name in inputs]
    device = next(model.parameters()).device
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    example = tuple(torch.zeros(1, widths[name], size, size, device=device) for name in ordered)
    dynamic = {name: {2: "H", 3: "W"} for name in ordered}
    dynamic[OUTPUT_NAME] = {2: "H2", 3: "W2"}
    torch.onnx.export(model, example, out_path, opset_version=opset, input_names=ordered,
                      output_names=[OUTPUT_NAME], dynamic_axes=dynamic)
    return out_path


def _sha256(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def run(args, log):
    manifest_path = os.path.join(args.data, "manifest.json")
    manifest, dataset = load_dataset(args.data)
    summary = manifest.get("summary", {})
    log("  dataset: %d train / %d val pairs; manifest margin min %.4f, noise %.4f, detail ratio max %.3f"
        % (dataset["sizes"]["train"], dataset["sizes"]["val"],
           summary.get("margin", {}).get("min", float("nan")),
           summary.get("noise", {}).get("max", float("nan")),
           summary.get("detail_ratio", {}).get("max", float("nan"))))

    requested = ["color"] + [name.strip() for name in args.inputs.split(",") if name.strip()]
    available = {"color"} | {key for key in ("depth", "motion", "history") if key in dataset["train"]}
    missing = [name for name in requested if name not in available]
    if missing:
        raise SystemExit(
            "this dataset has no %s (it has: %s). A model cannot be given an input the data does not "
            "contain, and inventing zeros for it would measure nothing." % (", ".join(missing),
                                                                           ", ".join(sorted(available))))
    requested = [name for name in ("color", "depth", "motion", "history") if name in requested]
    log("  inputs: %s%s" % (",".join(requested),
                            " (history available)" if dataset["has_history"] else ""))

    zeroed = None if args.zero_input == "none" else args.zero_input
    if zeroed:
        # Ablation training: the input is removed from training *and* validation, so the comparison is
        # like for like. Measuring what an input is worth is the only way to tell a model that fails to
        # use it apart from data on which it cannot be used.
        for split in ("train", "val"):
            dataset[split][zeroed] = torch.zeros_like(dataset[split][zeroed])
        log("  ablation: '%s' is zeroed for training and validation" % zeroed)

    device, device_facts = resolve_device(args.device, log)
    # The split is moved to the device once, not per batch: the dataset is small enough to live there
    # whole, and a transfer per step would dominate a model this size.
    for split in ("train", "val"):
        dataset[split] = {key: value.to(device) for key, value in dataset[split].items()}
    if device.type == "cuda":
        torch.backends.cudnn.benchmark = True

    sampler = GpuSampler() if device.type == "cuda" else None
    if sampler is not None:
        sampler.start()
        torch.cuda.synchronize()   # so the wall clock times the GPU's work, not the kernel launches
    started = time.time()
    model, parameters, first_loss, last_loss = train(dataset, requested, args.epochs, args.batch_size,
                                                     args.channels, args.depth_channels,
                                                     args.motion_channels, args.history_channels,
                                                     args.learning_rate, args.warmup_epochs,
                                                     args.seed, device, log)
    if device.type == "cuda":
        torch.cuda.synchronize()
    seconds = time.time() - started
    gpu_usage = None
    if sampler is not None:
        sampler.stop()
        gpu_usage = sampler.summary()
        log("  gpu: %s over %d samples; peak allocated by torch %.1f MB"
            % (gpu_usage.get("utilization_percent", "not measured"), gpu_usage["samples"],
               torch.cuda.max_memory_allocated() / (1 << 20)))
    log("  training: %.1f s total, %.1f ms/epoch" % (seconds, seconds / max(args.epochs, 1) * 1000.0))

    val = dataset["val"]
    full = measure(model, val)
    keys = list(val.keys())

    def ablation(name):
        """How much the output changes when `name` is zeroed. Only inputs the model actually consumes are
        measured, so a colour-only model reports zeros for the others rather than numbers from weights it
        does not have."""
        if name not in model.inputs:
            return 0.0
        return float((full["output"] - measure(model, val, zero=name)["output"]).abs().mean())

    depth_ablation = ablation("depth")
    motion_ablation = ablation("motion")
    history_ablation = ablation("history")
    # The metrics a caller checks, not only L1. Computed for the model and for the bilinear baseline on the
    # same held-out frames, so the comparison is like for like and the baseline's score is visible too.
    model_quality = quality_metrics.evaluate(full["output"], val["target"])
    baseline_quality = quality_metrics.evaluate(full["baseline"], val["target"])
    numbers = {"val_l1": full["l1"], "val_baseline_l1": full["baseline_l1"], "drift": full["drift"],
               "depth_ablation": depth_ablation, "motion_ablation": motion_ablation,
               "history_ablation": history_ablation,
               "ssim": model_quality["ssim"], "psnr_db": model_quality["psnr_db"],
               "ms_ssim": model_quality["ms_ssim"],
               "baseline_ssim": baseline_quality["ssim"],
               "baseline_psnr_db": baseline_quality["psnr_db"],
               "baseline_ms_ssim": baseline_quality["ms_ssim"],
               "train_first_loss": first_loss, "train_last_loss": last_loss,
               "train_progress": (first_loss - last_loss) / max(first_loss, 1e-9),
               "improvement": 1.0 - full["l1"] / max(full["baseline_l1"], 1e-9)}
    log("  val L1 %.5f against the bilinear baseline's %.5f -> %.2f%% better; drift from baseline %.5f"
        % (numbers["val_l1"], numbers["val_baseline_l1"], numbers["improvement"] * 100.0,
           numbers["drift"]))
    log("  ablations (how much the output moves when the input is zeroed): depth %.5f, motion %.5f, "
        "history %.5f" % (depth_ablation, motion_ablation, history_ablation))
    log("  quality: ssim %.4f psnr %.2f dB against the bilinear baseline's ssim %.4f psnr %.2f dB"
        % (numbers["ssim"], numbers["psnr_db"], numbers["baseline_ssim"],
           numbers["baseline_psnr_db"]))
    # MS-SSIM beside SSIM, because the two disagree exactly where a still-image metric is weakest: SSIM at the
    # pixel scale says nothing about whether the reconstruction is right at the scale the eye reads, and the
    # multi-scale term is what a commercial upscaler's structure claims are usually quoted in.
    scales = quality_metrics.ms_ssim_scales(val["target"].shape[-2:]
                                           if val["target"].ndim >= 3 else (0, 0))
    log("  ms-ssim: %.4f against the bilinear baseline's %.4f (%d of 5 scales at this resolution)"
        % (numbers["ms_ssim"], numbers["baseline_ms_ssim"], scales))
    log("  training progress: residual L1 %.5f -> %.5f (%.1f%% lower)"
        % (first_loss, last_loss, numbers["train_progress"] * 100.0))

    failures = check_gates(numbers, zeroed, model.inputs)
    report = {"model": "nrr_upscaler_trained", "parameters": parameters, "inputs": list(model.inputs),
              "channels": args.channels,
              "depth_channels": args.depth_channels, "motion_channels": args.motion_channels,
              "epochs": args.epochs, "batch_size": args.batch_size,
              "learning_rate": args.learning_rate, "seed": args.seed,
              "zeroed_input": zeroed,
              "device": device_facts,
              "gpu": gpu_usage or {"samples": 0,
                                   "note": "not a CUDA run, so utilization was not sampled"},
              "gpu_torch_peak_memory_mb": (round(torch.cuda.max_memory_allocated() / (1 << 20))
                                           if device.type == "cuda" else None),
              "train_seconds": round(seconds, 2),
              "dataset": {"dir": args.data, "manifest_sha256": _sha256(manifest_path),
                          "generator": manifest.get("generator"), "seed": manifest.get("seed"),
                          "count": manifest.get("count"), "sizes": dataset["sizes"]},
              "measured": numbers,
              "gates": {"min_improvement": MIN_IMPROVEMENT, "baseline_floor": BASELINE_FLOOR,
                        "conditioning_floor": CONDITIONING_FLOOR, "failures": failures}}
    report_path = os.path.splitext(args.out)[0] + ".report.json"

    if failures:
        # A model that does not qualify is not exported at all, and the refusal is written down: an
        # exported file with a warning printed next to it gets used anyway.
        log("  REFUSING to export: %d gate(s) failed, so this model does not qualify" % len(failures))
        for failure in failures:
            log("    - %s" % failure)
        with open(report_path, "w", encoding="utf-8", newline="\n") as handle:
            json.dump(report, handle, indent=2)
            handle.write("\n")
        log("  report: %s (the refusal is recorded, not swallowed)" % report_path)
        return 1

    export_onnx(model, args.out, args.size, model.inputs)
    verification = verify_export(model, args.out, take(val, slice(0, 1), keys))
    report["export"] = {"path": args.out, "opset": 17, "sha256": _sha256(args.out),
                        "verify": verification}
    # Dynamic H/W is what makes the graph usable by the runtime at sizes it was not trained at, so it is
    # checked rather than assumed.
    try:
        import onnxruntime
        session = onnxruntime.InferenceSession(args.out, providers=["CPUExecutionProvider"])
        other = args.size + 32
        widths = {"color": 3, "depth": 1, "motion": 2, "history": 3}
        produced = list(session.run([OUTPUT_NAME], {
            name: np.zeros((1, widths[name], other, other), np.float32)
            for name in model.inputs})[0].shape)
        expected = [1, 3, other * 2, other * 2]
        report["export"]["dynamic_size_check"] = {"input_size": other, "output_shape": produced,
                                                  "expected": expected}
        if produced != expected:
            log("  FAILED: the exported graph is not dynamic in H/W (got %s, expected %s)"
                % (produced, expected))
            return 1
    except ImportError:
        report["export"]["dynamic_size_check"] = {"checked": False}

    with open(report_path, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(report, handle, indent=2)
        handle.write("\n")
    log("  exported: %s (%d parameters, %.1f s of training)" % (args.out, parameters, seconds))
    if verification.get("checked"):
        log("  onnxruntime %s agrees with PyTorch to %.2e; dynamic H/W verified"
            % (verification["onnxruntime"], verification["max_abs_difference"]))
    log("  report: %s" % report_path)
    return 0


def verify_export(model, out_path, batch):
    """Confirms the exported graph agrees with PyTorch, using onnxruntime when it is installed. An
    export nobody checked is a file, not a deliverable."""
    try:
        import onnxruntime
    except ImportError:
        return {"checked": False, "reason": "onnxruntime is not installed"}
    import onnx
    onnx.checker.check_model(onnx.load(out_path))
    session = onnxruntime.InferenceSession(out_path, providers=["CPUExecutionProvider"])
    keys = [name for name in ("color", "depth", "motion", "history") if name in model.inputs]
    # .cpu() because the batch lives on the model's device and numpy cannot read a CUDA tensor; onnxruntime
    # is happiest with plain host arrays.
    feeds = {name: batch[name].detach().cpu().numpy() for name in keys}
    # The reference run uses the model's own device for the same reason export_onnx does: torch refuses to
    # convolve a CPU tensor with a CUDA weight, and onnxruntime is happiest with plain CPU arrays.
    device = next(model.parameters()).device
    with torch.no_grad():
        reference = model(*[batch[name].to(device) for name in keys]).cpu().numpy()
    produced = session.run([OUTPUT_NAME], feeds)[0]
    return {"checked": True, "onnxruntime": onnxruntime.__version__,
            "max_abs_difference": float(np.max(np.abs(reference - produced)))}


def self_test():
    """Proves the gates are not decorative without needing a training run: the baseline itself must be
    rejected, and so must a model that improves the image while ignoring its conditioning."""
    cases = [
        ("the baseline itself", {"val_l1": 0.02, "val_baseline_l1": 0.02, "drift": 0.0,
                                 "depth_ablation": 0.0, "motion_ablation": 0.0,
                                 "history_ablation": 0.0, "train_progress": 0.5},
         ("color", "depth", "motion"), 4),
        ("better but conditioning-blind", {"val_l1": 0.015, "val_baseline_l1": 0.02, "drift": 0.002,
                                           "depth_ablation": 0.0, "motion_ablation": 0.0,
                                           "history_ablation": 0.0, "train_progress": 0.5},
         ("color", "depth", "motion"), 2),
        # This case only fails if the history gate is applied, which is why each case carries the input set
        # it is about: a model with no history weights cannot be failed for ignoring history, and a model
        # that has them must be.
        ("better but history-blind", {"val_l1": 0.015, "val_baseline_l1": 0.02, "drift": 0.002,
                                      "depth_ablation": 0.001, "motion_ablation": 0.001,
                                      "history_ablation": 0.0, "train_progress": 0.5},
         ("color", "depth", "motion", "history"), 1),
        ("better and conditioning-aware", {"val_l1": 0.015, "val_baseline_l1": 0.02, "drift": 0.002,
                                           "depth_ablation": 0.001, "motion_ablation": 0.001,
                                           "history_ablation": 0.001, "train_progress": 0.5},
         ("color", "depth", "motion", "history"), 0),
        # A run that learned nothing must be rejected even when it happens to look acceptable on the other
        # numbers, because a degenerate run is not a comparison result. This is the failure that hid in
        # five of the eight stage-4 runs.
        ("stalled run", {"val_l1": 0.01, "val_baseline_l1": 0.02, "drift": 0.002,
                         "depth_ablation": 0.001, "motion_ablation": 0.001, "history_ablation": 0.001,
                         "train_progress": 0.0, "train_first_loss": 0.0148, "train_last_loss": 0.0148},
         ("color", "depth", "motion", "history"), 1),
    ]
    problems = 0
    for name, numbers, inputs, expected in cases:
        found = check_gates(numbers, inputs=inputs)
        if len(found) == expected:
            print("  %-32s %d gate(s) failed, as expected" % (name, len(found)))
        else:
            print("  %-32s expected %d failures, got %d - the gates are wrong"
                  % (name, expected, len(found)))
            problems += 1
        for reason in found:
            print("      - %s" % reason)
    return 1 if problems else 0


def main(argv):
    parser = argparse.ArgumentParser(description="Train the in-house NRR upscaler.")
    parser.add_argument("--data", default="models/training-data/v1")
    parser.add_argument("--out", default="models/nrr_upscaler_trained.onnx")
    parser.add_argument("--epochs", type=int, default=60)
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--channels", type=int, default=32,
                        help="network width; 64 gives roughly 0.27M parameters")
    parser.add_argument("--depth-channels", type=int, default=8)
    parser.add_argument("--motion-channels", type=int, default=8)
    parser.add_argument("--history-channels", type=int, default=8)
    parser.add_argument("--inputs", default="depth,motion",
                        help="comma-separated inputs besides color, which is always first: a subset of "
                             "depth,motion,history. This is the comparison - a model given history is a "
                             "different model from one that is not, and the run reports which is better")
    parser.add_argument("--learning-rate", type=float, default=2e-3)
    parser.add_argument("--warmup-epochs", type=int, default=5,
                        help="linear learning-rate warmup. Added because 2 of 10 seeds failed early - one "
                             "froze with the output at the baseline, one learned only 2.9% better than it - "
                             "and both are the pathology a warmup addresses on a zero-initialised head")
    parser.add_argument("--seed", type=int, default=20260930)
    parser.add_argument("--size", type=int, default=64,
                        help="the input size the model was trained at, used for the export example")
    parser.add_argument("--device", default="auto", choices=("auto", "cpu", "cuda"),
                        help="auto uses the GPU whenever torch can provide one; cuda refuses to run "
                             "on the CPU instead of pretending")
    parser.add_argument("--zero-input", default="none", choices=("none", "depth", "motion", "history"),
                        help="ablation run: zero this input for training and validation, to measure "
                             "what it is worth")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args(argv[1:])
    if args.self_test:
        return self_test()
    torch.set_num_threads(os.cpu_count() or 4)
    return run(args, lambda message: print(message, flush=True))


def conv(in_channels, out_channels, kernel=3):
    return nn.Conv2d(in_channels, out_channels, kernel, padding=kernel // 2)


class ResidualBlock(nn.Module):
    """Two 3x3 convolutions and an add, which is the refinement stage architecture.md describes.

    Leaky activations, not ReLU, and the reason is measured rather than stylistic. Five of eight stage-4
    runs sat at exactly the untrained-model loss: the output convolution is zero-initialised (so the
    untrained model is exactly the bilinear baseline), which means the gradient reaching every upstream
    layer is W_out^T * grad and is exactly zero until that weight moves. A plain ReLU that an early Adam
    step drives negative across a whole channel then zeroes the features feeding that convolution, so
    grad_W_out = grad * features is zero too, and the network freezes in an absorbing state it cannot
    leave. A leaking activation keeps those features non-zero, so the weight keeps moving and the rest of
    the network keeps its gradient path."""

    def __init__(self, channels):
        super().__init__()
        self.body = nn.Sequential(conv(channels, channels), nn.LeakyReLU(0.01, inplace=True),
                                  conv(channels, channels))

    def forward(self, x):
        return torch.nn.functional.leaky_relu(x + self.body(x), 0.01)


class Upscaler(nn.Module):
    """A reduced version of models/architecture.md - the same stages at smaller widths, because the
    pairs are 2x at these sizes and a 2.5M-parameter network would be neither trainable here nor
    measurable against a fixture. `channels=64` gives roughly 0.27M parameters.

    `inputs` names which tensors this model consumes, and it is a parameter rather than a constant because
    that is the question: a model given history is a different model from one given only colour, and which
    of them is better has to be run rather than assumed. A branch is built only for an input in the set, so
    a colour-only model has no depth, motion or history weights at all - the comparison is between models,
    not between a model and its own zeroed inputs."""

    def __init__(self, channels=32, depth_channels=8, motion_channels=8, history_channels=8,
                 inputs=("color", "depth", "motion")):
        super().__init__()
        self.inputs = tuple(inputs)
        # Leaky throughout, for the same measured reason as ResidualBlock: a feature map that is exactly
        # zero anywhere upstream of the zero-initialised output convolution cuts the only gradient path the
        # network has.
        self.feature = nn.Sequential(conv(3, channels), nn.LeakyReLU(0.01, inplace=True),
                                     conv(channels, channels), nn.LeakyReLU(0.01, inplace=True))
        fused = channels
        if "depth" in self.inputs:
            self.depth = conv(1, depth_channels)
            fused += depth_channels
        if "motion" in self.inputs:
            self.motion = conv(2, motion_channels)
            fused += motion_channels
        if "history" in self.inputs:
            self.history = conv(3, history_channels)
            fused += history_channels
        self.fusion = conv(fused, channels * 4)
        self.shuffle = nn.PixelShuffle(2)
        self.refine = nn.Sequential(conv(channels, channels), nn.LeakyReLU(0.01, inplace=True))
        self.block1 = ResidualBlock(channels)
        self.block2 = ResidualBlock(channels)
        self.output = conv(channels, 3)
        self.skip = nn.Upsample(scale_factor=2, mode="bilinear", align_corners=False)
        # Start as the baseline: a zeroed output convolution plus the skip means the untrained model is
        # exactly the bilinear upsample, so any improvement measured later is something learned.
        nn.init.zeros_(self.output.weight)
        nn.init.zeros_(self.output.bias)

    def residual(self, color, depth=None, motion=None, history=None):
        features = self.feature(color)
        parts = [features]
        if "depth" in self.inputs:
            parts.append(self.depth(depth))
        if "motion" in self.inputs:
            parts.append(self.motion(motion))
        if "history" in self.inputs:
            parts.append(self.history(history))
        features = self.refine(self.shuffle(self.fusion(torch.cat(parts, dim=1))))
        features = self.block2(self.block1(features))
        return self.output(features)

    def forward(self, color, depth=None, motion=None, history=None):
        return self.skip(color) + self.residual(color, depth, motion, history)


def baseline_upscale(color):
    """The thing the model has to beat, computed exactly the way the model's own skip does."""
    return torch.nn.functional.interpolate(color, scale_factor=2, mode="bilinear", align_corners=False)


def measure(model, batch, zero=None):
    """The numbers the gates use. `zero` names an input to replace with zeros, which is how each input's
    contribution is measured rather than assumed - including history, which is the whole point of the
    comparison this exists to settle."""
    with torch.no_grad():
        color = batch["color"]
        depth = batch.get("depth")
        motion = batch.get("motion")
        history = batch.get("history")
        if zero == "depth" and depth is not None:
            depth = torch.zeros_like(depth)
        if zero == "motion" and motion is not None:
            motion = torch.zeros_like(motion)
        if zero == "history" and history is not None:
            history = torch.zeros_like(history)
        output = model(color, depth, motion, history)
        baseline = baseline_upscale(color)
        return {"l1": float(torch.nn.functional.l1_loss(output, batch["target"])),
                "baseline_l1": float(torch.nn.functional.l1_loss(baseline, batch["target"])),
                "drift": float((output - baseline).abs().mean()),
                "output": output,
                "baseline": baseline}


def train(dataset, inputs, epochs, batch_size, channels, depth_channels, motion_channels,
          history_channels, learning_rate, warmup_epochs, seed, device, log):
    torch.manual_seed(seed)
    model = Upscaler(channels, depth_channels, motion_channels, history_channels,
                     inputs=inputs).to(device)
    parameters = sum(p.numel() for p in model.parameters())
    log("  model: %d parameters, inputs=%s, channels=%d, batch=%d, epochs=%d, lr=%g"
        % (parameters, ",".join(inputs), channels, batch_size, epochs, learning_rate))

    keys = list(dataset["train"].keys())
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    train_split = dataset["train"]
    count = dataset["sizes"]["train"]
    generator = torch.Generator().manual_seed(seed)
    first_loss = last_loss = None
    for epoch in range(1, epochs + 1):
        # Linear warmup. The output convolution starts at zero (which is what makes the untrained model
        # exactly the bilinear baseline), so the first Adam steps move a weight that has no history and
        # Adam's step size is largest exactly there. Ten seeds measured the consequence: two of them failed -
        # one froze with the output at 4e-05 of the baseline, one learned a real residual but only 2.9%
        # better than it - and both are early-training pathologies, which is what a warmup addresses.
        if warmup_epochs > 0:
            ramp = min(1.0, float(epoch) / float(warmup_epochs))
            for group in optimizer.param_groups:
                group["lr"] = learning_rate * ramp
        order = torch.randperm(count, generator=generator)
        model.train()
        total, batches = 0.0, 0
        for start in range(0, count, batch_size):
            batch = take(train_split, order[start:start + batch_size], keys)
            optimizer.zero_grad()
            # The loss is on the correction the skip cannot supply, not on the whole image: the skip
            # already carries the low frequencies, and weighting those equally would let the model coast
            # on the baseline and still report a small number.
            prediction = model.residual(batch["color"], batch.get("depth"), batch.get("motion"),
                                        batch.get("history"))
            truth = batch["target"] - baseline_upscale(batch["color"])
            loss = torch.nn.functional.l1_loss(prediction, truth)
            loss.backward()
            optimizer.step()
            total += float(loss)
            batches += 1
        epoch_loss = total / max(batches, 1)
        if first_loss is None:
            first_loss = epoch_loss
        last_loss = epoch_loss
        if epoch == 1 or epoch == epochs or epoch % max(1, epochs // 5) == 0:
            log("  epoch %3d/%d  residual L1 %.5f" % (epoch, epochs, epoch_loss))
    model.eval()
    return model, parameters, (first_loss or 0.0), (last_loss or 0.0)


# The entry point belongs at the end of the file: this guard sat above conv()/Upscaler()/train() for a
# while, so running the script called main() before those names existed and failed with a NameError that
# pointed at the wrong function.
if __name__ == "__main__":
    sys.exit(main(sys.argv))

