#!/usr/bin/env python3
"""train_nrr.py - train the in-house upscaler on pairs generated by gen_training_pairs.py.

Why this exists: models/nrr_upscaler_v0.1.onnx is a skeleton whose refinement output is zero, so it is
an identity-preserving bilinear upsample with no learned weights. This is the first model in the
repository whose weights come from data we own and whose quality is measured against the baseline it
has to beat.

What is trained: a small 2x upscaler - feature extraction, depth and motion fusion, PixelShuffle
upsampling, two residual blocks, output projection, and a bilinear skip. The skip is deliberate: the
network learns the *correction* to the naive baseline rather than the image, so "beats bilinear" is a
statement about something learned, and a zero residual is exactly the baseline - which the gates below
detect instead of assuming.

The gates, all measured on held-out scenes rather than read off the training loss:
    beats the baseline   val L1 must be at least MIN_IMPROVEMENT below the bilinear upscale's
    is not the baseline  the output must differ from the bilinear upscale by more than BASELINE_FLOOR
    uses conditioning    zeroing depth, and zeroing motion, must each change the output. A model that
                         ignores an input the roadmap asked for has not been trained on it, and no
                         training loss would ever reveal that.
    reproducible         the same seed reproduces the same validation numbers

Usage:
    python tools/train_nrr.py --data models/training-data/v1 --out models/nrr_upscaler_trained.onnx
    python tools/train_nrr.py --self-test    # the gates must reject a model that is the baseline

Requires: pip install torch (CPU is enough), numpy, onnx. onnxruntime is optional and used only to
confirm that the exported graph agrees with PyTorch.
"""

import argparse
import hashlib
import json
import os
import sys
import time

import numpy as np
import torch
import torch.nn as nn

# The names the C++ runtime reads out of the graph (runtime/onnx_runtime.cpp reads the session's own
# input and output names, and these are the ones models/architecture.md specifies).
INPUT_NAMES = ("color", "depth", "motion")
OUTPUT_NAME = "output"

# Measured thresholds, not preferences: each one is a floor below which the claim would be cosmetic.
MIN_IMPROVEMENT = 0.05      # at least 5% below the bilinear baseline on held-out scenes
BASELINE_FLOOR = 1e-3       # output must differ from the bilinear baseline by more than this
CONDITIONING_FLOOR = 1e-4   # zeroing an input must change the output by more than this


def load_dataset(data_dir):
    """Loads the manifest and the pairs it names, as float32 tensors in NCHW order."""
    manifest_path = os.path.join(data_dir, "manifest.json")
    if not os.path.exists(manifest_path):
        raise SystemExit("%s has no manifest.json - run tools/gen_training_pairs.py first" % data_dir)
    with open(manifest_path, encoding="utf-8") as handle:
        manifest = json.load(handle)

    buckets = {"train": [], "val": []}
    for entry in manifest["pairs"]:
        path = os.path.join(data_dir, entry["file"])
        with np.load(path) as pair:
            buckets[entry["split"]].append({
                "color": torch.from_numpy(pair["input"].transpose(2, 0, 1)[None].copy()),
                "depth": torch.from_numpy(pair["depth"][None, None].copy()),
                "motion": torch.from_numpy(pair["motion"].transpose(2, 0, 1)[None].copy()),
                "target": torch.from_numpy(pair["target"].transpose(2, 0, 1)[None].copy())})

    for split in ("train", "val"):
        if not buckets[split]:
            raise SystemExit(
                "the dataset has no %s pairs (train=%d, val=%d) - regenerate with a smaller "
                "--val-every, or more pairs" % (split, len(buckets["train"]), len(buckets["val"])))

    dataset = {}
    for split, items in buckets.items():
        dataset[split] = {key: torch.cat([item[key] for item in items], dim=0)
                          for key in ("color", "depth", "motion", "target")}
    dataset["sizes"] = {split: len(items) for split, items in buckets.items()}
    return manifest, dataset


def take(batch, index):
    """Slices a whole split down to one batch, keeping the key names the model and metrics use."""
    return {key: batch[key][index] for key in ("color", "depth", "motion", "target")}


def check_gates(numbers, zeroed=None):
    """Returns the reasons a model fails to qualify, as a list, so a run reports every failure rather
    than only the first. Called before anything is exported, and used by the self-test.

    `zeroed` names an input that this run deliberately ablated: a model cannot be blamed for ignoring an
    input it was never given, so that one conditioning gate is skipped and the reason is recorded."""
    failures = []
    if numbers["val_l1"] > numbers["val_baseline_l1"] * (1.0 - MIN_IMPROVEMENT):
        failures.append(
            "does not beat the baseline: val L1 %.5f against the bilinear baseline's %.5f, which is "
            "not at least %.0f%% lower" % (numbers["val_l1"], numbers["val_baseline_l1"],
                                           MIN_IMPROVEMENT * 100.0))
    if numbers["drift"] <= BASELINE_FLOOR:
        failures.append(
            "is the baseline: its output differs from the bilinear upscale by only %.6f (needs > "
            "%.4f), so nothing was learned" % (numbers["drift"], BASELINE_FLOOR))
    for field in ("depth_ablation", "motion_ablation"):
        if zeroed and field.startswith(zeroed):
            continue
        if numbers[field] <= CONDITIONING_FLOOR:
            failures.append(
                "ignores %s: zeroing it changes the output by only %.6f (needs > %.4f)"
                % (field.split("_")[0], numbers[field], CONDITIONING_FLOOR))
    return failures


def export_onnx(model, out_path, size, opset=17):
    """Exports with the input and output names architecture.md specifies and dynamic H/W, so the
    runtime is not tied to the size this model happened to be trained at."""
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    example = (torch.zeros(1, 3, size, size), torch.zeros(1, 1, size, size),
               torch.zeros(1, 2, size, size))
    dynamic = {name: {2: "H", 3: "W"} for name in INPUT_NAMES}
    dynamic[OUTPUT_NAME] = {2: "H2", 3: "W2"}
    torch.onnx.export(model, example, out_path, opset_version=opset, input_names=list(INPUT_NAMES),
                      output_names=[OUTPUT_NAME], dynamic_axes=dynamic)
    return out_path


def _sha256(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def run(args, log):
    manifest_path = os.path.join(args.data, "manifest.json")
    manifest, dataset = load_dataset(args.data)
    summary = manifest.get("summary", {})
    log("  dataset: %d train / %d val pairs; manifest margin min %.4f, noise %.4f, detail ratio max %.3f"
        % (dataset["sizes"]["train"], dataset["sizes"]["val"],
           summary.get("margin", {}).get("min", float("nan")),
           summary.get("noise", {}).get("max", float("nan")),
           summary.get("detail_ratio", {}).get("max", float("nan"))))

    zeroed = None if args.zero_input == "none" else args.zero_input
    if zeroed:
        # Ablation training: the input is removed from training *and* validation, so the comparison is
        # like for like. Measuring what an input is worth is the only way to tell a model that fails to
        # use it apart from data on which it cannot be used.
        for split in ("train", "val"):
            dataset[split][zeroed] = torch.zeros_like(dataset[split][zeroed])
        log("  ablation: '%s' is zeroed for training and validation" % zeroed)

    started = time.time()
    model, parameters = train(dataset, args.epochs, args.batch_size, args.channels,
                              args.depth_channels, args.motion_channels, args.learning_rate,
                              args.seed, log)
    seconds = time.time() - started

    val = dataset["val"]
    full = measure(model, val)
    depth_ablation = float((full["output"] - measure(model, val, zero="depth")["output"]).abs().mean())
    motion_ablation = float((full["output"] - measure(model, val, zero="motion")["output"]).abs().mean())
    numbers = {"val_l1": full["l1"], "val_baseline_l1": full["baseline_l1"], "drift": full["drift"],
               "depth_ablation": depth_ablation, "motion_ablation": motion_ablation,
               "improvement": 1.0 - full["l1"] / max(full["baseline_l1"], 1e-9)}
    log("  val L1 %.5f against the bilinear baseline's %.5f -> %.2f%% better; drift from baseline %.5f"
        % (numbers["val_l1"], numbers["val_baseline_l1"], numbers["improvement"] * 100.0,
           numbers["drift"]))
    log("  conditioning: zeroing depth changes the output by %.5f, zeroing motion by %.5f"
        % (depth_ablation, motion_ablation))

    failures = check_gates(numbers, zeroed)
    report = {"model": "nrr_upscaler_trained", "parameters": parameters, "channels": args.channels,
              "depth_channels": args.depth_channels, "motion_channels": args.motion_channels,
              "epochs": args.epochs, "batch_size": args.batch_size,
              "learning_rate": args.learning_rate, "seed": args.seed,
              "zeroed_input": zeroed,
              "train_seconds": round(seconds, 2),
              "dataset": {"dir": args.data, "manifest_sha256": _sha256(manifest_path),
                          "generator": manifest.get("generator"), "seed": manifest.get("seed"),
                          "count": manifest.get("count"), "sizes": dataset["sizes"]},
              "measured": numbers,
              "gates": {"min_improvement": MIN_IMPROVEMENT, "baseline_floor": BASELINE_FLOOR,
                        "conditioning_floor": CONDITIONING_FLOOR, "failures": failures}}
    report_path = os.path.splitext(args.out)[0] + ".report.json"

    if failures:
        # A model that does not qualify is not exported at all, and the refusal is written down: an
        # exported file with a warning printed next to it gets used anyway.
        log("  REFUSING to export: %d gate(s) failed, so this model does not qualify" % len(failures))
        for failure in failures:
            log("    - %s" % failure)
        with open(report_path, "w", encoding="utf-8", newline="\n") as handle:
            json.dump(report, handle, indent=2)
            handle.write("\n")
        log("  report: %s (the refusal is recorded, not swallowed)" % report_path)
        return 1

    export_onnx(model, args.out, args.size)
    verification = verify_export(model, args.out, take(val, slice(0, 1)))
    report["export"] = {"path": args.out, "opset": 17, "sha256": _sha256(args.out),
                        "verify": verification}
    # Dynamic H/W is what makes the graph usable by the runtime at sizes it was not trained at, so it is
    # checked rather than assumed.
    try:
        import onnxruntime
        session = onnxruntime.InferenceSession(args.out, providers=["CPUExecutionProvider"])
        other = args.size + 32
        produced = list(session.run([OUTPUT_NAME], {
            "color": np.zeros((1, 3, other, other), np.float32),
            "depth": np.zeros((1, 1, other, other), np.float32),
            "motion": np.zeros((1, 2, other, other), np.float32)})[0].shape)
        expected = [1, 3, other * 2, other * 2]
        report["export"]["dynamic_size_check"] = {"input_size": other, "output_shape": produced,
                                                  "expected": expected}
        if produced != expected:
            log("  FAILED: the exported graph is not dynamic in H/W (got %s, expected %s)"
                % (produced, expected))
            return 1
    except ImportError:
        report["export"]["dynamic_size_check"] = {"checked": False}

    with open(report_path, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(report, handle, indent=2)
        handle.write("\n")
    log("  exported: %s (%d parameters, %.1f s of training)" % (args.out, parameters, seconds))
    if verification.get("checked"):
        log("  onnxruntime %s agrees with PyTorch to %.2e; dynamic H/W verified"
            % (verification["onnxruntime"], verification["max_abs_difference"]))
    log("  report: %s" % report_path)
    return 0


def verify_export(model, out_path, batch):
    """Confirms the exported graph agrees with PyTorch, using onnxruntime when it is installed. An
    export nobody checked is a file, not a deliverable."""
    try:
        import onnxruntime
    except ImportError:
        return {"checked": False, "reason": "onnxruntime is not installed"}
    import onnx
    onnx.checker.check_model(onnx.load(out_path))
    session = onnxruntime.InferenceSession(out_path, providers=["CPUExecutionProvider"])
    feeds = {name: batch[key].numpy()
             for name, key in zip(INPUT_NAMES, ("color", "depth", "motion"))}
    with torch.no_grad():
        reference = model(batch["color"], batch["depth"], batch["motion"]).numpy()
    produced = session.run([OUTPUT_NAME], feeds)[0]
    return {"checked": True, "onnxruntime": onnxruntime.__version__,
            "max_abs_difference": float(np.max(np.abs(reference - produced)))}


def self_test():
    """Proves the gates are not decorative without needing a training run: the baseline itself must be
    rejected, and so must a model that improves the image while ignoring its conditioning."""
    cases = [
        ("the baseline itself", {"val_l1": 0.02, "val_baseline_l1": 0.02, "drift": 0.0,
                                 "depth_ablation": 0.0, "motion_ablation": 0.0}, 4),
        ("better but conditioning-blind", {"val_l1": 0.015, "val_baseline_l1": 0.02, "drift": 0.002,
                                           "depth_ablation": 0.0, "motion_ablation": 0.0}, 2),
        ("better and conditioning-aware", {"val_l1": 0.015, "val_baseline_l1": 0.02, "drift": 0.002,
                                           "depth_ablation": 0.001, "motion_ablation": 0.001}, 0),
    ]
    problems = 0
    for name, numbers, expected in cases:
        found = check_gates(numbers)
        if len(found) == expected:
            print("  %-32s %d gate(s) failed, as expected" % (name, len(found)))
        else:
            print("  %-32s expected %d failures, got %d - the gates are wrong"
                  % (name, expected, len(found)))
            problems += 1
        for reason in found:
            print("      - %s" % reason)
    return 1 if problems else 0


def main(argv):
    parser = argparse.ArgumentParser(description="Train the in-house NRR upscaler.")
    parser.add_argument("--data", default="models/training-data/v1")
    parser.add_argument("--out", default="models/nrr_upscaler_trained.onnx")
    parser.add_argument("--epochs", type=int, default=60)
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--channels", type=int, default=32,
                        help="network width; 64 gives roughly 0.27M parameters")
    parser.add_argument("--depth-channels", type=int, default=8)
    parser.add_argument("--motion-channels", type=int, default=8)
    parser.add_argument("--learning-rate", type=float, default=2e-3)
    parser.add_argument("--seed", type=int, default=20260930)
    parser.add_argument("--size", type=int, default=64,
                        help="the input size the model was trained at, used for the export example")
    parser.add_argument("--zero-input", default="none", choices=("none", "depth", "motion"),
                        help="ablation run: zero this input for training and validation, to measure "
                             "what it is worth")
    parser.add_argument("--self-test", action="store_true")
    args = parser.parse_args(argv[1:])
    if args.self_test:
        return self_test()
    torch.set_num_threads(os.cpu_count() or 4)
    return run(args, lambda message: print(message, flush=True))


def conv(in_channels, out_channels, kernel=3):
    return nn.Conv2d(in_channels, out_channels, kernel, padding=kernel // 2)


class ResidualBlock(nn.Module):
    """Two 3x3 convolutions and an add, which is the refinement stage architecture.md describes."""

    def __init__(self, channels):
        super().__init__()
        self.body = nn.Sequential(conv(channels, channels), nn.ReLU(inplace=True),
                                  conv(channels, channels))

    def forward(self, x):
        return torch.relu(x + self.body(x))


class Upscaler(nn.Module):
    """A reduced version of models/architecture.md - the same stages at smaller widths, because the
    pairs are 2x at these sizes and a 2.5M-parameter network would be neither trainable here nor
    measurable against a fixture. `channels=64` gives roughly 0.27M parameters."""

    def __init__(self, channels=32, depth_channels=8, motion_channels=8):
        super().__init__()
        self.feature = nn.Sequential(conv(3, channels), nn.ReLU(inplace=True),
                                     conv(channels, channels), nn.ReLU(inplace=True))
        self.depth = conv(1, depth_channels)
        self.motion = conv(2, motion_channels)
        self.fusion = conv(channels + depth_channels + motion_channels, channels * 4)
        self.shuffle = nn.PixelShuffle(2)
        self.refine = nn.Sequential(conv(channels, channels), nn.ReLU(inplace=True))
        self.block1 = ResidualBlock(channels)
        self.block2 = ResidualBlock(channels)
        self.output = conv(channels, 3)
        self.skip = nn.Upsample(scale_factor=2, mode="bilinear", align_corners=False)
        # Start as the baseline: a zeroed output convolution plus the skip means the untrained model is
        # exactly the bilinear upsample, so any improvement measured later is something learned.
        nn.init.zeros_(self.output.weight)
        nn.init.zeros_(self.output.bias)

    def residual(self, color, depth, motion):
        features = self.feature(color)
        features = torch.cat([features, self.depth(depth), self.motion(motion)], dim=1)
        features = self.refine(self.shuffle(self.fusion(features)))
        features = self.block2(self.block1(features))
        return self.output(features)

    def forward(self, color, depth, motion):
        return self.skip(color) + self.residual(color, depth, motion)


def baseline_upscale(color):
    """The thing the model has to beat, computed exactly the way the model's own skip does."""
    return torch.nn.functional.interpolate(color, scale_factor=2, mode="bilinear", align_corners=False)


def measure(model, batch, zero=None):
    """The numbers the gates use. `zero` names an input to replace with zeros, which is how the use of
    conditioning is measured rather than assumed."""
    with torch.no_grad():
        color, depth, motion = batch["color"], batch["depth"], batch["motion"]
        if zero == "depth":
            depth = torch.zeros_like(depth)
        if zero == "motion":
            motion = torch.zeros_like(motion)
        output = model(color, depth, motion)
        baseline = baseline_upscale(color)
        return {"l1": float(torch.nn.functional.l1_loss(output, batch["target"])),
                "baseline_l1": float(torch.nn.functional.l1_loss(baseline, batch["target"])),
                "drift": float((output - baseline).abs().mean()),
                "output": output,
                "baseline": baseline}


def train(dataset, epochs, batch_size, channels, depth_channels, motion_channels, learning_rate,
          seed, log):
    torch.manual_seed(seed)
    model = Upscaler(channels, depth_channels, motion_channels)
    parameters = sum(p.numel() for p in model.parameters())
    log("  model: %d parameters, channels=%d, batch=%d, epochs=%d, lr=%g"
        % (parameters, channels, batch_size, epochs, learning_rate))

    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    train_split = dataset["train"]
    count = dataset["sizes"]["train"]
    generator = torch.Generator().manual_seed(seed)
    for epoch in range(1, epochs + 1):
        order = torch.randperm(count, generator=generator)
        model.train()
        total, batches = 0.0, 0
        for start in range(0, count, batch_size):
            batch = take(train_split, order[start:start + batch_size])
            optimizer.zero_grad()
            # The loss is on the correction the skip cannot supply, not on the whole image: the skip
            # already carries the low frequencies, and weighting those equally would let the model coast
            # on the baseline and still report a small number.
            prediction = model.residual(batch["color"], batch["depth"], batch["motion"])
            truth = batch["target"] - baseline_upscale(batch["color"])
            loss = torch.nn.functional.l1_loss(prediction, truth)
            loss.backward()
            optimizer.step()
            total += float(loss)
            batches += 1
        if epoch == 1 or epoch == epochs or epoch % max(1, epochs // 5) == 0:
            log("  epoch %3d/%d  residual L1 %.5f" % (epoch, epochs, total / max(batches, 1)))
    model.eval()
    return model, parameters


# The entry point belongs at the end of the file: this guard sat above conv()/Upscaler()/train() for a
# while, so running the script called main() before those names existed and failed with a NameError that
# pointed at the wrong function.
if __name__ == "__main__":
    sys.exit(main(sys.argv))

