// ---------------------------------------------------------------------------
// test_jitter.cpp
//
// The runtime now has a notion of the sub-pixel offset a frame was sampled at,
// because without one the engine cannot feed a jitter-aware model the information
// it was trained on. That makes runtime/nrr_jitter.cpp a second implementation of
// something that already exists in Python (tools/train_nrr.py::dejitter), and two
// implementations that disagree are worse than one: a model measured in Python
// would behave differently in the engine while every harness number stayed green.
//
// So this pins the C++ to exact values produced by the Python side on a
// deterministic fixture, the same way test_quality_parity.cpp pins PSNR/SSIM.
//
// The fixture is a linear ramp in x with a quarter-weight ramp in y - chosen
// because interpolation blur cannot hide a sign error on a ramp. A sinusoidal or
// textured fixture would soften under a second bilinear pass and could let a
// backwards sign pass as merely "slightly worse", which is the specific bug these
// values were chosen to catch. Interior samples land on exact binary fractions, so
// the comparison is tight rather than tolerant.
//
// The expected constants were generated by running the Python mirror on this same
// fixture and are reproduced verbatim rather than recomputed: a test that derives
// its own expectation with the code under test proves nothing.
// ---------------------------------------------------------------------------
#include "test_framework.h"
#include "nrr_jitter.h"
#include "nrr_inference.h"
#include "nrr_temporal.h"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <vector>

namespace nrr {
namespace test {

namespace jitter_fixture {

/* Uniquely prefixed: main.cpp compiles every test file into one translation unit,
 * so bare names collide with the anonymous-namespace fixtures in the other files. */
const uint32_t jf_w = 64;
const uint32_t jf_h = 64;
const float jf_offset_x = 0.3f;
const float jf_offset_y = 0.2f;

/* The un-jittered signal the fixture represents. Single channel: the correction is
 * per-pixel geometry and does not care how many channels ride along, which
 * dejitter_nchw's channel loop is covered for separately. */
std::vector<float> jf_scene() {
    std::vector<float> scene(static_cast<size_t>(jf_w) * jf_h, 0.0f);
    for (uint32_t y = 0; y < jf_h; ++y) {
        for (uint32_t x = 0; x < jf_w; ++x) {
            scene[static_cast<size_t>(y) * jf_w + x] =
                (static_cast<float>(x) + 0.25f * static_cast<float>(y)) / 64.0f;
        }
    }
    return scene;
}

/* A frame captured with its content displaced by +offset, i.e. input(x) = scene(x - offset).
 * Built by sampling the scene backward, which is what the capture does - verified against the
 * captured pixels (tools/aa_samples_probe.py) after the opposite direction was found to double the
 * misalignment instead of removing it. */
std::vector<float> jf_capture(const std::vector<float>& scene, float ox, float oy) {
    std::vector<float> out(scene.size(), 0.0f);
    for (uint32_t y = 0; y < jf_h; ++y) {
        for (uint32_t x = 0; x < jf_w; ++x) {
            const float u = std::min(std::max(static_cast<float>(x) - ox, 0.0f),
                                     static_cast<float>(jf_w) - 1.0f);
            const float v = std::min(std::max(static_cast<float>(y) - oy, 0.0f),
                                     static_cast<float>(jf_h) - 1.0f);
            const int x0 = static_cast<int>(std::floor(u));
            const int y0 = static_cast<int>(std::floor(v));
            const int x1 = std::min(x0 + 1, static_cast<int>(jf_w) - 1);
            const int y1 = std::min(y0 + 1, static_cast<int>(jf_h) - 1);
            const float lx = u - static_cast<float>(x0);
            const float ly = v - static_cast<float>(y0);
            const float top = scene[static_cast<size_t>(y0) * jf_w + x0] * (1.0f - lx)
                            + scene[static_cast<size_t>(y0) * jf_w + x1] * lx;
            const float bottom = scene[static_cast<size_t>(y1) * jf_w + x0] * (1.0f - lx)
                               + scene[static_cast<size_t>(y1) * jf_w + x1] * lx;
            out[static_cast<size_t>(y) * jf_w + x] = top * (1.0f - ly) + bottom * ly;
        }
    }
    return out;
}

double jf_mean_abs_error(const std::vector<float>& a, const std::vector<float>& b) {
    double total = 0.0;
    for (size_t i = 0; i < a.size(); ++i) total += std::fabs(static_cast<double>(a[i] - b[i]));
    return total / static_cast<double>(a.size());
}

} // namespace jitter_fixture
/* Zero offset must be the identity, not merely "close". An un-jittered renderer
 * takes this path on every frame, and a small bias here would silently tax every
 * non-jittered user. */
NRR_TEST(test_jitter_zero_offset_is_identity) {
    const std::vector<float> scene = jitter_fixture::jf_scene();
    std::vector<float> out;
    NRR_ASSERT(dejitter_nchw(scene, 1, jitter_fixture::jf_w, jitter_fixture::jf_h,
                             JitterOffset(0.0f, 0.0f), out),
               "a zero offset must still produce a valid frame");
    NRR_EXPECT_EQ(out.size(), scene.size(), "identity must not change the size");
    for (size_t i = 0; i < scene.size(); ++i) {
        if (out[i] != scene[i]) {
            NRR_ASSERT(false, "a zero offset must be exactly the identity");
        }
    }
}

/* The offset plane is two numbers per frame broadcast over the frame, in x-then-y
 * channel order. If this layout drifts from the trainer's, every jitter-aware model
 * quietly degrades to the control it was trained to beat, with no error anywhere. */
NRR_TEST(test_jitter_plane_layout_matches_the_trainer) {
    std::vector<float> plane;
    NRR_ASSERT(build_jitter_plane(JitterOffset(0.3f, -0.2f), 8, 4, plane),
               "a valid size must produce a plane");
    NRR_EXPECT_EQ(plane.size(), static_cast<size_t>(2) * 8 * 4, "plane must be 2 x H x W");
    for (size_t i = 0; i < 32; ++i) {
        NRR_EXPECT_EQ(plane[i], 0.3f, "channel 0 must carry x on every pixel");
        NRR_EXPECT_EQ(plane[32 + i], -0.2f, "channel 1 must carry y on every pixel");
    }
    std::vector<float> untouched(3, 7.0f);
    NRR_ASSERT(!build_jitter_plane(JitterOffset(0.0f, 0.0f), 0, 4, untouched),
               "a zero-width plane must be refused");
    NRR_EXPECT_EQ(untouched[0], 7.0f, "a refused build must not touch the output");
}

/* The property the whole feature rests on: correcting by the offset the frame was
 * captured at must recover the scene far better than ignoring it. */
NRR_TEST(test_jitter_correcting_the_offset_recovers_the_scene) {
    using namespace jitter_fixture;
    const std::vector<float> scene = jf_scene();
    const std::vector<float> captured = jf_capture(scene, jf_offset_x, jf_offset_y);

    std::vector<float> corrected, ignored;
    NRR_ASSERT(dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(jf_offset_x, jf_offset_y), corrected),
               "correcting by the capture offset must succeed");
    NRR_ASSERT(dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(0.0f, 0.0f), ignored),
               "ignoring the offset must succeed");

    const double corrected_error = jf_mean_abs_error(corrected, scene);
    const double ignored_error = jf_mean_abs_error(ignored, scene);
    NRR_ASSERT(corrected_error < ignored_error * 0.1,
               "correcting the offset must beat ignoring it by a wide margin; got "
               + std::to_string(corrected_error) + " against " + std::to_string(ignored_error));
}

/* A backwards sign must be visibly worse than being told nothing at all. This is
 * the check that separates "uses the offset" from "uses the offset correctly", and
 * it is the one the training ablation structurally cannot make: a graph that ignored
 * the input entirely would pass an ablation test while being useless. */
NRR_TEST(test_jitter_wrong_sign_is_worse_than_no_offset) {
    using namespace jitter_fixture;
    const std::vector<float> scene = jf_scene();
    const std::vector<float> captured = jf_capture(scene, jf_offset_x, jf_offset_y);

    std::vector<float> ignored, backwards;
    dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(0.0f, 0.0f), ignored);
    dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(-jf_offset_x, -jf_offset_y), backwards);

    NRR_ASSERT(jf_mean_abs_error(backwards, scene) > jf_mean_abs_error(ignored, scene),
               "a backwards offset must be worse than no offset; a sign error would pass this wrongly");
}
/* Parity with the Python implementation this mirrors. Constants generated by
 * tools/train_nrr.py::dejitter on this same fixture; if either side drifts, one of
 * the two fails. The tolerance is float32 accumulation over a 64x64 ramp, not a
 * modelling allowance. */
NRR_TEST(test_jitter_matches_the_python_reference) {
    using namespace jitter_fixture;
    const double kTolerance = 1e-6;
    const std::vector<float> scene = jf_scene();
    const std::vector<float> captured = jf_capture(scene, jf_offset_x, jf_offset_y);

    std::vector<float> corrected, ignored, backwards;
    dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(jf_offset_x, jf_offset_y), corrected);
    dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(0.0f, 0.0f), ignored);
    dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(-jf_offset_x, -jf_offset_y), backwards);

    NRR_ASSERT(std::fabs(jf_mean_abs_error(corrected, scene) - 0.000145808) < kTolerance,
               "mean error after correcting must match the Python reference");
    NRR_ASSERT(std::fabs(jf_mean_abs_error(ignored, scene) - 0.005383285) < kTolerance,
               "mean error with the offset withheld must match the Python reference");
    NRR_ASSERT(std::fabs(jf_mean_abs_error(backwards, scene) - 0.010742160) < kTolerance,
               "mean error with a backwards offset must match the Python reference");

    /* Regenerated by tools/regen_jitter_fixture.py after the convention was flipped to the capture's.
     * The samples are what catch a flip: on a linear ramp the two conventions are mirror images, so the
     * mean errors barely move (0.000145808 against 0.000145804 before), while these differ at the fifth
     * decimal - the first sample by 1.6e-3, far outside the 1e-6 tolerance. */
    const int samples[5][3] = {{0, 0, 0}, {10, 20, 1}, {32, 32, 2}, {63, 63, 3}, {5, 50, 4}};
    const double expected[5] = {0.003906244, 0.351562500, 0.625000000, 1.225000024, 0.800781250};
    for (const auto& sample : samples) {
        const size_t index = static_cast<size_t>(sample[0]) * jf_w + static_cast<size_t>(sample[1]);
        NRR_ASSERT(std::fabs(static_cast<double>(corrected[index]) - expected[sample[2]]) < kTolerance,
                   "de-jittered sample " + std::to_string(sample[1]) + "," + std::to_string(sample[0])
                   + " must match the Python reference");
    }
}

/* The correction is geometry, not an upscale: shape in, same shape out. A caller
 * feeding a frame it did not size correctly is refused rather than having a short
 * buffer read as if it were pixels. */
NRR_TEST(test_jitter_rejects_malformed_input) {
    std::vector<float> out;
    NRR_ASSERT(!dejitter_nchw(std::vector<float>(16, 0.0f), 0, 4, 4, JitterOffset(0.3f, 0.2f), out),
               "zero channels must be refused");
    NRR_ASSERT(!dejitter_nchw(std::vector<float>(16, 0.0f), 1, 0, 4, JitterOffset(0.3f, 0.2f), out),
               "zero width must be refused");
    NRR_ASSERT(!dejitter_nchw(std::vector<float>(16, 0.0f), 1, 8, 8, JitterOffset(0.3f, 0.2f), out),
               "a buffer smaller than the declared frame must be refused");
    NRR_ASSERT(dejitter_nchw(std::vector<float>(16, 0.0f), 1, 4, 4, JitterOffset(0.3f, 0.2f), out),
               "an exactly-sized buffer must be accepted, so the check above failed on size");
    NRR_EXPECT_EQ(out.size(), static_cast<size_t>(16), "an accepted call must fill the buffer");
}

/* Multi-channel frames must have every channel corrected, independently. A loop that
 * only touched channel 0 would still pass every single-channel test above. */
NRR_TEST(test_jitter_corrects_every_channel) {
    const uint32_t w = 16, h = 8;
    const int channels = 3;
    std::vector<float> frame(static_cast<size_t>(w) * h * channels, 0.0f);
    const size_t plane = static_cast<size_t>(w) * h;
    for (size_t i = 0; i < plane; ++i) {
        frame[i] = static_cast<float>(i % w) / static_cast<float>(w);
        frame[plane + i] = 1.0f - static_cast<float>(i % w) / static_cast<float>(w);
        frame[2 * plane + i] = 0.5f;
    }
    std::vector<float> out;
    NRR_ASSERT(dejitter_nchw(frame, channels, w, h, JitterOffset(0.4f, 0.3f), out),
               "a multi-channel frame must be accepted");
    NRR_EXPECT_EQ(out.size(), frame.size(), "multi-channel correction must preserve the size");
    /* The flat channel must come back exactly flat: a constant is invariant under any
     * resampling, so this detects cross-channel bleed with no tolerance games. */
    for (size_t i = 0; i < plane; ++i) {
        NRR_ASSERT(std::fabs(out[2 * plane + i] - 0.5f) < 1e-6,
                   "a constant channel must survive resampling unchanged, which catches channel bleed");
    }
}

/* History must carry each frame's own offset, and hand it back with the frame it
 * belongs to. Reporting the *present* frame's offset instead would be wrong in a way
 * that is invisible at runtime: both offsets are small, both are plausible, and the
 * history would be warped by the difference without any error being raised. */
NRR_TEST(test_jitter_history_records_each_frames_own_offset) {
    TemporalHistory history;
    history.set_max_frames(4);
    const std::vector<float> color(16 * 16 * 3, 0.0f);
    const std::vector<float> depth(16 * 16, 0.0f);
    const std::vector<float> motion(16 * 16 * 2, 0.0f);

    history.add_frame(0, 0.0f, color, depth, motion, 16, 16,
                      NRR_TEXTURE_FORMAT_RGB8, NRR_TEXTURE_FORMAT_R32F, JitterOffset(0.25f, -0.5f));
    /* A frame recorded without an offset, as an un-jittered renderer would. */
    history.add_frame(1, 0.016f, color, depth, motion, 16, 16,
                      NRR_TEXTURE_FORMAT_RGB8, NRR_TEXTURE_FORMAT_R32F);

    std::vector<float> got_color, got_depth, got_motion;
    uint32_t width = 0, height = 0;
    JitterOffset jitter;

    /* Retrieval returns the newest entry strictly older than the requested index, so
     * asking for 1 yields frame 0 (the jittered one) and asking for 2 yields frame 1
     * (the un-jittered one). */
    NRR_ASSERT(history.get_previous_frame(1, got_color, got_depth, got_motion, width, height, jitter),
               "the jittered frame must be retrievable");
    NRR_ASSERT(std::fabs(jitter.x - 0.25f) < 1e-6 && std::fabs(jitter.y + 0.5f) < 1e-6,
               "the retrieved offset must be the one that frame was recorded with, not the newest entry's");

    NRR_ASSERT(history.get_previous_frame(2, got_color, got_depth, got_motion, width, height, jitter),
               "a frame older than index 2 must still be found");
    NRR_ASSERT(jitter.is_zero(),
               "a frame recorded without an offset must come back as the identity, not uninitialised");

    /* The older overload must keep working and must not be a separate code path. */
    NRR_ASSERT(history.get_previous_frame(2, got_color, got_depth, got_motion, width, height),
               "the original overload must still retrieve the frame");

    /* Not-found means "nothing recorded is older than this index", not "the index is
     * beyond everything". Asking for 99 finds frame 1, because frame 1 *is* older
     * than 99; only asking for 0 leaves nothing older, since frame 0 is the oldest
     * entry. Both directions are asserted because the distinction is the retrieval
     * rule itself, and a caller clearing history on a scene cut depends on it. */
    NRR_ASSERT(history.get_previous_frame(99, got_color, got_depth, got_motion, width, height, jitter),
               "an index past every entry must still find the newest one, since it is older than it");
    JitterOffset untouched(9.0f, 9.0f);
    NRR_ASSERT(!history.get_previous_frame(0, got_color, got_depth, got_motion, width, height, untouched),
               "nothing is older than the oldest recorded frame");
    NRR_ASSERT(untouched.x == 9.0f && untouched.y == 9.0f,
               "a failed retrieval must leave the caller's offset untouched, not silently reset it");
}

/* A jitter-aware model declares a `jitter` input. If the classifier does not
 * recognise it, the tensor is left unfed, which is indistinguishable from feeding a
 * zero offset - so the model silently runs as the control it was trained to beat.
 * Pinned for the names the trainer actually exports and for the ordering hazard. */
NRR_TEST(test_jitter_input_names_classify_as_the_offset) {
    NRR_ASSERT(classify_tensor_role("jitter") == TensorRole::Jitter, "'jitter' must be the offset");
    NRR_ASSERT(classify_tensor_role("Jitter") == TensorRole::Jitter, "matching must be case-insensitive");
    NRR_ASSERT(classify_tensor_role("subpixel_offset") == TensorRole::Jitter, "'subpixel' must be the offset");
    NRR_ASSERT(classify_tensor_role("jittered_input") == TensorRole::Jitter,
               "a colour synonym inside a jitter name must not win - that would feed a 2-channel offset");
    /* The other roles must be unaffected by the new, earlier match. */
    NRR_ASSERT(classify_tensor_role("color") == TensorRole::Color, "colour must still be colour");
    NRR_ASSERT(classify_tensor_role("depth") == TensorRole::Depth, "depth must still be depth");
    NRR_ASSERT(classify_tensor_role("motion") == TensorRole::Motion, "motion must still be motion");
    NRR_ASSERT(classify_tensor_role("unrelated") == TensorRole::Other, "an unknown name must stay Other");
}

/* The history role. `history` matched no keyword at all, so it fell through to Other
 * and every binding site handed the temporal model the *colour image* as its own
 * history - a resolve given the present frame as the past one, which cannot see any
 * motion and cannot accumulate. Pinned for the names in use and for the ordering
 * hazard against colour. */
NRR_TEST(test_temporal_history_names_classify_as_history) {
    NRR_ASSERT(classify_tensor_role("history") == TensorRole::History, "'history' must be history");
    NRR_ASSERT(classify_tensor_role("History") == TensorRole::History, "matching must be case-insensitive");
    NRR_ASSERT(classify_tensor_role("prev_output") == TensorRole::History, "'prev_' must be history");
    NRR_ASSERT(classify_tensor_role("previous_frame") == TensorRole::History, "'previous' must be history");
    NRR_ASSERT(classify_tensor_role("history_color") == TensorRole::History,
               "a colour synonym inside a history name must not win - that would feed the wrong tensor");
    /* A model input merely *described* as temporal stays on the colour path. */
    NRR_ASSERT(classify_tensor_role("temporal_input") == TensorRole::Color,
               "'temporal_input' names the model's kind, not a history tensor");
    NRR_ASSERT(classify_tensor_role("color") == TensorRole::Color, "colour must still be colour");
    NRR_ASSERT(classify_tensor_role("depth") == TensorRole::Depth, "depth must still be depth");
    NRR_ASSERT(classify_tensor_role("jitter") == TensorRole::Jitter, "jitter must still be jitter");
}

/* The model wants the previous frame's *low-resolution* render. The accumulator's
 * blended history is at output resolution and would be a silent 2x mismatch, so the
 * two are stored apart - this pins that separation, including that a reset discards
 * the low-res frame rather than carrying it into the next scene. */
NRR_TEST(test_temporal_previous_input_frame_is_low_resolution_and_reset_clears_it) {
    TemporalAccumulator accumulator;
    accumulator.initialize();

    std::vector<uint8_t> out;
    uint32_t w = 0, h = 0;
    NRRTextureFormat format = NRR_TEXTURE_FORMAT_RGBA8;
    NRR_ASSERT(!accumulator.previous_input_frame(out, w, h, format),
               "a fresh accumulator must report no previous input");

    /* 4x4 RGB8 is 48 bytes; if this ever returns a size derived from the output
     * resolution instead, the separation has been lost. */
    const std::vector<uint8_t> frame(4 * 4 * 3, 0xAB);
    accumulator.record_input_frame(frame.data(), 4, 4, NRR_TEXTURE_FORMAT_RGB8);

    NRR_ASSERT(accumulator.has_previous_input(), "a recorded frame must be available");
    NRR_ASSERT(accumulator.previous_input_frame(out, w, h, format),
               "the recorded frame must be retrievable");
    NRR_EXPECT_EQ(w, 4u, "the stored frame must keep its own resolution");
    NRR_EXPECT_EQ(h, 4u, "the stored frame must keep its own resolution");
    NRR_EXPECT_EQ(out.size(), static_cast<size_t>(4 * 4 * 3), "the stored bytes must be the input's, not the output's");
    NRR_EXPECT_EQ(static_cast<int>(out[0]), 0xAB, "the stored pixels must be the ones recorded");

    accumulator.reset();
    NRR_ASSERT(!accumulator.previous_input_frame(out, w, h, format),
               "a reset must discard the low-resolution frame, or the next scene inherits the last one");

    /* A null record must clear rather than keep a stale frame. */
    accumulator.record_input_frame(frame.data(), 4, 4, NRR_TEXTURE_FORMAT_RGB8);
    accumulator.record_input_frame(nullptr, 0, 0, NRR_TEXTURE_FORMAT_RGB8);
    NRR_ASSERT(!accumulator.has_previous_input(),
               "recording nothing must clear the frame rather than leave the previous one");
}

} // namespace test
} // namespace nrr