// ---------------------------------------------------------------------------
// test_jitter.cpp
//
// The runtime now has a notion of the sub-pixel offset a frame was sampled at,
// because without one the engine cannot feed a jitter-aware model the information
// it was trained on. That makes runtime/nrr_jitter.cpp a second implementation of
// something that already exists in Python (tools/train_nrr.py::dejitter), and two
// implementations that disagree are worse than one: a model measured in Python
// would behave differently in the engine while every harness number stayed green.
//
// So this pins the C++ to exact values produced by the Python side on a
// deterministic fixture, the same way test_quality_parity.cpp pins PSNR/SSIM.
//
// The fixture is a linear ramp in x with a quarter-weight ramp in y - chosen
// because interpolation blur cannot hide a sign error on a ramp. A sinusoidal or
// textured fixture would soften under a second bilinear pass and could let a
// backwards sign pass as merely "slightly worse", which is the specific bug these
// values were chosen to catch. Interior samples land on exact binary fractions, so
// the comparison is tight rather than tolerant.
//
// The expected constants were generated by running the Python mirror on this same
// fixture and are reproduced verbatim rather than recomputed: a test that derives
// its own expectation with the code under test proves nothing.
// ---------------------------------------------------------------------------
#include "test_framework.h"
#include "nrr_jitter.h"
#include "nrr_inference.h"
#include "nrr_temporal.h"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstring>
#include <vector>

namespace nrr {
namespace test {

namespace jitter_fixture {

/* Uniquely prefixed: main.cpp compiles every test file into one translation unit,
 * so bare names collide with the anonymous-namespace fixtures in the other files. */
const uint32_t jf_w = 64;
const uint32_t jf_h = 64;
const float jf_offset_x = 0.3f;
const float jf_offset_y = 0.2f;

/* The un-jittered signal the fixture represents. Single channel: the correction is
 * per-pixel geometry and does not care how many channels ride along, which
 * dejitter_nchw's channel loop is covered for separately. */
std::vector<float> jf_scene() {
    std::vector<float> scene(static_cast<size_t>(jf_w) * jf_h, 0.0f);
    for (uint32_t y = 0; y < jf_h; ++y) {
        for (uint32_t x = 0; x < jf_w; ++x) {
            scene[static_cast<size_t>(y) * jf_w + x] =
                (static_cast<float>(x) + 0.25f * static_cast<float>(y)) / 64.0f;
        }
    }
    return scene;
}

/* A frame captured with its content displaced by +offset, i.e. input(x) = scene(x - offset).
 * Built by sampling the scene backward, which is what the capture does - verified against the
 * captured pixels (tools/aa_samples_probe.py) after the opposite direction was found to double the
 * misalignment instead of removing it. */
std::vector<float> jf_capture(const std::vector<float>& scene, float ox, float oy) {
    std::vector<float> out(scene.size(), 0.0f);
    for (uint32_t y = 0; y < jf_h; ++y) {
        for (uint32_t x = 0; x < jf_w; ++x) {
            const float u = std::min(std::max(static_cast<float>(x) - ox, 0.0f),
                                     static_cast<float>(jf_w) - 1.0f);
            const float v = std::min(std::max(static_cast<float>(y) - oy, 0.0f),
                                     static_cast<float>(jf_h) - 1.0f);
            const int x0 = static_cast<int>(std::floor(u));
            const int y0 = static_cast<int>(std::floor(v));
            const int x1 = std::min(x0 + 1, static_cast<int>(jf_w) - 1);
            const int y1 = std::min(y0 + 1, static_cast<int>(jf_h) - 1);
            const float lx = u - static_cast<float>(x0);
            const float ly = v - static_cast<float>(y0);
            const float top = scene[static_cast<size_t>(y0) * jf_w + x0] * (1.0f - lx)
                            + scene[static_cast<size_t>(y0) * jf_w + x1] * lx;
            const float bottom = scene[static_cast<size_t>(y1) * jf_w + x0] * (1.0f - lx)
                               + scene[static_cast<size_t>(y1) * jf_w + x1] * lx;
            out[static_cast<size_t>(y) * jf_w + x] = top * (1.0f - ly) + bottom * ly;
        }
    }
    return out;
}

double jf_mean_abs_error(const std::vector<float>& a, const std::vector<float>& b) {
    double total = 0.0;
    for (size_t i = 0; i < a.size(); ++i) total += std::fabs(static_cast<double>(a[i] - b[i]));
    return total / static_cast<double>(a.size());
}

} // namespace jitter_fixture
/* Zero offset must be the identity, not merely "close". An un-jittered renderer
 * takes this path on every frame, and a small bias here would silently tax every
 * non-jittered user. */
NRR_TEST(test_jitter_zero_offset_is_identity) {
    const std::vector<float> scene = jitter_fixture::jf_scene();
    std::vector<float> out;
    NRR_ASSERT(dejitter_nchw(scene, 1, jitter_fixture::jf_w, jitter_fixture::jf_h,
                             JitterOffset(0.0f, 0.0f), out),
               "a zero offset must still produce a valid frame");
    NRR_EXPECT_EQ(out.size(), scene.size(), "identity must not change the size");
    for (size_t i = 0; i < scene.size(); ++i) {
        if (out[i] != scene[i]) {
            NRR_ASSERT(false, "a zero offset must be exactly the identity");
        }
    }
}

/* The offset plane is two numbers per frame broadcast over the frame, in x-then-y
 * channel order. If this layout drifts from the trainer's, every jitter-aware model
 * quietly degrades to the control it was trained to beat, with no error anywhere. */
NRR_TEST(test_jitter_plane_layout_matches_the_trainer) {
    std::vector<float> plane;
    NRR_ASSERT(build_jitter_plane(JitterOffset(0.3f, -0.2f), 8, 4, plane),
               "a valid size must produce a plane");
    NRR_EXPECT_EQ(plane.size(), static_cast<size_t>(2) * 8 * 4, "plane must be 2 x H x W");
    for (size_t i = 0; i < 32; ++i) {
        NRR_EXPECT_EQ(plane[i], 0.3f, "channel 0 must carry x on every pixel");
        NRR_EXPECT_EQ(plane[32 + i], -0.2f, "channel 1 must carry y on every pixel");
    }
    std::vector<float> untouched(3, 7.0f);
    NRR_ASSERT(!build_jitter_plane(JitterOffset(0.0f, 0.0f), 0, 4, untouched),
               "a zero-width plane must be refused");
    NRR_EXPECT_EQ(untouched[0], 7.0f, "a refused build must not touch the output");
}

/* The property the whole feature rests on: correcting by the offset the frame was
 * captured at must recover the scene far better than ignoring it. */
NRR_TEST(test_jitter_correcting_the_offset_recovers_the_scene) {
    using namespace jitter_fixture;
    const std::vector<float> scene = jf_scene();
    const std::vector<float> captured = jf_capture(scene, jf_offset_x, jf_offset_y);

    std::vector<float> corrected, ignored;
    NRR_ASSERT(dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(jf_offset_x, jf_offset_y), corrected),
               "correcting by the capture offset must succeed");
    NRR_ASSERT(dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(0.0f, 0.0f), ignored),
               "ignoring the offset must succeed");

    const double corrected_error = jf_mean_abs_error(corrected, scene);
    const double ignored_error = jf_mean_abs_error(ignored, scene);
    NRR_ASSERT(corrected_error < ignored_error * 0.1,
               "correcting the offset must beat ignoring it by a wide margin; got "
               + std::to_string(corrected_error) + " against " + std::to_string(ignored_error));
}

/* A backwards sign must be visibly worse than being told nothing at all. This is
 * the check that separates "uses the offset" from "uses the offset correctly", and
 * it is the one the training ablation structurally cannot make: a graph that ignored
 * the input entirely would pass an ablation test while being useless. */
NRR_TEST(test_jitter_wrong_sign_is_worse_than_no_offset) {
    using namespace jitter_fixture;
    const std::vector<float> scene = jf_scene();
    const std::vector<float> captured = jf_capture(scene, jf_offset_x, jf_offset_y);

    std::vector<float> ignored, backwards;
    dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(0.0f, 0.0f), ignored);
    dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(-jf_offset_x, -jf_offset_y), backwards);

    NRR_ASSERT(jf_mean_abs_error(backwards, scene) > jf_mean_abs_error(ignored, scene),
               "a backwards offset must be worse than no offset; a sign error would pass this wrongly");
}
/* Parity with the Python implementation this mirrors. Constants generated by
 * tools/train_nrr.py::dejitter on this same fixture; if either side drifts, one of
 * the two fails. The tolerance is float32 accumulation over a 64x64 ramp, not a
 * modelling allowance. */
NRR_TEST(test_jitter_matches_the_python_reference) {
    using namespace jitter_fixture;
    const double kTolerance = 1e-6;
    const std::vector<float> scene = jf_scene();
    const std::vector<float> captured = jf_capture(scene, jf_offset_x, jf_offset_y);

    std::vector<float> corrected, ignored, backwards;
    dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(jf_offset_x, jf_offset_y), corrected);
    dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(0.0f, 0.0f), ignored);
    dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(-jf_offset_x, -jf_offset_y), backwards);

    NRR_ASSERT(std::fabs(jf_mean_abs_error(corrected, scene) - 0.000145808) < kTolerance,
               "mean error after correcting must match the Python reference");
    NRR_ASSERT(std::fabs(jf_mean_abs_error(ignored, scene) - 0.005383285) < kTolerance,
               "mean error with the offset withheld must match the Python reference");
    NRR_ASSERT(std::fabs(jf_mean_abs_error(backwards, scene) - 0.010742160) < kTolerance,
               "mean error with a backwards offset must match the Python reference");

    /* Regenerated by tools/regen_jitter_fixture.py after the convention was flipped to the capture's.
     * The samples are what catch a flip: on a linear ramp the two conventions are mirror images, so the
     * mean errors barely move (0.000145808 against 0.000145804 before), while these differ at the fifth
     * decimal - the first sample by 1.6e-3, far outside the 1e-6 tolerance. */
    const int samples[5][3] = {{0, 0, 0}, {10, 20, 1}, {32, 32, 2}, {63, 63, 3}, {5, 50, 4}};
    const double expected[5] = {0.003906244, 0.351562500, 0.625000000, 1.225000024, 0.800781250};
    for (const auto& sample : samples) {
        const size_t index = static_cast<size_t>(sample[0]) * jf_w + static_cast<size_t>(sample[1]);
        NRR_ASSERT(std::fabs(static_cast<double>(corrected[index]) - expected[sample[2]]) < kTolerance,
                   "de-jittered sample " + std::to_string(sample[1]) + "," + std::to_string(sample[0])
                   + " must match the Python reference");
    }
}

/* The correction is geometry, not an upscale: shape in, same shape out. A caller
 * feeding a frame it did not size correctly is refused rather than having a short
 * buffer read as if it were pixels. */
NRR_TEST(test_jitter_rejects_malformed_input) {
    std::vector<float> out;
    NRR_ASSERT(!dejitter_nchw(std::vector<float>(16, 0.0f), 0, 4, 4, JitterOffset(0.3f, 0.2f), out),
               "zero channels must be refused");
    NRR_ASSERT(!dejitter_nchw(std::vector<float>(16, 0.0f), 1, 0, 4, JitterOffset(0.3f, 0.2f), out),
               "zero width must be refused");
    NRR_ASSERT(!dejitter_nchw(std::vector<float>(16, 0.0f), 1, 8, 8, JitterOffset(0.3f, 0.2f), out),
               "a buffer smaller than the declared frame must be refused");
    NRR_ASSERT(dejitter_nchw(std::vector<float>(16, 0.0f), 1, 4, 4, JitterOffset(0.3f, 0.2f), out),
               "an exactly-sized buffer must be accepted, so the check above failed on size");
    NRR_EXPECT_EQ(out.size(), static_cast<size_t>(16), "an accepted call must fill the buffer");
}

/* Multi-channel frames must have every channel corrected, independently. A loop that
 * only touched channel 0 would still pass every single-channel test above. */
NRR_TEST(test_jitter_corrects_every_channel) {
    const uint32_t w = 16, h = 8;
    const int channels = 3;
    std::vector<float> frame(static_cast<size_t>(w) * h * channels, 0.0f);
    const size_t plane = static_cast<size_t>(w) * h;
    for (size_t i = 0; i < plane; ++i) {
        frame[i] = static_cast<float>(i % w) / static_cast<float>(w);
        frame[plane + i] = 1.0f - static_cast<float>(i % w) / static_cast<float>(w);
        frame[2 * plane + i] = 0.5f;
    }
    std::vector<float> out;
    NRR_ASSERT(dejitter_nchw(frame, channels, w, h, JitterOffset(0.4f, 0.3f), out),
               "a multi-channel frame must be accepted");
    NRR_EXPECT_EQ(out.size(), frame.size(), "multi-channel correction must preserve the size");
    /* The flat channel must come back exactly flat: a constant is invariant under any
     * resampling, so this detects cross-channel bleed with no tolerance games. */
    for (size_t i = 0; i < plane; ++i) {
        NRR_ASSERT(std::fabs(out[2 * plane + i] - 0.5f) < 1e-6,
                   "a constant channel must survive resampling unchanged, which catches channel bleed");
    }
}

/* History must carry each frame's own offset, and hand it back with the frame it
 * belongs to. Reporting the *present* frame's offset instead would be wrong in a way
 * that is invisible at runtime: both offsets are small, both are plausible, and the
 * history would be warped by the difference without any error being raised. */
NRR_TEST(test_jitter_history_records_each_frames_own_offset) {
    TemporalHistory history;
    history.set_max_frames(4);
    const std::vector<float> color(16 * 16 * 3, 0.0f);
    const std::vector<float> depth(16 * 16, 0.0f);
    const std::vector<float> motion(16 * 16 * 2, 0.0f);

    history.add_frame(0, 0.0f, color, depth, motion, 16, 16,
                      NRR_TEXTURE_FORMAT_RGB8, NRR_TEXTURE_FORMAT_R32F, JitterOffset(0.25f, -0.5f));
    /* A frame recorded without an offset, as an un-jittered renderer would. */
    history.add_frame(1, 0.016f, color, depth, motion, 16, 16,
                      NRR_TEXTURE_FORMAT_RGB8, NRR_TEXTURE_FORMAT_R32F);

    std::vector<float> got_color, got_depth, got_motion;
    uint32_t width = 0, height = 0;
    JitterOffset jitter;

    /* Retrieval returns the newest entry strictly older than the requested index, so
     * asking for 1 yields frame 0 (the jittered one) and asking for 2 yields frame 1
     * (the un-jittered one). */
    NRR_ASSERT(history.get_previous_frame(1, got_color, got_depth, got_motion, width, height, jitter),
               "the jittered frame must be retrievable");
    NRR_ASSERT(std::fabs(jitter.x - 0.25f) < 1e-6 && std::fabs(jitter.y + 0.5f) < 1e-6,
               "the retrieved offset must be the one that frame was recorded with, not the newest entry's");

    NRR_ASSERT(history.get_previous_frame(2, got_color, got_depth, got_motion, width, height, jitter),
               "a frame older than index 2 must still be found");
    NRR_ASSERT(jitter.is_zero(),
               "a frame recorded without an offset must come back as the identity, not uninitialised");

    /* The older overload must keep working and must not be a separate code path. */
    NRR_ASSERT(history.get_previous_frame(2, got_color, got_depth, got_motion, width, height),
               "the original overload must still retrieve the frame");

    /* Not-found means "nothing recorded is older than this index", not "the index is
     * beyond everything". Asking for 99 finds frame 1, because frame 1 *is* older
     * than 99; only asking for 0 leaves nothing older, since frame 0 is the oldest
     * entry. Both directions are asserted because the distinction is the retrieval
     * rule itself, and a caller clearing history on a scene cut depends on it. */
    NRR_ASSERT(history.get_previous_frame(99, got_color, got_depth, got_motion, width, height, jitter),
               "an index past every entry must still find the newest one, since it is older than it");
    JitterOffset untouched(9.0f, 9.0f);
    NRR_ASSERT(!history.get_previous_frame(0, got_color, got_depth, got_motion, width, height, untouched),
               "nothing is older than the oldest recorded frame");
    NRR_ASSERT(untouched.x == 9.0f && untouched.y == 9.0f,
               "a failed retrieval must leave the caller's offset untouched, not silently reset it");
}

/* A jitter-aware model declares a `jitter` input. If the classifier does not
 * recognise it, the tensor is left unfed, which is indistinguishable from feeding a
 * zero offset - so the model silently runs as the control it was trained to beat.
 * Pinned for the names the trainer actually exports and for the ordering hazard. */
NRR_TEST(test_jitter_input_names_classify_as_the_offset) {
    NRR_ASSERT(classify_tensor_role("jitter") == TensorRole::Jitter, "'jitter' must be the offset");
    NRR_ASSERT(classify_tensor_role("Jitter") == TensorRole::Jitter, "matching must be case-insensitive");
    NRR_ASSERT(classify_tensor_role("subpixel_offset") == TensorRole::Jitter, "'subpixel' must be the offset");
    NRR_ASSERT(classify_tensor_role("jittered_input") == TensorRole::Jitter,
               "a colour synonym inside a jitter name must not win - that would feed a 2-channel offset");
    /* The other roles must be unaffected by the new, earlier match. */
    NRR_ASSERT(classify_tensor_role("color") == TensorRole::Color, "colour must still be colour");
    NRR_ASSERT(classify_tensor_role("depth") == TensorRole::Depth, "depth must still be depth");
    NRR_ASSERT(classify_tensor_role("motion") == TensorRole::Motion, "motion must still be motion");
    NRR_ASSERT(classify_tensor_role("unrelated") == TensorRole::Other, "an unknown name must stay Other");
}

/* The history role. `history` matched no keyword at all, so it fell through to Other
 * and every binding site handed the temporal model the *colour image* as its own
 * history - a resolve given the present frame as the past one, which cannot see any
 * motion and cannot accumulate. Pinned for the names in use and for the ordering
 * hazard against colour. */
NRR_TEST(test_temporal_history_names_classify_as_history) {
    NRR_ASSERT(classify_tensor_role("history") == TensorRole::History, "'history' must be history");
    NRR_ASSERT(classify_tensor_role("History") == TensorRole::History, "matching must be case-insensitive");
    NRR_ASSERT(classify_tensor_role("prev_output") == TensorRole::History, "'prev_' must be history");
    NRR_ASSERT(classify_tensor_role("previous_frame") == TensorRole::History, "'previous' must be history");
    NRR_ASSERT(classify_tensor_role("history_color") == TensorRole::History,
               "a colour synonym inside a history name must not win - that would feed the wrong tensor");
    /* A model input merely *described* as temporal stays on the colour path. */
    NRR_ASSERT(classify_tensor_role("temporal_input") == TensorRole::Color,
               "'temporal_input' names the model's kind, not a history tensor");
    NRR_ASSERT(classify_tensor_role("color") == TensorRole::Color, "colour must still be colour");
    NRR_ASSERT(classify_tensor_role("depth") == TensorRole::Depth, "depth must still be depth");
    NRR_ASSERT(classify_tensor_role("jitter") == TensorRole::Jitter, "jitter must still be jitter");
}

/* The model wants the previous frame's *low-resolution* render. The accumulator's
 * blended history is at output resolution and would be a silent 2x mismatch, so the
 * two are stored apart - this pins that separation, including that a reset discards
 * the low-res frame rather than carrying it into the next scene. */
NRR_TEST(test_temporal_previous_input_frame_is_low_resolution_and_reset_clears_it) {
    TemporalAccumulator accumulator;
    accumulator.initialize();

    std::vector<uint8_t> out;
    uint32_t w = 0, h = 0;
    NRRTextureFormat format = NRR_TEXTURE_FORMAT_RGBA8;
    NRR_ASSERT(!accumulator.previous_input_frame(out, w, h, format),
               "a fresh accumulator must report no previous input");

    /* 4x4 RGB8 is 48 bytes; if this ever returns a size derived from the output
     * resolution instead, the separation has been lost. */
    const std::vector<uint8_t> frame(4 * 4 * 3, 0xAB);
    accumulator.record_input_frame(frame.data(), 4, 4, NRR_TEXTURE_FORMAT_RGB8);

    NRR_ASSERT(accumulator.has_previous_input(), "a recorded frame must be available");
    NRR_ASSERT(accumulator.previous_input_frame(out, w, h, format),
               "the recorded frame must be retrievable");
    NRR_EXPECT_EQ(w, 4u, "the stored frame must keep its own resolution");
    NRR_EXPECT_EQ(h, 4u, "the stored frame must keep its own resolution");
    NRR_EXPECT_EQ(out.size(), static_cast<size_t>(4 * 4 * 3), "the stored bytes must be the input's, not the output's");
    NRR_EXPECT_EQ(static_cast<int>(out[0]), 0xAB, "the stored pixels must be the ones recorded");

    accumulator.reset();
    NRR_ASSERT(!accumulator.previous_input_frame(out, w, h, format),
               "a reset must discard the low-resolution frame, or the next scene inherits the last one");

    /* A null record must clear rather than keep a stale frame. */
    accumulator.record_input_frame(frame.data(), 4, 4, NRR_TEXTURE_FORMAT_RGB8);
    accumulator.record_input_frame(nullptr, 0, 0, NRR_TEXTURE_FORMAT_RGB8);
    NRR_ASSERT(!accumulator.has_previous_input(),
               "recording nothing must clear the frame rather than leave the previous one");
}

/* ---------------------------------------------------------------------------
 * The phase-aligned path: the same measured convention, on the operation the
 * de-jitter does not perform.
 *
 * The constants below come from tools/regen_aa_fixture.py, which validates itself
 * before printing them: that the C++-mirrored bilinear taps agree with torch's
 * interpolate + grid_sample to 8e-8, that the capture's sign reconstructs a frame far
 * better than its mirror, and that the ordering asserted below holds in Python. Two
 * fixtures, because they pin different steps:
 *
 *   * a 64x64 bilinear capture of a 128x128 ramp, three frames at the capture's own
 *     Halton offsets, placed and averaged. On a ramp the mean equals a single placed
 *     frame, so this pins the placement - scale and sign included - and cannot see the
 *     accumulate-and-divide step at all.
 *   * a point-sampled zone plate, where the accumulation itself is pinned, plus the
 *     ordering that says the accumulator does something a de-jitter cannot.
 * --------------------------------------------------------------------------- */
namespace aa_fixture {

const uint32_t aa_hi = 128;  /* the output grid the samples are placed into */
const uint32_t aa_lo = 64;   /* the resolution the frames were rendered at */

/* The ordering fixture's plate: 0.040 radians per target pixel squared, which is the probe's
 * own plate strength in these units - about 3.3 cycles per frame pixel at the rim, far past
 * the frame grid's Nyquist limit. That strength is not decoration. In the mildly aliased
 * regime an un-jittered single frame can beat any integration (measured +7% on this same
 * fixture at k = 0.006), so an ordering test needs content that genuinely aliases, which is
 * also the content the feature exists for. */
const float aa_plate_k = 0.040f;

/* Pinned values at these points. The offsets equal aa_halton(1..3), asserted in the first
 * test, so the fixture cannot drift from the tool's frame set unnoticed. */
const int aa_points[6][2] = {{0, 0}, {10, 20}, {32, 33}, {63, 62}, {100, 101}, {127, 127}};
const double aa_resolved[6] = {0.006148727, 0.175781250, 0.320312500,
                               0.607421875, 0.984375000, 1.234699516};
const int aa_wrong_points[2][2] = {{32, 33}, {63, 62}};
const double aa_wrong[2] = {0.321614583, 0.608723958};
const double aa_one_frame[2] = {0.320312500, 0.607421875};
const int aa_plate_points[3][2] = {{20, 30}, {64, 64}, {110, 100}};
const double aa_plate_resolved[3] = {0.614664373, 0.997607489, 0.372503726};
const double aa_plate_single[3] = {0.654102142, 0.998502148, 0.546668620};

/* Halton (2,3) with index = frame + 1: the capture's own sequence, so the fixture is not a set
 * of offsets chosen to make the arithmetic work out. Computed in double and stored as float,
 * exactly as the tool does - a float32 radical inverse would show up in the pinned values,
 * since these are scaled by the resolution ratio before use. */
inline double aa_radical_inverse(int value, int radix) {
    double result = 0.0, fraction = 1.0;
    while (value > 0) {
        fraction /= static_cast<double>(radix);
        result += fraction * static_cast<double>(value % radix);
        value /= radix;
    }
    return result;
}

inline JitterOffset aa_halton(int index) {
    return JitterOffset(static_cast<float>(aa_radical_inverse(index, 2) - 0.5),
                        static_cast<float>(aa_radical_inverse(index, 3) - 0.5));
}

/* Clamped bilinear sample of a planar image at a continuous coordinate. Written out rather than
 * reused from nrr_jitter.cpp, where the tap helper is private to the implementation: a fixture
 * that borrowed it could not catch a change in it. The floor is taken *before* the clamp, which
 * is the part that is easy to get subtly wrong, and the pinned constants catch it - clamping a
 * negative coordinate to 0 and then stepping to pixel 1 is a different interpolation. */
inline float aa_sample(const std::vector<float>& plane, uint32_t width, uint32_t height,
                       float u, float v) {
    const float base_x = std::floor(u);
    const float base_y = std::floor(v);
    const int x0 = std::min(std::max(static_cast<int>(base_x), 0), static_cast<int>(width) - 1);
    const int x1 = std::min(std::max(static_cast<int>(base_x) + 1, 0), static_cast<int>(width) - 1);
    const int y0 = std::min(std::max(static_cast<int>(base_y), 0), static_cast<int>(height) - 1);
    const int y1 = std::min(std::max(static_cast<int>(base_y) + 1, 0), static_cast<int>(height) - 1);
    const float lx = u - base_x;
    const float ly = v - base_y;
    const float top = plane[static_cast<size_t>(y0) * width + x0] * (1.0f - lx)
                    + plane[static_cast<size_t>(y0) * width + x1] * lx;
    const float bottom = plane[static_cast<size_t>(y1) * width + x0] * (1.0f - lx)
                       + plane[static_cast<size_t>(y1) * width + x1] * lx;
    return top * (1.0f - ly) + bottom * ly;
}

/* The un-jittered signal at the output resolution. Same shape of fixture as jf_scene(), and
 * likewise not normalised to [0,1]: the arithmetic under test does not clamp, so a ramp that
 * stays inside the range would only be hiding that. */
std::vector<float> aa_ramp() {
    std::vector<float> out(static_cast<size_t>(aa_hi) * aa_hi, 0.0f);
    for (uint32_t y = 0; y < aa_hi; ++y) {
        for (uint32_t x = 0; x < aa_hi; ++x) {
            out[static_cast<size_t>(y) * aa_hi + x] =
                (static_cast<float>(x) + 0.25f * static_cast<float>(y)) / static_cast<float>(aa_hi);
        }
    }
    return out;
}

/* One frame of `target` on a sampling grid displaced by `offset`, in the capture's *measured*
 * convention: pixel p holds the scene at (p + 0.5 - offset) * 2 - 0.5 in target pixels, so the
 * frame's content sits at +offset * scale. Bilinear here - a surrogate that has been pre-filtered,
 * which is fine for pinning placement and useless for showing an integration gain, because a
 * pre-filtered signal has no aliasing left to resolve.
 *
 * The sign is the one that was measured on the real capture's frames, not the one that reads naturally
 * off "the renderer displaced its grid by +j": the natural reading builds the mirror of the capture and
 * validates the mirrored placement. tools/regen_aa_fixture.py now cross-checks this builder's sign
 * against the capture's own pixels on every run, and the first test below pins the invariant that makes
 * the direction unmistakable - at scale 1 this placement is exactly dejitter_nchw(). */
std::vector<float> aa_capture(const std::vector<float>& target, const JitterOffset& offset) {
    std::vector<float> out(static_cast<size_t>(aa_lo) * aa_lo, 0.0f);
    const float step = static_cast<float>(aa_hi) / static_cast<float>(aa_lo);
    for (uint32_t y = 0; y < aa_lo; ++y) {
        const float v = (static_cast<float>(y) + 0.5f - offset.y) * step - 0.5f;
        for (uint32_t x = 0; x < aa_lo; ++x) {
            const float u = (static_cast<float>(x) + 0.5f - offset.x) * step - 0.5f;
            out[static_cast<size_t>(y) * aa_lo + x] = aa_sample(target, aa_hi, aa_hi, u, v);
        }
    }
    return out;
}

inline float aa_plate_value(float x, float y) {
    const float dx = x - 0.5f * static_cast<float>(aa_hi);
    const float dy = y - 0.5f * static_cast<float>(aa_hi);
    return 0.5f + 0.5f * std::cos(aa_plate_k * (dx * dx + dy * dy));
}

/* The ground truth: the plate averaged over each pixel's footprint, i.e. a supersampled render.
 * A point-evaluated reference is itself aliased at these frequencies, and comparing one aliased
 * image against another measures the phase of two sampling grids rather than the reconstruction. */
std::vector<float> aa_plate_reference() {
    const int oversample = 4;
    std::vector<float> out(static_cast<size_t>(aa_hi) * aa_hi, 0.0f);
    for (uint32_t y = 0; y < aa_hi; ++y) {
        for (uint32_t x = 0; x < aa_hi; ++x) {
            double total = 0.0;
            for (int oy = 0; oy < oversample; ++oy) {
                for (int ox = 0; ox < oversample; ++ox) {
                    const float sx = static_cast<float>(x)
                                   + (static_cast<float>(ox) + 0.5f) / oversample - 0.5f;
                    const float sy = static_cast<float>(y)
                                   + (static_cast<float>(oy) + 0.5f) / oversample - 0.5f;
                    total += static_cast<double>(aa_plate_value(sx, sy));
                }
            }
            out[static_cast<size_t>(y) * aa_hi + x] =
                static_cast<float>(total / static_cast<double>(oversample * oversample));
        }
    }
    return out;
}

/* One frame of the plate: a *point* sample per pixel, no interpolation. That is what a rasteriser
 * writes, and it is the regime in which an integration can recover anything. Same measured grid sign
 * as aa_capture(), and for the same reason. */
std::vector<float> aa_point_frame(const JitterOffset& offset) {
    std::vector<float> out(static_cast<size_t>(aa_lo) * aa_lo, 0.0f);
    const float step = static_cast<float>(aa_hi) / static_cast<float>(aa_lo);
    for (uint32_t y = 0; y < aa_lo; ++y) {
        const float sy = (static_cast<float>(y) + 0.5f - offset.y) * step - 0.5f;
        for (uint32_t x = 0; x < aa_lo; ++x) {
            const float sx = (static_cast<float>(x) + 0.5f - offset.x) * step - 0.5f;
            out[static_cast<size_t>(y) * aa_lo + x] = aa_plate_value(sx, sy);
        }
    }
    return out;
}

/* Normalised gradient magnitude of the reference, as the probe and the tool use: a plain mean over
 * a mostly flat frame hides an edge effect in the flat fraction. Central differences inside the
 * frame and one-sided at its edges, matching numpy's gradient. */
std::vector<double> aa_edge_weights(const std::vector<float>& image) {
    std::vector<double> weights(static_cast<size_t>(aa_hi) * aa_hi, 0.0);
    double total = 0.0;
    for (uint32_t y = 0; y < aa_hi; ++y) {
        for (uint32_t x = 0; x < aa_hi; ++x) {
            const size_t here = static_cast<size_t>(y) * aa_hi + x;
            const double gx = x == 0 ? image[here + 1] - image[here]
                            : x + 1 == aa_hi ? image[here] - image[here - 1]
                            : 0.5 * (image[here + 1] - image[here - 1]);
            const double gy = y == 0 ? image[here + aa_hi] - image[here]
                            : y + 1 == aa_hi ? image[here] - image[here - aa_hi]
                            : 0.5 * (image[here + aa_hi] - image[here - aa_hi]);
            const double magnitude = std::sqrt(gx * gx + gy * gy);
            weights[here] = magnitude;
            total += magnitude;
        }
    }
    for (size_t i = 0; i < weights.size(); ++i) {
        weights[i] = total > 0.0 ? weights[i] / total : 0.0;
    }
    return weights;
}

double aa_edge_error(const std::vector<float>& candidate, const std::vector<float>& reference,
                     const std::vector<double>& weights) {
    double total = 0.0;
    for (size_t i = 0; i < candidate.size(); ++i) {
        total += std::fabs(static_cast<double>(candidate[i]) - static_cast<double>(reference[i]))
               * weights[i];
    }
    return total;
}

} // namespace aa_fixture

/* The placement parity. The pinned values come from the torch pair (interpolate + grid_sample),
 * mirrored by tools/regen_aa_fixture.py and validated against torch to 8e-8 before it printed them.
 * This is what a half-pixel convention, an offset not scaled into output pixels, or the pre-flip sign
 * cannot survive: each of those produces a plausible picture and a different number here. */
NRR_TEST(test_aa_accumulator_places_each_frame_where_it_was_sampled) {
    using namespace aa_fixture;
    const double kTolerance = 1e-6;

    /* The tool's offsets have to be the capture's own sequence, or fixture and tool have drifted
     * apart without either of them failing. */
    const JitterOffset expected[3] = {aa_halton(1), aa_halton(2), aa_halton(3)};
    NRR_ASSERT(std::fabs(expected[0].x) < 1e-6 && std::fabs(expected[0].y + 0.166666667f) < 1e-6,
               "aa_halton(1) must be Halton(2,3)'s first offset");
    NRR_ASSERT(std::fabs(expected[2].x - 0.25f) < 1e-6 && std::fabs(expected[2].y + 0.388888889f) < 1e-6,
               "aa_halton(3) must be Halton(2,3)'s third offset");

    const std::vector<float> scene = aa_ramp();
    PhaseAlignedAccumulator accumulator;
    std::vector<float> resolved;
    NRR_ASSERT(!accumulator.resolve(resolved), "a resolve with nothing accumulated must fail");
    for (int k = 0; k < 3; ++k) {
        const JitterOffset offset = aa_halton(k + 1);
        NRR_ASSERT(accumulator.add_frame(aa_capture(scene, offset), 1, aa_lo, aa_lo, aa_hi, aa_hi, offset),
                   "a valid frame must be accepted");
    }
    NRR_EXPECT_EQ(accumulator.frame_count(), 3u, "three frames must have been accumulated");

    NRR_ASSERT(accumulator.resolve(resolved), "a resolve after three frames must succeed");
    NRR_EXPECT_EQ(resolved.size(), static_cast<size_t>(aa_hi) * aa_hi,
                  "the resolve must have the output resolution");
    for (int i = 0; i < 6; ++i) {
        const size_t index = static_cast<size_t>(aa_points[i][0]) * aa_hi
                           + static_cast<size_t>(aa_points[i][1]);
        NRR_ASSERT(std::fabs(static_cast<double>(resolved[index]) - aa_resolved[i]) < kTolerance,
                   "resolved sample " + std::to_string(aa_points[i][0]) + "," + std::to_string(aa_points[i][1])
                   + " must match the Python reference; got " + std::to_string(resolved[index])
                   + " against " + std::to_string(aa_resolved[i]));
    }

    /* One frame placed with the capture's sign. On a ramp this equals the three-frame mean above - a
     * linear function is its own average under a shift - so the two pin the placement without pinning
     * the division, which the zone-plate constants in the next test do instead. */
    const JitterOffset first = aa_halton(1);
    PhaseAlignedAccumulator one_frame, flipped;
    NRR_ASSERT(one_frame.add_frame(aa_capture(scene, first), 1, aa_lo, aa_lo, aa_hi, aa_hi, first),
               "a single frame must be accepted");
    std::vector<float> one;
    NRR_ASSERT(one_frame.resolve(one), "a single-frame resolve must succeed");

    /* The same frame with the mirrored sign: the check that the pinned placement is the capture's
     * direction and not its mirror. The values differ in the third decimal - the offset times the ramp
     * slope - which is precisely the size of the misalignment being corrected. */
    NRR_ASSERT(flipped.add_frame(aa_capture(scene, first), 1, aa_lo, aa_lo, aa_hi, aa_hi,
                                 JitterOffset(-first.x, -first.y)),
               "a frame placed with the mirrored sign must still be accepted");
    std::vector<float> wrong;
    NRR_ASSERT(flipped.resolve(wrong), "the mirrored resolve must succeed");

    for (int i = 0; i < 2; ++i) {
        const size_t index = static_cast<size_t>(aa_wrong_points[i][0]) * aa_hi
                           + static_cast<size_t>(aa_wrong_points[i][1]);
        NRR_ASSERT(std::fabs(static_cast<double>(one[index]) - aa_one_frame[i]) < kTolerance,
                   "the capture's sign must place the frame where the Python reference puts it; got "
                   + std::to_string(one[index]) + " against " + std::to_string(aa_one_frame[i]));
        NRR_ASSERT(std::fabs(static_cast<double>(wrong[index]) - aa_wrong[i]) < kTolerance,
                   "the mirrored sign must place the frame where the Python reference puts *it*; got "
                   + std::to_string(wrong[index]) + " against " + std::to_string(aa_wrong[i]));
        NRR_ASSERT(std::fabs(static_cast<double>(wrong[index]) - static_cast<double>(one[index])) > 1e-3,
                   "the two signs must not produce the same frame, or this test proves nothing");
    }

    /* The invariant that makes the direction unmistakable, and that the mirrored placement fails by
     * construction: at scale 1 - an accumulation whose output grid is the frame's own grid - the
     * placement is not *like* dejitter_nchw(), it is the same operation on the same samples, so the two
     * must agree to the last bit. Two independent measurements of the capture's sign (the fixture's
     * frames and the capture's own pixels) and this structural one cannot all be satisfied by the
     * mirrored direction, which is what makes it worth asserting next to the pinned constants. */
    {
        const JitterOffset offset = aa_halton(2);
        const std::vector<float> frame = aa_capture(scene, offset);
        PhaseAlignedAccumulator native;
        std::vector<float> placed, corrected;
        NRR_ASSERT(native.add_frame(frame, 1, aa_lo, aa_lo, aa_lo, aa_lo, offset),
                   "a native-resolution accumulation must be accepted");
        NRR_ASSERT(native.resolve(placed), "a native-resolution resolve must succeed");
        NRR_ASSERT(dejitter_nchw(frame, 1, aa_lo, aa_lo, offset, corrected),
                   "de-jittering the same frame must succeed");
        double worst = 0.0;
        for (size_t i = 0; i < placed.size(); ++i) {
            worst = std::max(worst, std::fabs(static_cast<double>(placed[i])
                                              - static_cast<double>(corrected[i])));
        }
        NRR_ASSERT(worst < 1e-7,
                   "at scale 1 the placement must be dejitter_nchw() exactly; worst difference "
                   + std::to_string(worst));
    }
}

/* The claim the accumulator exists for, measured: integrating frames whose samples fell on different
 * sub-pixel positions beats one frame, and beats de-jittering every frame and then averaging - the
 * operation that corrects geometry per frame and, by putting every frame back onto the same grid,
 * removes the diversity an integration is meant to use. Python's numbers on this fixture are 0.199397
 * single, 0.143895 de-jittered, 0.135836 phase-aligned, 0.156286 phase-aligned with the mirrored sign,
 * i.e. 1.000 / 0.722 / 0.681 / 0.784 of the single-sample error. */
NRR_TEST(test_aa_accumulator_integrates_distinct_subpixel_samples) {
    using namespace aa_fixture;
    const int kFrames = 8;
    const std::vector<float> reference = aa_plate_reference();
    const std::vector<double> weights = aa_edge_weights(reference);

    std::vector<float> single;
    NRR_ASSERT(upsample_bilinear_nchw(aa_point_frame(JitterOffset(0.0f, 0.0f)), 1, aa_lo, aa_lo,
                                      aa_hi, aa_hi, single),
               "upsampling an un-jittered frame must succeed");
    for (int i = 0; i < 3; ++i) {
        const size_t index = static_cast<size_t>(aa_plate_points[i][0]) * aa_hi
                           + static_cast<size_t>(aa_plate_points[i][1]);
        NRR_ASSERT(std::fabs(static_cast<double>(single[index]) - aa_plate_single[i]) < 1e-5,
                   "the un-jittered frame's upsample must match the Python reference; got "
                   + std::to_string(single[index]) + " against " + std::to_string(aa_plate_single[i]));
    }

    PhaseAlignedAccumulator accumulator, mirrored;
    std::vector<float> de_jittered(static_cast<size_t>(aa_hi) * aa_hi, 0.0f);
    for (int k = 1; k <= kFrames; ++k) {
        const JitterOffset offset = aa_halton(k);
        const std::vector<float> frame = aa_point_frame(offset);
        NRR_ASSERT(accumulator.add_frame(frame, 1, aa_lo, aa_lo, aa_hi, aa_hi, offset),
                   "every frame of the sequence must be accepted");
        NRR_ASSERT(mirrored.add_frame(frame, 1, aa_lo, aa_lo, aa_hi, aa_hi,
                                      JitterOffset(-offset.x, -offset.y)),
                   "the mirrored accumulator must accept the same frames");

        /* The operation being replaced: correct this frame where it was rendered, then upsample it to
         * the output grid and average. It uses the shipped correction, so this column is the real
         * alternative rather than a straw man. */
        std::vector<float> corrected, upsampled;
        NRR_ASSERT(dejitter_nchw(frame, 1, aa_lo, aa_lo, offset, corrected),
                   "de-jittering a frame must succeed");
        NRR_ASSERT(upsample_bilinear_nchw(corrected, 1, aa_lo, aa_lo, aa_hi, aa_hi, upsampled),
                   "upsampling a de-jittered frame must succeed");
        for (size_t i = 0; i < de_jittered.size(); ++i) {
            de_jittered[i] += upsampled[i];
        }
    }
    for (size_t i = 0; i < de_jittered.size(); ++i) {
        de_jittered[i] /= static_cast<float>(kFrames);
    }

    std::vector<float> aligned, wrong;
    NRR_ASSERT(accumulator.resolve(aligned), "the accumulated resolve must succeed");
    NRR_ASSERT(mirrored.resolve(wrong), "the mirrored resolve must succeed");

    const double single_edge = aa_edge_error(single, reference, weights);
    const double de_jittered_edge = aa_edge_error(de_jittered, reference, weights);
    const double aligned_edge = aa_edge_error(aligned, reference, weights);
    const double wrong_edge = aa_edge_error(wrong, reference, weights);
    const std::string ratios = "single " + std::to_string(single_edge)
                             + ", de-jittered " + std::to_string(de_jittered_edge)
                             + ", aligned " + std::to_string(aligned_edge)
                             + ", mirrored " + std::to_string(wrong_edge);

    NRR_ASSERT(aligned_edge < single_edge * 0.85,
               "integrating distinct sub-pixel samples must beat one frame by a wide margin; got " + ratios);
    NRR_ASSERT(aligned_edge < de_jittered_edge * 0.95,
               "it must also beat de-jittering every frame and averaging them; got " + ratios);
    NRR_ASSERT(aligned_edge < wrong_edge * 0.95,
               "and it must beat the same integration with the mirrored sign; got " + ratios);

    /* The accumulation itself, pinned. This fixture is not linear, so unlike the ramp it can see the
     * mean. Tolerance 1e-5 rather than 1e-6: the frames here are float32 while the mirror is float64,
     * and the plate has steep local gradients - 3.3 cycles per frame pixel at the rim. */
    for (int i = 0; i < 3; ++i) {
        const size_t index = static_cast<size_t>(aa_plate_points[i][0]) * aa_hi
                           + static_cast<size_t>(aa_plate_points[i][1]);
        NRR_ASSERT(std::fabs(static_cast<double>(aligned[index]) - aa_plate_resolved[i]) < 1e-5,
                   "accumulated sample " + std::to_string(aa_plate_points[i][0]) + ","
                   + std::to_string(aa_plate_points[i][1]) + " must match the Python reference; got "
                   + std::to_string(aligned[index]) + " against " + std::to_string(aa_plate_resolved[i]));
    }
}

/* A sequence has one output grid and one channel count, and a frame that was rendered for a different
 * display is refused rather than reinterpreted - silently averaging samples placed for another grid
 * would be a wrong picture with no error anywhere. Refusal also has to leave the accumulator usable,
 * so the failure paths are checked for side effects rather than only for their return value. */
NRR_TEST(test_aa_accumulator_refuses_mixed_grids_and_bad_shapes) {
    using namespace aa_fixture;
    const std::vector<float> frame(static_cast<size_t>(aa_lo) * aa_lo, 0.5f);

    PhaseAlignedAccumulator accumulator;
    std::vector<float> out(4, 7.0f);

    /* Nothing accumulated: a resolve must refuse rather than fabricate a frame. */
    NRR_ASSERT(!accumulator.resolve(out), "a resolve with no frames must fail");
    NRR_EXPECT_EQ(out[0], 7.0f, "a refused resolve must not touch the output");

    NRR_ASSERT(!accumulator.add_frame(frame, 0, aa_lo, aa_lo, aa_hi, aa_hi, JitterOffset()),
               "a zero channel count must be refused");
    NRR_ASSERT(!accumulator.add_frame(frame, 1, 0, aa_lo, aa_hi, aa_hi, JitterOffset()),
               "a zero frame width must be refused");
    NRR_ASSERT(!accumulator.add_frame(frame, 1, aa_lo, aa_lo, 0, aa_hi, JitterOffset()),
               "a zero output width must be refused");
    NRR_ASSERT(!accumulator.add_frame(std::vector<float>(10, 0.0f), 1, aa_lo, aa_lo, aa_hi, aa_hi,
                                      JitterOffset()),
               "a short frame must be refused rather than read past its end");
    NRR_EXPECT_EQ(accumulator.frame_count(), 0u, "a refused frame must not count as accumulated");
    NRR_ASSERT(!accumulator.resolve(out), "and none of them may have left anything to resolve");

    /* One accepted frame, and then attempts to fold a different sequence into it. */
    NRR_ASSERT(accumulator.add_frame(frame, 1, aa_lo, aa_lo, aa_hi, aa_hi, JitterOffset()),
               "the first frame must be accepted");
    std::vector<float> first;
    NRR_ASSERT(accumulator.resolve(first), "one frame must resolve");
    NRR_ASSERT(!accumulator.add_frame(frame, 3, aa_lo, aa_lo, aa_hi, aa_hi, JitterOffset()),
               "a different channel count must be refused, not reinterpreted");
    NRR_ASSERT(!accumulator.add_frame(frame, 1, aa_lo, aa_lo, aa_hi / 2, aa_hi, JitterOffset()),
               "a different output grid must be refused");
    NRR_EXPECT_EQ(accumulator.frame_count(), 1u, "a refused frame must not count as accumulated");

    std::vector<float> unchanged;
    NRR_ASSERT(accumulator.resolve(unchanged), "the accumulator must still resolve");
    for (size_t i = 0; i < first.size(); ++i) {
        NRR_ASSERT(unchanged[i] == first[i],
                   "a refused frame must leave the accumulated sum exactly as it was");
    }
    NRR_EXPECT_EQ(accumulator.out_width(), aa_hi, "the grid must be the one the accepted frame set");
    NRR_EXPECT_EQ(accumulator.channels(), 1, "the channel count must be the accepted frame's");

    /* A reset has to discard, not merely restart the count. */
    accumulator.reset();
    NRR_EXPECT_EQ(accumulator.frame_count(), 0u, "a reset must clear the count");
    NRR_ASSERT(!accumulator.resolve(out), "a reset must leave nothing to resolve");
    NRR_ASSERT(accumulator.add_frame(frame, 1, aa_lo, aa_lo, aa_hi, aa_hi, JitterOffset()),
               "and the accumulator must be usable again, with its grid chosen afresh");
}

/* The resize the accumulator places through, on its own. The same-size case has to be exact rather
 * than merely close - it is the path taken when display and render resolution match, and a half-pixel
 * convention error would appear here as a small uniform blur that nothing else in the suite notices. */
NRR_TEST(test_aa_upsample_is_the_identity_at_native_resolution) {
    using namespace aa_fixture;
    const std::vector<float> source = aa_ramp();
    std::vector<float> out;
    NRR_ASSERT(upsample_bilinear_nchw(source, 1, aa_hi, aa_hi, aa_hi, aa_hi, out),
               "a same-size resize must succeed");
    NRR_EXPECT_EQ(out.size(), source.size(), "a same-size resize must not change the size");
    for (size_t i = 0; i < source.size(); ++i) {
        if (out[i] != source[i]) {
            NRR_ASSERT(false, "a same-size resize must be exactly the identity");
        }
    }

    /* A constant must stay constant at any scale: that is what a normalised filter does, and an
     * off-by-half kernel or double-weighted edge would show up as a ramp towards the border. */
    const std::vector<float> flat(static_cast<size_t>(aa_lo) * aa_lo, 0.25f);
    std::vector<float> doubled;
    NRR_ASSERT(upsample_bilinear_nchw(flat, 1, aa_lo, aa_lo, aa_hi, aa_hi, doubled),
               "an upsample must succeed");
    for (size_t i = 0; i < doubled.size(); ++i) {
        NRR_ASSERT(std::fabs(doubled[i] - 0.25f) < 1e-6f,
                   "a constant frame must upsample to the same constant");
    }

    /* Planar layout: channel 1 must be read from its own plane, not from channel 0's rows. */
    const size_t plane = static_cast<size_t>(aa_lo) * aa_lo;
    std::vector<float> two_channel(plane * 2, 0.0f);
    for (size_t i = 0; i < plane; ++i) {
        two_channel[plane + i] = 0.75f;
    }
    std::vector<float> both;
    NRR_ASSERT(upsample_bilinear_nchw(two_channel, 2, aa_lo, aa_lo, aa_hi, aa_hi, both),
               "a two-channel upsample must succeed");
    const size_t out_plane = static_cast<size_t>(aa_hi) * aa_hi;
    NRR_ASSERT(std::fabs(both[out_plane / 2]) < 1e-6f, "channel 0 must keep its own values");
    NRR_ASSERT(std::fabs(both[out_plane + out_plane / 2] - 0.75f) < 1e-6f,
               "channel 1 must keep its own values");

    NRR_ASSERT(!upsample_bilinear_nchw(flat, 1, aa_lo, aa_lo, 0, aa_hi, out),
               "a zero output width must be refused");
    NRR_ASSERT(!upsample_bilinear_nchw(flat, 1, 0, 0, aa_hi, aa_hi, out),
               "a zero source size must be refused");
    NRR_ASSERT(!upsample_bilinear_nchw(std::vector<float>(10, 0.0f), 1, aa_lo, aa_lo, aa_hi, aa_hi, out),
               "a short source must be refused rather than read past its end");
}

// ---------------------------------------------------------------------------
// The phase-aligned pass in the render path.
//
// runtime/nrr_temporal.h holds it, not runtime/nrr_jitter.cpp, because it is a
// frame-level policy rather than an image operation: which frames may be
// integrated, when the scene has moved too far to keep integrating, and what the
// caller has to say about the frame's own phase. These tests pin that policy plus
// the gate, and the composition of the pass with the reprojection blend - which
// nothing did before this revision, because every phase-aligned test passed an
// empty motion provider and the blend therefore never ran.
//
// What the pass is worth is measured in tools/aa_resolve_probe.py, and the
// numbers quoted here are from that tool with the two instrument faults it used to
// have fixed (the warp applied at half magnitude on a 2x capture, and the metric
// scoring against a target that never moved): with the reference calibrated to the
// capture's own grid, the sample-side prize is -36.9% edge error at 8 frames, and
// the blend in front of the integration costs 4-11% of it.
// ---------------------------------------------------------------------------

namespace phase_fixture {

const uint32_t pf_w = 32;
const uint32_t pf_h = 16;

/* A frame with a strong one-per-pixel ramp in x, so a placement shows up as a measurable bias: a shift
 * of `d` pixels moves every interior value by d * 255 / pf_w. */
std::vector<uint8_t> pf_ramp() {
    std::vector<uint8_t> out(static_cast<size_t>(pf_w) * pf_h * 3, 0);
    for (uint32_t y = 0; y < pf_h; ++y) {
        for (uint32_t x = 0; x < pf_w; ++x) {
            const uint8_t value = static_cast<uint8_t>(255u * x / pf_w);
            const size_t p = (static_cast<size_t>(y) * pf_w + x) * 3;
            out[p] = value;
            out[p + 1] = value;
            out[p + 2] = value;
        }
    }
    return out;
}

/* A frame input a caller would build: one frame of a jittered sequence, with the motion it is asserted
 * to have. motion_magnitude is in frame fractions and the pass converts it, so these tests set it the
 * way an engine would. */
NRRFrameInput pf_input(uint64_t index, float offset_x, float offset_y, bool jittered,
                       float motion = 0.0f) {
    NRRFrameInput input;
    input.temporal.frame_index = index;
    input.temporal.resolution_x = pf_w;
    input.temporal.resolution_y = pf_h;
    input.temporal.motion_magnitude = motion;
    input.temporal.jitter.offset_x = offset_x;
    input.temporal.jitter.offset_y = offset_y;
    input.temporal.jitter.enabled = jittered ? 1 : 0;
    return input;
}

inline uint8_t pf_pixel(const std::vector<uint8_t>& rgb8, uint32_t x, uint32_t y) {
    return rgb8[(static_cast<size_t>(y) * pf_w + x) * 3];
}

TemporalAccumulator::MotionImage pf_no_field() { return TemporalAccumulator::MotionImage(); }

/* float -> half, so a motion field can be built here in the format the accumulator's MotionImage declares
 * (RG16F; there is no RG8 in NRRTextureFormat, whatever the specification's table said). */
uint16_t pf_half(float value) {
    uint32_t bits = 0;
    std::memcpy(&bits, &value, sizeof(bits));
    const uint32_t sign = (bits >> 16) & 0x8000u;
    const int32_t exponent = static_cast<int32_t>((bits >> 23) & 0xFFu) - 127 + 15;
    const uint32_t mantissa = bits & 0x7FFFFFu;
    if (exponent <= 0) return static_cast<uint16_t>(sign);
    if (exponent >= 0x1F) return static_cast<uint16_t>(sign | 0x7C00u);
    return static_cast<uint16_t>(sign | (static_cast<uint32_t>(exponent) << 10) | (mantissa >> 13));
}

/* A valid motion field, constant across the frame: the shape an engine's camera-only field has. `dx`/`dy`
 * are in output pixels per frame, which is the unit the per-pixel restart threshold is in. Held in a
 * function-local static so the MotionImage's raw pointer stays valid for the call. */
TemporalAccumulator::MotionImage pf_field(float dx, float dy) {
    static std::vector<uint8_t> storage;
    storage.assign(static_cast<size_t>(pf_w) * pf_h * 4, 0);
    const uint16_t hx = pf_half(dx);
    const uint16_t hy = pf_half(dy);
    for (size_t i = 0; i < static_cast<size_t>(pf_w) * pf_h; ++i) {
        std::memcpy(&storage[i * 4], &hx, 2);
        std::memcpy(&storage[i * 4 + 2], &hy, 2);
    }
    TemporalAccumulator::MotionImage image;
    image.pixels = storage.data();
    image.width = pf_w;
    image.height = pf_h;
    image.format = NRR_TEXTURE_FORMAT_RG16F;
    return image;
}

/* The ramp with every value raised by `levels`, clamped: a frame whose content changed without moving, so a
 * test can tell what the blend mixed in from what the pass placed. */
std::vector<uint8_t> pf_ramp_offset(int levels) {
    std::vector<uint8_t> out = pf_ramp();
    for (size_t i = 0; i < out.size(); ++i) {
        const int raised = static_cast<int>(out[i]) + levels;
        out[i] = static_cast<uint8_t>(raised > 255 ? 255 : (raised < 0 ? 0 : raised));
    }
    return out;
}

} // namespace phase_fixture

/* Off by default, and off must be exactly what the caller had before: the frame is passed through byte
 * for byte, nothing is counted, and no note is produced. A caller that never asks for the feature must
 * not be able to tell this pass exists. */
NRR_TEST(test_phase_aligned_pass_is_off_until_asked) {
    using namespace phase_fixture;
    TemporalAccumulator accumulator;
    accumulator.initialize();

    const std::vector<uint8_t> original = pf_ramp();
    std::vector<uint8_t> rgb8 = original;
    const NRRFrameInput input = pf_input(1, 0.5f, 0.0f, true);
    const TemporalAccumulator::PhaseAlignedFrame phase =
        phase_aligned_frame_for(input, false, pf_w, pf_h, pf_w, pf_h);
    NRR_ASSERT(phase.eligible, "the fixture must be an eligible frame, or this proves nothing");
    NRR_EXPECT_EQ(accumulator.apply(input, rgb8, pf_w, pf_h, pf_no_field, phase).phase_aligned_frames,
                  0u, "an accumulator that was not asked to integrate must not integrate");
    NRR_ASSERT(rgb8 == original, "the displayed frame must be untouched with the pass off");
    NRR_ASSERT(!accumulator.is_phase_aligned_enabled(), "off is the default");

    /* And enabling it is what changes that, or the check above passes for the wrong reason. */
    accumulator.set_phase_aligned_enabled(true);
    NRR_ASSERT(accumulator.is_phase_aligned_enabled(), "the switch must report what was set");
    std::vector<uint8_t> enabled = original;
    const TemporalAccumulator::Result result =
        accumulator.apply(input, enabled, pf_w, pf_h, pf_no_field, phase);
    NRR_EXPECT_EQ(result.phase_aligned_frames, 1u, "the eligible frame must be accumulated");
    NRR_ASSERT(result.phase_note[0] != '\0', "a pass that ran must say so");
    NRR_ASSERT(enabled != original, "a frame placed by half a pixel must differ from the one given");
}


/* The integration itself, and the two facts that describe it: how many frames are in it, and that each
 * is placed by its *own* offset. On a linear ramp the mean of a +d and a -d placement is the unplaced
 * frame, so a two-frame accumulation of opposite offsets must reproduce the input - an accumulation
 * that applied one frame's offset to all of them would not. */
NRR_TEST(test_phase_aligned_pass_places_each_frame_by_its_own_offset) {
    using namespace phase_fixture;
    TemporalAccumulator accumulator;
    accumulator.initialize();
    accumulator.set_phase_aligned_enabled(true);

    const std::vector<uint8_t> original = pf_ramp();

    std::vector<uint8_t> plus = original;
    const NRRFrameInput first_input = pf_input(1, 0.5f, 0.0f, true);
    const TemporalAccumulator::Result first = accumulator.apply(
        first_input, plus, pf_w, pf_h, pf_no_field,
        phase_aligned_frame_for(first_input, false, pf_w, pf_h, pf_w, pf_h));
    NRR_EXPECT_EQ(first.phase_aligned_frames, 1u, "the first frame must start the accumulation");
    const int biased = static_cast<int>(pf_pixel(plus, 16, 8))
                     - static_cast<int>(pf_pixel(original, 16, 8));
    NRR_ASSERT(biased >= 3,
               "placing the frame by +0.5 px must move a 1/32-per-pixel ramp by about 4 levels; got "
               + std::to_string(biased));

    std::vector<uint8_t> both = original;
    const NRRFrameInput second_input = pf_input(2, -0.5f, 0.0f, true);
    const TemporalAccumulator::Result second = accumulator.apply(
        second_input, both, pf_w, pf_h, pf_no_field,
        phase_aligned_frame_for(second_input, false, pf_w, pf_h, pf_w, pf_h));
    NRR_EXPECT_EQ(second.phase_aligned_frames, 2u, "the second frame must join the accumulation");

    /* Interior pixels only: the placement clamps at the frame's edge, where a ramp is not linear across
     * the clamp and the identity above would not hold. */
    int worst = 0;
    for (uint32_t y = 1; y + 1 < pf_h; ++y) {
        for (uint32_t x = 1; x + 1 < pf_w; ++x) {
            worst = std::max(worst, std::abs(static_cast<int>(pf_pixel(both, x, y))
                                             - static_cast<int>(pf_pixel(original, x, y))));
        }
    }
    NRR_ASSERT(worst <= 3,
               "the mean of a +0.5 and a -0.5 placement is the unplaced frame on a ramp; worst "
               "interior difference " + std::to_string(worst));
}


/* The gate. Integration is only valid while the scene is still, so a frame whose declared motion exceeds
 * PHASE_ALIGNED_MOTION_GATE_PX - converted from frame fractions to frame-grid pixels by the pass itself -
 * drops what has been accumulated instead of averaging across the move, and the frame after it starts
 * again. A moving camera therefore degrades to "no integration" rather than to a blurred average of two
 * scenes, which is the failure mode the gate exists to prevent. */
NRR_TEST(test_phase_aligned_pass_resets_when_the_scene_moves) {
    using namespace phase_fixture;
    TemporalAccumulator accumulator;
    accumulator.initialize();
    accumulator.set_phase_aligned_enabled(true);

    const float still = 0.6f * PHASE_ALIGNED_MOTION_GATE_PX / static_cast<float>(pf_w);
    const float moving = 2.0f * PHASE_ALIGNED_MOTION_GATE_PX / static_cast<float>(pf_w);
    std::vector<uint8_t> frame = pf_ramp();

    for (uint64_t index = 1; index <= 2; ++index) {
        const float offset = index == 1 ? 0.25f : -0.25f;
        const NRRFrameInput input = pf_input(index, offset, 0.0f, true, still);
        accumulator.apply(input, frame, pf_w, pf_h, pf_no_field,
                          phase_aligned_frame_for(input, false, pf_w, pf_h, pf_w, pf_h));
    }
    NRR_EXPECT_EQ(accumulator.phase_aligned_frames(), 2u, "both still frames must accumulate");

    const NRRFrameInput moved_input = pf_input(3, 0.25f, 0.0f, true, moving);
    const TemporalAccumulator::Result moved = accumulator.apply(
        moved_input, frame, pf_w, pf_h, pf_no_field,
        phase_aligned_frame_for(moved_input, false, pf_w, pf_h, pf_w, pf_h));
    NRR_EXPECT_EQ(moved.phase_aligned_frames, 0u,
                  "a frame past the gate must empty the accumulation rather than join it");
    NRR_ASSERT(std::string(moved.phase_note).find("reset") != std::string::npos,
               "the note must say the accumulation was reset; got '" + std::string(moved.phase_note) + "'");

    const NRRFrameInput resumed_input = pf_input(4, 0.25f, 0.0f, true, still);
    NRR_EXPECT_EQ(accumulator.apply(resumed_input, frame, pf_w, pf_h, pf_no_field,
                                    phase_aligned_frame_for(resumed_input, false, pf_w, pf_h, pf_w, pf_h))
                      .phase_aligned_frames,
                  1u, "the frame after a reset must start a new accumulation, not resume the old one");
}


/* A sequence that does not jitter has no distinct sub-pixel phases, so there is nothing to integrate and
 * the pass must decline rather than quietly average frames: a mean of identically-phased frames is a
 * stability filter - which is what the reprojection blend is for - and calling it antialiasing would be a
 * claim with no measurement behind it. */
NRR_TEST(test_phase_aligned_pass_declines_without_distinct_phases) {
    using namespace phase_fixture;
    TemporalAccumulator accumulator;
    accumulator.initialize();
    accumulator.set_phase_aligned_enabled(true);

    const NRRFrameInput unjittered = pf_input(1, 0.4f, 0.4f, false);
    const TemporalAccumulator::PhaseAlignedFrame phase =
        phase_aligned_frame_for(unjittered, false, pf_w, pf_h, pf_w, pf_h);
    NRR_ASSERT(!phase.eligible,
               "an un-jittered sequence must not be eligible, whatever offset it happens to carry");

    const std::vector<uint8_t> original = pf_ramp();
    std::vector<uint8_t> rgb8 = original;
    const TemporalAccumulator::Result declined =
        accumulator.apply(unjittered, rgb8, pf_w, pf_h, pf_no_field, phase);
    NRR_EXPECT_EQ(declined.phase_aligned_frames, 0u, "nothing may be accumulated");
    NRR_ASSERT(rgb8 == original, "and the displayed frame must be untouched");
    NRR_ASSERT(std::string(declined.phase_note).find("off") != std::string::npos,
               "the note must say why it declined; got '" + std::string(declined.phase_note) + "'");
}

/* A scene change discards the accumulation as well, and the accumulator detects one by itself: a change
 * of render resolution means the samples belong to a scene that is no longer on screen, and a mean of the
 * old and the new is a ghost. The frame that triggers it starts the new accumulation. */
NRR_TEST(test_phase_aligned_pass_is_discarded_by_a_scene_change) {
    using namespace phase_fixture;
    TemporalAccumulator accumulator;
    accumulator.initialize();
    accumulator.set_phase_aligned_enabled(true);

    std::vector<uint8_t> frame = pf_ramp();
    const NRRFrameInput first = pf_input(1, 0.25f, 0.0f, true);
    accumulator.apply(first, frame, pf_w, pf_h, pf_no_field,
                      phase_aligned_frame_for(first, false, pf_w, pf_h, pf_w, pf_h));
    NRR_EXPECT_EQ(accumulator.phase_aligned_frames(), 1u, "the jittered frame must accumulate");

    /* The buffer has to be the size of the new grid, not the old one: apply() reads and writes
     * width*height*3 bytes of it, and handing it the smaller ramp would be an out-of-bounds write that
     * happens to look like a resolution change. */
    std::vector<uint8_t> resized(static_cast<size_t>(pf_w) * (pf_h * 2) * 3, 0x80);
    const NRRFrameInput second = pf_input(2, 0.25f, 0.0f, true);
    accumulator.apply(second, resized, pf_w, pf_h * 2, pf_no_field,
                      phase_aligned_frame_for(second, false, pf_w, pf_h * 2, pf_w, pf_h * 2));
    NRR_EXPECT_EQ(accumulator.phase_aligned_frames(), 1u,
                  "a resolution change must discard the old accumulation, leaving only the new frame");
}

/* The offset rule both render paths derive from the model's input set, pinned where it lives: an
 * accelerator backend and the CPU backend must decide the same thing about the same frame, or one
 * sequence accumulates differently depending on which one rendered it. */
NRR_TEST(test_phase_aligned_offset_rule_matches_the_two_model_kinds) {
    using namespace phase_fixture;
    const NRRFrameInput input = pf_input(1, 0.25f, -0.5f, true, 0.0f);

    /* A model that declares a `jitter` input corrected the grid itself: offset zero. */
    const TemporalAccumulator::PhaseAlignedFrame self_correcting =
        phase_aligned_frame_for(input, true, pf_w, pf_h, pf_w * 2, pf_h * 2);
    NRR_ASSERT(self_correcting.eligible, "a jittered sequence is eligible however the model behaves");
    NRR_EXPECT_EQ(self_correcting.offset_x, 0.0f,
                  "a model that de-jitters has already spent the phase; placing it would undo the model");
    NRR_EXPECT_EQ(self_correcting.offset_y, 0.0f, "both axes");

    /* A model that cannot know its grid reproduces the displacement, scaled into output pixels. */
    const TemporalAccumulator::PhaseAlignedFrame unaware =
        phase_aligned_frame_for(input, false, pf_w, pf_h, pf_w * 2, pf_h * 2);
    NRR_EXPECT_EQ(unaware.offset_x, 0.5f, "the jitter must be scaled by the resolution ratio");
    NRR_EXPECT_EQ(unaware.offset_y, -1.0f, "and so must the other axis");

    /* And an un-jittered sequence is not eligible for either kind of model. */
    const NRRFrameInput plain = pf_input(1, 0.25f, -0.5f, false);
    NRR_ASSERT(!phase_aligned_frame_for(plain, false, pf_w, pf_h, pf_w, pf_h).eligible,
               "without distinct phases there is nothing to integrate");
    NRR_ASSERT(!phase_aligned_frame_for(plain, true, pf_w, pf_h, pf_w, pf_h).eligible,
               "for either kind of model");
}


/* The per-pixel restart, and the weight that goes with it.
 *
 * A pixel the caller marks as no longer describing what is on screen is emptied and re-seeded from this
 * frame, while its neighbours keep averaging. That is what lets the still part of an image keep
 * integrating while the part that moves does not drag it into a smear - and it is why the resolve can no
 * longer divide by the frame count: a restarted pixel holds one sample where its neighbours hold several,
 * and dividing those by the sequence length would darken exactly the region that moved.
 *
 * The fixture is deliberately trivial so the numbers are exact: a constant plane whose value is the frame
 * index, placed with a zero offset (the identity), so the mean of three frames is 1 everywhere and a
 * restarted pixel holds the third frame's 2. */
NRR_TEST(test_phase_aligned_restart_empties_only_the_marked_pixels) {
    using namespace phase_fixture;
    const size_t plane = static_cast<size_t>(pf_w) * pf_h;
    PhaseAlignedAccumulator accumulator;

    std::vector<uint8_t> restart(plane, 0);
    const size_t marked = 5u * pf_w + 7u;
    for (int frame = 0; frame < 3; ++frame) {
        const std::vector<float> values(plane, static_cast<float>(frame));
        if (frame == 2) restart[marked] = 1;
        NRR_ASSERT(accumulator.add_frame(values, 1, pf_w, pf_h, pf_w, pf_h, JitterOffset(),
                                         (frame == 2) ? restart : std::vector<uint8_t>()),
                   "every frame must be accepted");
    }

    std::vector<float> resolved;
    NRR_ASSERT(accumulator.resolve(resolved), "the resolve must succeed");
    NRR_EXPECT_EQ(accumulator.frame_count(), 3u, "the sequence length is still reported as three");
    NRR_ASSERT(std::fabs(resolved[marked] - 2.0f) < 1e-6,
               "a restarted pixel must hold only the frame that restarted it; got "
               + std::to_string(resolved[marked]));
    NRR_ASSERT(std::fabs(resolved[marked + 1] - 1.0f) < 1e-6,
               "and its neighbour must keep the three-frame mean; got "
               + std::to_string(resolved[marked + 1]));
}

/* A mask that does not describe this accumulator's grid is refused rather than resized: it would
 * otherwise be indexed as if it did, which is the same class of mistake the output-resolution check
 * catches - and a refused frame must leave the accumulator usable. */
NRR_TEST(test_phase_aligned_refuses_a_mask_of_the_wrong_size) {
    using namespace phase_fixture;
    const size_t plane = static_cast<size_t>(pf_w) * pf_h;
    const std::vector<float> values(plane, 0.5f);
    PhaseAlignedAccumulator accumulator;

    NRR_ASSERT(!accumulator.add_frame(values, 1, pf_w, pf_h, pf_w, pf_h, JitterOffset(),
                                      std::vector<uint8_t>(plane - 1, 0)),
               "a mask shorter than the output grid must be refused");
    NRR_EXPECT_EQ(accumulator.frame_count(), 0u, "and must not have counted as a frame");
    NRR_ASSERT(accumulator.add_frame(values, 1, pf_w, pf_h, pf_w, pf_h, JitterOffset(),
                                     std::vector<uint8_t>(plane, 0)),
               "the same frame with a correct mask must still be accepted");
}


/* The gate's units, pinned: the constant is measured in *frame-grid* pixels, so a caller's magnitude - a
 * fraction of the frame - is converted with the frame's own width. On a 2x pipeline the output width is
 * twice that, and using it makes the gate twice as strict as the measurement behind it, which is the
 * defect this pins: the same declared fraction must be judged against the grid it was declared in. */
NRR_TEST(test_phase_aligned_gate_converts_the_magnitude_with_the_frame_width) {
    using namespace phase_fixture;
    std::vector<uint8_t> rgb8(static_cast<size_t>(64) * pf_h * 3, 128);

    /* One declared fraction, read against two different frame grids, with the output width held at 64 in
     * both: 0.15 px on a 32-wide frame is inside the gate, and the same fraction on a 64-wide frame is
     * 0.3 px and past it. A conversion that used the output width would read 0.3 px in *both* cases and
     * refuse the first one, which is what makes the accept below the discriminating observation. */
    const float fraction = 0.15f / 32.0f;

    TemporalAccumulator narrow;
    narrow.initialize();
    narrow.set_phase_aligned_enabled(true);
    const NRRFrameInput narrow_input = pf_input(1, 0.25f, 0.0f, true, fraction);
    const TemporalAccumulator::PhaseAlignedFrame narrow_phase =
        phase_aligned_frame_for(narrow_input, false, 32, pf_h, 64, pf_h);
    NRR_EXPECT_EQ(narrow_phase.frame_width, 32u,
                  "the frame's own width must be what the gate converts with");
    narrow.apply(narrow_input, rgb8, 64, pf_h, pf_no_field, narrow_phase);
    NRR_EXPECT_EQ(narrow.phase_aligned_frames(), 1u,
                  "0.15 px on the frame's own grid is inside the 0.2 px gate, even though the output grid "
                  "is twice as wide");

    TemporalAccumulator wide;
    wide.initialize();
    wide.set_phase_aligned_enabled(true);
    const NRRFrameInput wide_input = pf_input(1, 0.25f, 0.0f, true, fraction);
    const TemporalAccumulator::Result refused = wide.apply(
        wide_input, rgb8, 64, pf_h, pf_no_field,
        phase_aligned_frame_for(wide_input, false, 64, pf_h, 64, pf_h));
    NRR_EXPECT_EQ(refused.phase_aligned_frames, 0u,
                  "the same fraction on a 64-wide frame is 0.3 px and must exceed the gate - so the two "
                  "verdicts together say the magnitude was converted with the frame, not with the output");
    NRR_ASSERT(std::string(refused.phase_note).find("no field") != std::string::npos,
               "the note must be the no-field refusal; got '" + std::string(refused.phase_note) + "'");
}


/* One declared motion magnitude, two consumers, one unit.
 *
 * The blend's history weight and the phase-aligned gate both read
 * NRRFrameInput::temporal.motion_magnitude, and they used to read it as two different things: the gate
 * multiplied it by the frame width and compared pixels, while the blend compared the raw fraction against a
 * constant of 0.3 - so a real measurement (6 px of camera motion at 1920 = 0.0031) left the gate refusing the
 * frame and the blend holding 0.7 of its history, in the same frame. The field is now declared as a fraction
 * of the frame width and converted once, by motion_magnitude_px(), into the pixels both thresholds are in.
 *
 * This pins that agreement at a known grid: one number below both gates makes both consumers accept, one
 * number above both makes both back off, and the ABI echo stays the fraction the caller declared.
 */
NRR_TEST(test_motion_magnitude_reaches_both_consumers_in_one_unit) {
    using namespace phase_fixture;
    TemporalAccumulator accumulator;
    accumulator.initialize();
    accumulator.set_phase_aligned_enabled(true);
    NRR_ASSERT(PHASE_ALIGNED_MOTION_GATE_PX < TEMPORAL_ALPHA_MOTION_GATE_PX,
               "the integration's gate has to be the stricter one, or the two cases below are not distinct");

    std::vector<uint8_t> frame = pf_ramp();
    const NRRFrameInput first = pf_input(1, 0.25f, 0.0f, true, 0.0f);
    accumulator.apply(first, frame, pf_w, pf_h, pf_no_field,
                      phase_aligned_frame_for(first, false, pf_w, pf_h, pf_w, pf_h));

    /* Below both gates: the integration accepts and the blend keeps its full history weight. */
    const float under_px = 0.5f * PHASE_ALIGNED_MOTION_GATE_PX;
    const float under_declared = under_px / static_cast<float>(pf_w);
    std::vector<uint8_t> still = pf_ramp();
    const NRRFrameInput still_input = pf_input(2, -0.25f, 0.0f, true, under_declared);
    const TemporalAccumulator::Result still_result =
        accumulator.apply(still_input, still, pf_w, pf_h, pf_no_field,
                          phase_aligned_frame_for(still_input, false, pf_w, pf_h, pf_w, pf_h));
    NRR_EXPECT_NEAR(still_result.motion_px, under_px, 1e-6,
                    "the declared fraction is converted with the frame's own grid");
    NRR_EXPECT_NEAR(still_result.state.temporal_alpha, TEMPORAL_BASE_ALPHA, 1e-6,
                    "the blend keeps its history below its own gate");
    NRR_EXPECT_EQ(still_result.phase_aligned_frames, 2u,
                  "and the stricter gate lets the same frame integrate");
    NRR_EXPECT_NEAR(still_result.state.motion_magnitude, under_declared, 1e-6,
                    "the ABI echo stays the fraction the caller declared");

    /* Above both: the integration resets and the blend's weight decays. One number, one direction. */
    const float over_px = 3.0f;
    const float expected_alpha =
        TEMPORAL_BASE_ALPHA *
        (1.0f - (over_px - TEMPORAL_ALPHA_MOTION_GATE_PX) /
                    (TEMPORAL_ALPHA_MOTION_FULL_PX - TEMPORAL_ALPHA_MOTION_GATE_PX));
    NRR_ASSERT(over_px > TEMPORAL_ALPHA_MOTION_GATE_PX &&
               over_px < TEMPORAL_ALPHA_MOTION_FULL_PX,
               "the moving value has to land inside the decay band, or the assertions below are about clamps");
    std::vector<uint8_t> moved = pf_ramp();
    const NRRFrameInput moved_input = pf_input(3, 0.25f, 0.0f, true,
                                               over_px / static_cast<float>(pf_w));
    const TemporalAccumulator::Result moved_result =
        accumulator.apply(moved_input, moved, pf_w, pf_h, pf_no_field,
                          phase_aligned_frame_for(moved_input, false, pf_w, pf_h, pf_w, pf_h));
    NRR_EXPECT_NEAR(moved_result.motion_px, over_px, 1e-6, "the same conversion, a larger value");
    NRR_EXPECT_EQ(moved_result.phase_aligned_frames, 0u,
                  "past its gate the integration empties the accumulation");
    NRR_EXPECT_NEAR(moved_result.state.temporal_alpha, expected_alpha, 1e-6,
                    "and the blend's weight decays, from the same converted number");

    /* The grid the conversion uses: with no frame width from the pass, the caller's declared render
     * resolution is what remains, so a 2x pipeline cannot silently halve the motion. */
    NRRFrameInput wide = pf_input(4, 0.25f, 0.0f, true, 0.5f);
    wide.temporal.resolution_x = 2 * pf_w;
    NRR_EXPECT_NEAR(motion_magnitude_px(wide, 0, pf_w), 0.5f * static_cast<float>(2 * pf_w), 1e-6,
                    "the declared resolution is the fallback grid");
}


/* The composition of the two accumulators, in the order apply() runs them.
 *
 * Nothing tested this before: every phase-aligned test above passes an empty motion provider, so the
 * reprojection blend never fired and the pass was only ever exercised on its own. But the runtime's
 * arrangement is not "integrate the model's output" - the blend writes the displayed frame first, the
 * integration accumulates *that*, and the resolve is what is recorded as the next frame's history, so the
 * two accumulators feed each other. (What the composition is worth is measured in tools/aa_resolve_probe.py's
 * composition_check: the blend in front of the integration costs 4% of the integration's gain for the placed
 * arrangement and 11% for the unplaced one, so it does not throw the gain away.)
 *
 * Three things are pinned here:
 *   - both passes run in one frame, which the empty-field tests could not show;
 *   - a still, unchanged scene is undisturbed: with identical frames the blend of the resolve with itself is
 *     the identity, so the displayed frame is the same whether the pass is on or off;
 *   - the history the blend mixes is the *resolve*, not the raw frame. A frame whose content changed without
 *     moving makes the two runs differ by an amount fixed by the placement bias the pass introduced - and
 *     that difference vanishes if the blend is fed the raw frame, which is what a reordered pipeline would
 *     do. The expectation is derived here (weight x bias), not hard-coded, so it tracks the policy.
 */
NRR_TEST(test_phase_aligned_pass_and_blend_compose_in_one_frame) {
    using namespace phase_fixture;

    const float kOffset = 0.5f;      /* constant per frame, so every placement bias is the same */
    const int kContentChange = 8;    /* levels: the scene changes between frames without moving */

    struct Run {
        TemporalAccumulator::Result second;
        std::vector<uint8_t> displayed_first;
        std::vector<uint8_t> displayed_second;
    };
    auto run_sequence = [&](bool phase_aligned, int levels) {
        TemporalAccumulator accumulator;
        accumulator.initialize();
        accumulator.set_phase_aligned_enabled(phase_aligned);

        Run run;
        std::vector<uint8_t> first = pf_ramp();
        const NRRFrameInput first_input = pf_input(1, kOffset, 0.0f, true, 0.0f);
        accumulator.apply(first_input, first, pf_w, pf_h, [] { return pf_field(0.0f, 0.0f); },
                          phase_aligned_frame_for(first_input, false, pf_w, pf_h, pf_w, pf_h));
        run.displayed_first = first;

        std::vector<uint8_t> second = pf_ramp_offset(levels);
        const NRRFrameInput second_input = pf_input(2, kOffset, 0.0f, true, 0.0f);
        run.second = accumulator.apply(second_input, second, pf_w, pf_h,
                                       [] { return pf_field(0.0f, 0.0f); },
                                       phase_aligned_frame_for(second_input, false, pf_w,
                                                               pf_h, pf_w, pf_h));
        run.displayed_second = second;
        return run;
    };

    const Run composed = run_sequence(true, 0);
    NRR_ASSERT(composed.second.blended,
               "with a valid field and a previous frame the blend must run - without it this proves nothing");
    NRR_EXPECT_EQ(composed.second.phase_aligned_frames, 2u,
                  "and the integration must be accumulating in the same frame");
    NRR_ASSERT(composed.second.blend_stats.blended_pixels > 0u,
               "a blend that ran must report the pixels it touched");

    /* The bias and the differences are measured as means over the interior pixels, not at one pixel: a single
     * uint8 sample of a ramp carries +/-1 level of quantisation, and the identities below multiply it by
     * (1 + alpha)/2. Interior only, because the placement clamps at the frame's edge where a ramp is not
     * linear across the clamp, and the mean of ~400 pixels averages the rest of the rounding out. */
    auto mean_interior_delta = [&](const std::vector<uint8_t>& a, const std::vector<uint8_t>& b) {
        double sum = 0.0;
        size_t count = 0;
        for (uint32_t y = 1; y + 1 < pf_h; ++y) {
            for (uint32_t x = 1; x + 1 < pf_w; ++x) {
                const size_t p = (static_cast<size_t>(y) * pf_w + x) * 3;
                sum += static_cast<double>(a[p]) - static_cast<double>(b[p]);
                ++count;
            }
        }
        return count > 0 ? static_cast<float>(sum / static_cast<double>(count)) : 0.0f;
    };

    /* The control: unchanged content. This is *not* the identity, and the reason is the composition's one real
     * subtlety - it is pinned here rather than glossed over. The history the blend mixes is the frame that was
     * *displayed*, i.e. the resolve, whose content the pass has already placed; placing the mixture again by
     * the current frame's offset therefore over-corrects the history's share of it. On this ramp that is
     * visible as a bias that grows from `bias` on the first frame to (1 + alpha)/2 * bias on the second: a
     * frame that arrived unplaced is placed once, while the resolve inside the blend is placed a second time
     * and then averaged in. (The history has to be the displayed frame - that is what reprojection reprojects -
     * so the two accumulators genuinely want different things from it. What that costs on real content, and
     * whether the pass should instead integrate the pre-blend frame, is the open question; see
     * composition_check in tools/aa_resolve_probe.py, which measures both orders.) */
    const Run plain = run_sequence(false, 0);
    NRR_EXPECT_NEAR(composed.second.state.temporal_alpha, TEMPORAL_BASE_ALPHA, 1e-6,
                    "a still scene keeps the base history weight while the pass is on");
    const float first_bias = mean_interior_delta(composed.displayed_first, plain.displayed_first);
    NRR_ASSERT(first_bias > 1.5f,
               "the pass must place the first frame by a measurable bias on this ramp; got "
               + std::to_string(first_bias));
    const float second_bias = mean_interior_delta(composed.displayed_second, plain.displayed_second);
    const float expected_second_bias =
        (1.0f + composed.second.state.temporal_alpha / 2.0f) * first_bias;
    /* The tolerance is the fixture's own rounding rather than a fudge: each displayed frame is quantised to
     * uint8 once (+/-0.5), and the two runs here round in opposite directions, so a difference of means can be
     * off by up to ~1 level while the identity itself is exact. The mean over the interior averages the ramp's
     * per-pixel rounding out; the bound is what is left. */
    NRR_ASSERT(std::fabs(second_bias - expected_second_bias) <= 1.0f,
               "the blend must mix the resolve - already placed - and the pass must place it again: expected a "
               "second-frame bias of " + std::to_string(expected_second_bias) + " levels, measured "
               + std::to_string(second_bias));

    /* The ordering, measured: the content changes without moving, so the only difference between the two runs
     * is what the blend mixed in for the second frame - the resolve of the first (placed, hence biased)
     * against the raw first frame. Both are affine in the ramp, so the difference is
     * (1 + alpha/2) * bias - (1 - alpha) * change / 2, with the bias and the weight measured from this same
     * fixture rather than assumed. It is the same identity as above with a second term, and it fails if the
     * blend is fed the raw frame instead of the resolve. */
    const Run changed_on = run_sequence(true, kContentChange);
    const Run changed_off = run_sequence(false, kContentChange);

    const float alpha = composed.second.state.temporal_alpha;
    const float expected =
        (1.0f + alpha / 2.0f) * first_bias
        - (1.0f - alpha) * static_cast<float>(kContentChange) / 2.0f;
    const float measured = mean_interior_delta(changed_on.displayed_second, changed_off.displayed_second);
    NRR_ASSERT(std::fabs(measured - expected) <= 1.0f,
               "the blend must see the integration's resolve, not the raw frame: expected "
               + std::to_string(expected) + " levels, measured " + std::to_string(measured));
}


} // namespace test
} // namespace nrr