// ---------------------------------------------------------------------------
// test_jitter.cpp
//
// The runtime now has a notion of the sub-pixel offset a frame was sampled at,
// because without one the engine cannot feed a jitter-aware model the information
// it was trained on. That makes runtime/nrr_jitter.cpp a second implementation of
// something that already exists in Python (tools/train_nrr.py::dejitter), and two
// implementations that disagree are worse than one: a model measured in Python
// would behave differently in the engine while every harness number stayed green.
//
// So this pins the C++ to exact values produced by the Python side on a
// deterministic fixture, the same way test_quality_parity.cpp pins PSNR/SSIM.
//
// The fixture is a linear ramp in x with a quarter-weight ramp in y - chosen
// because interpolation blur cannot hide a sign error on a ramp. A sinusoidal or
// textured fixture would soften under a second bilinear pass and could let a
// backwards sign pass as merely "slightly worse", which is the specific bug these
// values were chosen to catch. Interior samples land on exact binary fractions, so
// the comparison is tight rather than tolerant.
//
// The expected constants were generated by running the Python mirror on this same
// fixture and are reproduced verbatim rather than recomputed: a test that derives
// its own expectation with the code under test proves nothing.
// ---------------------------------------------------------------------------
#include "test_framework.h"
#include "nrr_jitter.h"
#include "nrr_inference.h"
#include "nrr_temporal.h"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <vector>

namespace nrr {
namespace test {

namespace jitter_fixture {

/* Uniquely prefixed: main.cpp compiles every test file into one translation unit,
 * so bare names collide with the anonymous-namespace fixtures in the other files. */
const uint32_t jf_w = 64;
const uint32_t jf_h = 64;
const float jf_offset_x = 0.3f;
const float jf_offset_y = 0.2f;

/* The un-jittered signal the fixture represents. Single channel: the correction is
 * per-pixel geometry and does not care how many channels ride along, which
 * dejitter_nchw's channel loop is covered for separately. */
std::vector<float> jf_scene() {
    std::vector<float> scene(static_cast<size_t>(jf_w) * jf_h, 0.0f);
    for (uint32_t y = 0; y < jf_h; ++y) {
        for (uint32_t x = 0; x < jf_w; ++x) {
            scene[static_cast<size_t>(y) * jf_w + x] =
                (static_cast<float>(x) + 0.25f * static_cast<float>(y)) / 64.0f;
        }
    }
    return scene;
}

/* A frame captured with its content displaced by +offset, i.e. input(x) = scene(x - offset).
 * Built by sampling the scene backward, which is what the capture does - verified against the
 * captured pixels (tools/aa_samples_probe.py) after the opposite direction was found to double the
 * misalignment instead of removing it. */
std::vector<float> jf_capture(const std::vector<float>& scene, float ox, float oy) {
    std::vector<float> out(scene.size(), 0.0f);
    for (uint32_t y = 0; y < jf_h; ++y) {
        for (uint32_t x = 0; x < jf_w; ++x) {
            const float u = std::min(std::max(static_cast<float>(x) - ox, 0.0f),
                                     static_cast<float>(jf_w) - 1.0f);
            const float v = std::min(std::max(static_cast<float>(y) - oy, 0.0f),
                                     static_cast<float>(jf_h) - 1.0f);
            const int x0 = static_cast<int>(std::floor(u));
            const int y0 = static_cast<int>(std::floor(v));
            const int x1 = std::min(x0 + 1, static_cast<int>(jf_w) - 1);
            const int y1 = std::min(y0 + 1, static_cast<int>(jf_h) - 1);
            const float lx = u - static_cast<float>(x0);
            const float ly = v - static_cast<float>(y0);
            const float top = scene[static_cast<size_t>(y0) * jf_w + x0] * (1.0f - lx)
                            + scene[static_cast<size_t>(y0) * jf_w + x1] * lx;
            const float bottom = scene[static_cast<size_t>(y1) * jf_w + x0] * (1.0f - lx)
                               + scene[static_cast<size_t>(y1) * jf_w + x1] * lx;
            out[static_cast<size_t>(y) * jf_w + x] = top * (1.0f - ly) + bottom * ly;
        }
    }
    return out;
}

double jf_mean_abs_error(const std::vector<float>& a, const std::vector<float>& b) {
    double total = 0.0;
    for (size_t i = 0; i < a.size(); ++i) total += std::fabs(static_cast<double>(a[i] - b[i]));
    return total / static_cast<double>(a.size());
}

} // namespace jitter_fixture
/* Zero offset must be the identity, not merely "close". An un-jittered renderer
 * takes this path on every frame, and a small bias here would silently tax every
 * non-jittered user. */
NRR_TEST(test_jitter_zero_offset_is_identity) {
    const std::vector<float> scene = jitter_fixture::jf_scene();
    std::vector<float> out;
    NRR_ASSERT(dejitter_nchw(scene, 1, jitter_fixture::jf_w, jitter_fixture::jf_h,
                             JitterOffset(0.0f, 0.0f), out),
               "a zero offset must still produce a valid frame");
    NRR_EXPECT_EQ(out.size(), scene.size(), "identity must not change the size");
    for (size_t i = 0; i < scene.size(); ++i) {
        if (out[i] != scene[i]) {
            NRR_ASSERT(false, "a zero offset must be exactly the identity");
        }
    }
}

/* The offset plane is two numbers per frame broadcast over the frame, in x-then-y
 * channel order. If this layout drifts from the trainer's, every jitter-aware model
 * quietly degrades to the control it was trained to beat, with no error anywhere. */
NRR_TEST(test_jitter_plane_layout_matches_the_trainer) {
    std::vector<float> plane;
    NRR_ASSERT(build_jitter_plane(JitterOffset(0.3f, -0.2f), 8, 4, plane),
               "a valid size must produce a plane");
    NRR_EXPECT_EQ(plane.size(), static_cast<size_t>(2) * 8 * 4, "plane must be 2 x H x W");
    for (size_t i = 0; i < 32; ++i) {
        NRR_EXPECT_EQ(plane[i], 0.3f, "channel 0 must carry x on every pixel");
        NRR_EXPECT_EQ(plane[32 + i], -0.2f, "channel 1 must carry y on every pixel");
    }
    std::vector<float> untouched(3, 7.0f);
    NRR_ASSERT(!build_jitter_plane(JitterOffset(0.0f, 0.0f), 0, 4, untouched),
               "a zero-width plane must be refused");
    NRR_EXPECT_EQ(untouched[0], 7.0f, "a refused build must not touch the output");
}

/* The property the whole feature rests on: correcting by the offset the frame was
 * captured at must recover the scene far better than ignoring it. */
NRR_TEST(test_jitter_correcting_the_offset_recovers_the_scene) {
    using namespace jitter_fixture;
    const std::vector<float> scene = jf_scene();
    const std::vector<float> captured = jf_capture(scene, jf_offset_x, jf_offset_y);

    std::vector<float> corrected, ignored;
    NRR_ASSERT(dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(jf_offset_x, jf_offset_y), corrected),
               "correcting by the capture offset must succeed");
    NRR_ASSERT(dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(0.0f, 0.0f), ignored),
               "ignoring the offset must succeed");

    const double corrected_error = jf_mean_abs_error(corrected, scene);
    const double ignored_error = jf_mean_abs_error(ignored, scene);
    NRR_ASSERT(corrected_error < ignored_error * 0.1,
               "correcting the offset must beat ignoring it by a wide margin; got "
               + std::to_string(corrected_error) + " against " + std::to_string(ignored_error));
}

/* A backwards sign must be visibly worse than being told nothing at all. This is
 * the check that separates "uses the offset" from "uses the offset correctly", and
 * it is the one the training ablation structurally cannot make: a graph that ignored
 * the input entirely would pass an ablation test while being useless. */
NRR_TEST(test_jitter_wrong_sign_is_worse_than_no_offset) {
    using namespace jitter_fixture;
    const std::vector<float> scene = jf_scene();
    const std::vector<float> captured = jf_capture(scene, jf_offset_x, jf_offset_y);

    std::vector<float> ignored, backwards;
    dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(0.0f, 0.0f), ignored);
    dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(-jf_offset_x, -jf_offset_y), backwards);

    NRR_ASSERT(jf_mean_abs_error(backwards, scene) > jf_mean_abs_error(ignored, scene),
               "a backwards offset must be worse than no offset; a sign error would pass this wrongly");
}
/* Parity with the Python implementation this mirrors. Constants generated by
 * tools/train_nrr.py::dejitter on this same fixture; if either side drifts, one of
 * the two fails. The tolerance is float32 accumulation over a 64x64 ramp, not a
 * modelling allowance. */
NRR_TEST(test_jitter_matches_the_python_reference) {
    using namespace jitter_fixture;
    const double kTolerance = 1e-6;
    const std::vector<float> scene = jf_scene();
    const std::vector<float> captured = jf_capture(scene, jf_offset_x, jf_offset_y);

    std::vector<float> corrected, ignored, backwards;
    dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(jf_offset_x, jf_offset_y), corrected);
    dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(0.0f, 0.0f), ignored);
    dejitter_nchw(captured, 1, jf_w, jf_h, JitterOffset(-jf_offset_x, -jf_offset_y), backwards);

    NRR_ASSERT(std::fabs(jf_mean_abs_error(corrected, scene) - 0.000145808) < kTolerance,
               "mean error after correcting must match the Python reference");
    NRR_ASSERT(std::fabs(jf_mean_abs_error(ignored, scene) - 0.005383285) < kTolerance,
               "mean error with the offset withheld must match the Python reference");
    NRR_ASSERT(std::fabs(jf_mean_abs_error(backwards, scene) - 0.010742160) < kTolerance,
               "mean error with a backwards offset must match the Python reference");

    /* Regenerated by tools/regen_jitter_fixture.py after the convention was flipped to the capture's.
     * The samples are what catch a flip: on a linear ramp the two conventions are mirror images, so the
     * mean errors barely move (0.000145808 against 0.000145804 before), while these differ at the fifth
     * decimal - the first sample by 1.6e-3, far outside the 1e-6 tolerance. */
    const int samples[5][3] = {{0, 0, 0}, {10, 20, 1}, {32, 32, 2}, {63, 63, 3}, {5, 50, 4}};
    const double expected[5] = {0.003906244, 0.351562500, 0.625000000, 1.225000024, 0.800781250};
    for (const auto& sample : samples) {
        const size_t index = static_cast<size_t>(sample[0]) * jf_w + static_cast<size_t>(sample[1]);
        NRR_ASSERT(std::fabs(static_cast<double>(corrected[index]) - expected[sample[2]]) < kTolerance,
                   "de-jittered sample " + std::to_string(sample[1]) + "," + std::to_string(sample[0])
                   + " must match the Python reference");
    }
}

/* The correction is geometry, not an upscale: shape in, same shape out. A caller
 * feeding a frame it did not size correctly is refused rather than having a short
 * buffer read as if it were pixels. */
NRR_TEST(test_jitter_rejects_malformed_input) {
    std::vector<float> out;
    NRR_ASSERT(!dejitter_nchw(std::vector<float>(16, 0.0f), 0, 4, 4, JitterOffset(0.3f, 0.2f), out),
               "zero channels must be refused");
    NRR_ASSERT(!dejitter_nchw(std::vector<float>(16, 0.0f), 1, 0, 4, JitterOffset(0.3f, 0.2f), out),
               "zero width must be refused");
    NRR_ASSERT(!dejitter_nchw(std::vector<float>(16, 0.0f), 1, 8, 8, JitterOffset(0.3f, 0.2f), out),
               "a buffer smaller than the declared frame must be refused");
    NRR_ASSERT(dejitter_nchw(std::vector<float>(16, 0.0f), 1, 4, 4, JitterOffset(0.3f, 0.2f), out),
               "an exactly-sized buffer must be accepted, so the check above failed on size");
    NRR_EXPECT_EQ(out.size(), static_cast<size_t>(16), "an accepted call must fill the buffer");
}

/* Multi-channel frames must have every channel corrected, independently. A loop that
 * only touched channel 0 would still pass every single-channel test above. */
NRR_TEST(test_jitter_corrects_every_channel) {
    const uint32_t w = 16, h = 8;
    const int channels = 3;
    std::vector<float> frame(static_cast<size_t>(w) * h * channels, 0.0f);
    const size_t plane = static_cast<size_t>(w) * h;
    for (size_t i = 0; i < plane; ++i) {
        frame[i] = static_cast<float>(i % w) / static_cast<float>(w);
        frame[plane + i] = 1.0f - static_cast<float>(i % w) / static_cast<float>(w);
        frame[2 * plane + i] = 0.5f;
    }
    std::vector<float> out;
    NRR_ASSERT(dejitter_nchw(frame, channels, w, h, JitterOffset(0.4f, 0.3f), out),
               "a multi-channel frame must be accepted");
    NRR_EXPECT_EQ(out.size(), frame.size(), "multi-channel correction must preserve the size");
    /* The flat channel must come back exactly flat: a constant is invariant under any
     * resampling, so this detects cross-channel bleed with no tolerance games. */
    for (size_t i = 0; i < plane; ++i) {
        NRR_ASSERT(std::fabs(out[2 * plane + i] - 0.5f) < 1e-6,
                   "a constant channel must survive resampling unchanged, which catches channel bleed");
    }
}

/* History must carry each frame's own offset, and hand it back with the frame it
 * belongs to. Reporting the *present* frame's offset instead would be wrong in a way
 * that is invisible at runtime: both offsets are small, both are plausible, and the
 * history would be warped by the difference without any error being raised. */
NRR_TEST(test_jitter_history_records_each_frames_own_offset) {
    TemporalHistory history;
    history.set_max_frames(4);
    const std::vector<float> color(16 * 16 * 3, 0.0f);
    const std::vector<float> depth(16 * 16, 0.0f);
    const std::vector<float> motion(16 * 16 * 2, 0.0f);

    history.add_frame(0, 0.0f, color, depth, motion, 16, 16,
                      NRR_TEXTURE_FORMAT_RGB8, NRR_TEXTURE_FORMAT_R32F, JitterOffset(0.25f, -0.5f));
    /* A frame recorded without an offset, as an un-jittered renderer would. */
    history.add_frame(1, 0.016f, color, depth, motion, 16, 16,
                      NRR_TEXTURE_FORMAT_RGB8, NRR_TEXTURE_FORMAT_R32F);

    std::vector<float> got_color, got_depth, got_motion;
    uint32_t width = 0, height = 0;
    JitterOffset jitter;

    /* Retrieval returns the newest entry strictly older than the requested index, so
     * asking for 1 yields frame 0 (the jittered one) and asking for 2 yields frame 1
     * (the un-jittered one). */
    NRR_ASSERT(history.get_previous_frame(1, got_color, got_depth, got_motion, width, height, jitter),
               "the jittered frame must be retrievable");
    NRR_ASSERT(std::fabs(jitter.x - 0.25f) < 1e-6 && std::fabs(jitter.y + 0.5f) < 1e-6,
               "the retrieved offset must be the one that frame was recorded with, not the newest entry's");

    NRR_ASSERT(history.get_previous_frame(2, got_color, got_depth, got_motion, width, height, jitter),
               "a frame older than index 2 must still be found");
    NRR_ASSERT(jitter.is_zero(),
               "a frame recorded without an offset must come back as the identity, not uninitialised");

    /* The older overload must keep working and must not be a separate code path. */
    NRR_ASSERT(history.get_previous_frame(2, got_color, got_depth, got_motion, width, height),
               "the original overload must still retrieve the frame");

    /* Not-found means "nothing recorded is older than this index", not "the index is
     * beyond everything". Asking for 99 finds frame 1, because frame 1 *is* older
     * than 99; only asking for 0 leaves nothing older, since frame 0 is the oldest
     * entry. Both directions are asserted because the distinction is the retrieval
     * rule itself, and a caller clearing history on a scene cut depends on it. */
    NRR_ASSERT(history.get_previous_frame(99, got_color, got_depth, got_motion, width, height, jitter),
               "an index past every entry must still find the newest one, since it is older than it");
    JitterOffset untouched(9.0f, 9.0f);
    NRR_ASSERT(!history.get_previous_frame(0, got_color, got_depth, got_motion, width, height, untouched),
               "nothing is older than the oldest recorded frame");
    NRR_ASSERT(untouched.x == 9.0f && untouched.y == 9.0f,
               "a failed retrieval must leave the caller's offset untouched, not silently reset it");
}

/* A jitter-aware model declares a `jitter` input. If the classifier does not
 * recognise it, the tensor is left unfed, which is indistinguishable from feeding a
 * zero offset - so the model silently runs as the control it was trained to beat.
 * Pinned for the names the trainer actually exports and for the ordering hazard. */
NRR_TEST(test_jitter_input_names_classify_as_the_offset) {
    NRR_ASSERT(classify_tensor_role("jitter") == TensorRole::Jitter, "'jitter' must be the offset");
    NRR_ASSERT(classify_tensor_role("Jitter") == TensorRole::Jitter, "matching must be case-insensitive");
    NRR_ASSERT(classify_tensor_role("subpixel_offset") == TensorRole::Jitter, "'subpixel' must be the offset");
    NRR_ASSERT(classify_tensor_role("jittered_input") == TensorRole::Jitter,
               "a colour synonym inside a jitter name must not win - that would feed a 2-channel offset");
    /* The other roles must be unaffected by the new, earlier match. */
    NRR_ASSERT(classify_tensor_role("color") == TensorRole::Color, "colour must still be colour");
    NRR_ASSERT(classify_tensor_role("depth") == TensorRole::Depth, "depth must still be depth");
    NRR_ASSERT(classify_tensor_role("motion") == TensorRole::Motion, "motion must still be motion");
    NRR_ASSERT(classify_tensor_role("unrelated") == TensorRole::Other, "an unknown name must stay Other");
}

/* The history role. `history` matched no keyword at all, so it fell through to Other
 * and every binding site handed the temporal model the *colour image* as its own
 * history - a resolve given the present frame as the past one, which cannot see any
 * motion and cannot accumulate. Pinned for the names in use and for the ordering
 * hazard against colour. */
NRR_TEST(test_temporal_history_names_classify_as_history) {
    NRR_ASSERT(classify_tensor_role("history") == TensorRole::History, "'history' must be history");
    NRR_ASSERT(classify_tensor_role("History") == TensorRole::History, "matching must be case-insensitive");
    NRR_ASSERT(classify_tensor_role("prev_output") == TensorRole::History, "'prev_' must be history");
    NRR_ASSERT(classify_tensor_role("previous_frame") == TensorRole::History, "'previous' must be history");
    NRR_ASSERT(classify_tensor_role("history_color") == TensorRole::History,
               "a colour synonym inside a history name must not win - that would feed the wrong tensor");
    /* A model input merely *described* as temporal stays on the colour path. */
    NRR_ASSERT(classify_tensor_role("temporal_input") == TensorRole::Color,
               "'temporal_input' names the model's kind, not a history tensor");
    NRR_ASSERT(classify_tensor_role("color") == TensorRole::Color, "colour must still be colour");
    NRR_ASSERT(classify_tensor_role("depth") == TensorRole::Depth, "depth must still be depth");
    NRR_ASSERT(classify_tensor_role("jitter") == TensorRole::Jitter, "jitter must still be jitter");
}

/* The model wants the previous frame's *low-resolution* render. The accumulator's
 * blended history is at output resolution and would be a silent 2x mismatch, so the
 * two are stored apart - this pins that separation, including that a reset discards
 * the low-res frame rather than carrying it into the next scene. */
NRR_TEST(test_temporal_previous_input_frame_is_low_resolution_and_reset_clears_it) {
    TemporalAccumulator accumulator;
    accumulator.initialize();

    std::vector<uint8_t> out;
    uint32_t w = 0, h = 0;
    NRRTextureFormat format = NRR_TEXTURE_FORMAT_RGBA8;
    NRR_ASSERT(!accumulator.previous_input_frame(out, w, h, format),
               "a fresh accumulator must report no previous input");

    /* 4x4 RGB8 is 48 bytes; if this ever returns a size derived from the output
     * resolution instead, the separation has been lost. */
    const std::vector<uint8_t> frame(4 * 4 * 3, 0xAB);
    accumulator.record_input_frame(frame.data(), 4, 4, NRR_TEXTURE_FORMAT_RGB8);

    NRR_ASSERT(accumulator.has_previous_input(), "a recorded frame must be available");
    NRR_ASSERT(accumulator.previous_input_frame(out, w, h, format),
               "the recorded frame must be retrievable");
    NRR_EXPECT_EQ(w, 4u, "the stored frame must keep its own resolution");
    NRR_EXPECT_EQ(h, 4u, "the stored frame must keep its own resolution");
    NRR_EXPECT_EQ(out.size(), static_cast<size_t>(4 * 4 * 3), "the stored bytes must be the input's, not the output's");
    NRR_EXPECT_EQ(static_cast<int>(out[0]), 0xAB, "the stored pixels must be the ones recorded");

    accumulator.reset();
    NRR_ASSERT(!accumulator.previous_input_frame(out, w, h, format),
               "a reset must discard the low-resolution frame, or the next scene inherits the last one");

    /* A null record must clear rather than keep a stale frame. */
    accumulator.record_input_frame(frame.data(), 4, 4, NRR_TEXTURE_FORMAT_RGB8);
    accumulator.record_input_frame(nullptr, 0, 0, NRR_TEXTURE_FORMAT_RGB8);
    NRR_ASSERT(!accumulator.has_previous_input(),
               "recording nothing must clear the frame rather than leave the previous one");
}

/* ---------------------------------------------------------------------------
 * The phase-aligned path: the same measured convention, on the operation the
 * de-jitter does not perform.
 *
 * The constants below come from tools/regen_aa_fixture.py, which validates itself
 * before printing them: that the C++-mirrored bilinear taps agree with torch's
 * interpolate + grid_sample to 8e-8, that the capture's sign reconstructs a frame far
 * better than its mirror, and that the ordering asserted below holds in Python. Two
 * fixtures, because they pin different steps:
 *
 *   * a 64x64 bilinear capture of a 128x128 ramp, three frames at the capture's own
 *     Halton offsets, placed and averaged. On a ramp the mean equals a single placed
 *     frame, so this pins the placement - scale and sign included - and cannot see the
 *     accumulate-and-divide step at all.
 *   * a point-sampled zone plate, where the accumulation itself is pinned, plus the
 *     ordering that says the accumulator does something a de-jitter cannot.
 * --------------------------------------------------------------------------- */
namespace aa_fixture {

const uint32_t aa_hi = 128;  /* the output grid the samples are placed into */
const uint32_t aa_lo = 64;   /* the resolution the frames were rendered at */

/* The ordering fixture's plate: 0.040 radians per target pixel squared, which is the probe's
 * own plate strength in these units - about 3.3 cycles per frame pixel at the rim, far past
 * the frame grid's Nyquist limit. That strength is not decoration. In the mildly aliased
 * regime an un-jittered single frame can beat any integration (measured +7% on this same
 * fixture at k = 0.006), so an ordering test needs content that genuinely aliases, which is
 * also the content the feature exists for. */
const float aa_plate_k = 0.040f;

/* Pinned values at these points. The offsets equal aa_halton(1..3), asserted in the first
 * test, so the fixture cannot drift from the tool's frame set unnoticed. */
const int aa_points[6][2] = {{0, 0}, {10, 20}, {32, 33}, {63, 62}, {100, 101}, {127, 127}};
const double aa_resolved[6] = {0.005534859, 0.175781250, 0.320312500,
                               0.607421875, 0.984375000, 1.234085648};
const int aa_wrong_points[2][2] = {{32, 33}, {63, 62}};
const double aa_wrong[2] = {0.319010417, 0.606119792};
const double aa_one_frame[2] = {0.320312500, 0.607421875};
const int aa_plate_points[3][2] = {{20, 30}, {64, 64}, {110, 100}};
const double aa_plate_resolved[3] = {0.367409754, 0.997542337, 0.625756466};
const double aa_plate_single[3] = {0.654102142, 0.998502148, 0.546668620};

/* Halton (2,3) with index = frame + 1: the capture's own sequence, so the fixture is not a set
 * of offsets chosen to make the arithmetic work out. Computed in double and stored as float,
 * exactly as the tool does - a float32 radical inverse would show up in the pinned values,
 * since these are scaled by the resolution ratio before use. */
inline double aa_radical_inverse(int value, int radix) {
    double result = 0.0, fraction = 1.0;
    while (value > 0) {
        fraction /= static_cast<double>(radix);
        result += fraction * static_cast<double>(value % radix);
        value /= radix;
    }
    return result;
}

inline JitterOffset aa_halton(int index) {
    return JitterOffset(static_cast<float>(aa_radical_inverse(index, 2) - 0.5),
                        static_cast<float>(aa_radical_inverse(index, 3) - 0.5));
}

/* Clamped bilinear sample of a planar image at a continuous coordinate. Written out rather than
 * reused from nrr_jitter.cpp, where the tap helper is private to the implementation: a fixture
 * that borrowed it could not catch a change in it. The floor is taken *before* the clamp, which
 * is the part that is easy to get subtly wrong, and the pinned constants catch it - clamping a
 * negative coordinate to 0 and then stepping to pixel 1 is a different interpolation. */
inline float aa_sample(const std::vector<float>& plane, uint32_t width, uint32_t height,
                       float u, float v) {
    const float base_x = std::floor(u);
    const float base_y = std::floor(v);
    const int x0 = std::min(std::max(static_cast<int>(base_x), 0), static_cast<int>(width) - 1);
    const int x1 = std::min(std::max(static_cast<int>(base_x) + 1, 0), static_cast<int>(width) - 1);
    const int y0 = std::min(std::max(static_cast<int>(base_y), 0), static_cast<int>(height) - 1);
    const int y1 = std::min(std::max(static_cast<int>(base_y) + 1, 0), static_cast<int>(height) - 1);
    const float lx = u - base_x;
    const float ly = v - base_y;
    const float top = plane[static_cast<size_t>(y0) * width + x0] * (1.0f - lx)
                    + plane[static_cast<size_t>(y0) * width + x1] * lx;
    const float bottom = plane[static_cast<size_t>(y1) * width + x0] * (1.0f - lx)
                       + plane[static_cast<size_t>(y1) * width + x1] * lx;
    return top * (1.0f - ly) + bottom * ly;
}

/* The un-jittered signal at the output resolution. Same shape of fixture as jf_scene(), and
 * likewise not normalised to [0,1]: the arithmetic under test does not clamp, so a ramp that
 * stays inside the range would only be hiding that. */
std::vector<float> aa_ramp() {
    std::vector<float> out(static_cast<size_t>(aa_hi) * aa_hi, 0.0f);
    for (uint32_t y = 0; y < aa_hi; ++y) {
        for (uint32_t x = 0; x < aa_hi; ++x) {
            out[static_cast<size_t>(y) * aa_hi + x] =
                (static_cast<float>(x) + 0.25f * static_cast<float>(y)) / static_cast<float>(aa_hi);
        }
    }
    return out;
}

/* One frame of `target` on a sampling grid displaced by `offset`: pixel p holds the scene at
 * (p + 0.5 + offset) * 2 - 0.5 in target pixels. Bilinear here - a surrogate that has been
 * pre-filtered, which is fine for pinning placement and useless for showing an integration
 * gain, because a pre-filtered signal has no aliasing left to resolve. */
std::vector<float> aa_capture(const std::vector<float>& target, const JitterOffset& offset) {
    std::vector<float> out(static_cast<size_t>(aa_lo) * aa_lo, 0.0f);
    const float step = static_cast<float>(aa_hi) / static_cast<float>(aa_lo);
    for (uint32_t y = 0; y < aa_lo; ++y) {
        const float v = (static_cast<float>(y) + 0.5f + offset.y) * step - 0.5f;
        for (uint32_t x = 0; x < aa_lo; ++x) {
            const float u = (static_cast<float>(x) + 0.5f + offset.x) * step - 0.5f;
            out[static_cast<size_t>(y) * aa_lo + x] = aa_sample(target, aa_hi, aa_hi, u, v);
        }
    }
    return out;
}

inline float aa_plate_value(float x, float y) {
    const float dx = x - 0.5f * static_cast<float>(aa_hi);
    const float dy = y - 0.5f * static_cast<float>(aa_hi);
    return 0.5f + 0.5f * std::cos(aa_plate_k * (dx * dx + dy * dy));
}

/* The ground truth: the plate averaged over each pixel's footprint, i.e. a supersampled render.
 * A point-evaluated reference is itself aliased at these frequencies, and comparing one aliased
 * image against another measures the phase of two sampling grids rather than the reconstruction. */
std::vector<float> aa_plate_reference() {
    const int oversample = 4;
    std::vector<float> out(static_cast<size_t>(aa_hi) * aa_hi, 0.0f);
    for (uint32_t y = 0; y < aa_hi; ++y) {
        for (uint32_t x = 0; x < aa_hi; ++x) {
            double total = 0.0;
            for (int oy = 0; oy < oversample; ++oy) {
                for (int ox = 0; ox < oversample; ++ox) {
                    const float sx = static_cast<float>(x)
                                   + (static_cast<float>(ox) + 0.5f) / oversample - 0.5f;
                    const float sy = static_cast<float>(y)
                                   + (static_cast<float>(oy) + 0.5f) / oversample - 0.5f;
                    total += static_cast<double>(aa_plate_value(sx, sy));
                }
            }
            out[static_cast<size_t>(y) * aa_hi + x] =
                static_cast<float>(total / static_cast<double>(oversample * oversample));
        }
    }
    return out;
}

/* One frame of the plate: a *point* sample per pixel, no interpolation. That is what a rasteriser
 * writes, and it is the regime in which an integration can recover anything. */
std::vector<float> aa_point_frame(const JitterOffset& offset) {
    std::vector<float> out(static_cast<size_t>(aa_lo) * aa_lo, 0.0f);
    const float step = static_cast<float>(aa_hi) / static_cast<float>(aa_lo);
    for (uint32_t y = 0; y < aa_lo; ++y) {
        const float sy = (static_cast<float>(y) + 0.5f + offset.y) * step - 0.5f;
        for (uint32_t x = 0; x < aa_lo; ++x) {
            const float sx = (static_cast<float>(x) + 0.5f + offset.x) * step - 0.5f;
            out[static_cast<size_t>(y) * aa_lo + x] = aa_plate_value(sx, sy);
        }
    }
    return out;
}

/* Normalised gradient magnitude of the reference, as the probe and the tool use: a plain mean over
 * a mostly flat frame hides an edge effect in the flat fraction. Central differences inside the
 * frame and one-sided at its edges, matching numpy's gradient. */
std::vector<double> aa_edge_weights(const std::vector<float>& image) {
    std::vector<double> weights(static_cast<size_t>(aa_hi) * aa_hi, 0.0);
    double total = 0.0;
    for (uint32_t y = 0; y < aa_hi; ++y) {
        for (uint32_t x = 0; x < aa_hi; ++x) {
            const size_t here = static_cast<size_t>(y) * aa_hi + x;
            const double gx = x == 0 ? image[here + 1] - image[here]
                            : x + 1 == aa_hi ? image[here] - image[here - 1]
                            : 0.5 * (image[here + 1] - image[here - 1]);
            const double gy = y == 0 ? image[here + aa_hi] - image[here]
                            : y + 1 == aa_hi ? image[here] - image[here - aa_hi]
                            : 0.5 * (image[here + aa_hi] - image[here - aa_hi]);
            const double magnitude = std::sqrt(gx * gx + gy * gy);
            weights[here] = magnitude;
            total += magnitude;
        }
    }
    for (size_t i = 0; i < weights.size(); ++i) {
        weights[i] = total > 0.0 ? weights[i] / total : 0.0;
    }
    return weights;
}

double aa_edge_error(const std::vector<float>& candidate, const std::vector<float>& reference,
                     const std::vector<double>& weights) {
    double total = 0.0;
    for (size_t i = 0; i < candidate.size(); ++i) {
        total += std::fabs(static_cast<double>(candidate[i]) - static_cast<double>(reference[i]))
               * weights[i];
    }
    return total;
}

} // namespace aa_fixture

/* The placement parity. The pinned values come from the torch pair (interpolate + grid_sample),
 * mirrored by tools/regen_aa_fixture.py and validated against torch to 8e-8 before it printed them.
 * This is what a half-pixel convention, an offset not scaled into output pixels, or the pre-flip sign
 * cannot survive: each of those produces a plausible picture and a different number here. */
NRR_TEST(test_aa_accumulator_places_each_frame_where_it_was_sampled) {
    using namespace aa_fixture;
    const double kTolerance = 1e-6;

    /* The tool's offsets have to be the capture's own sequence, or fixture and tool have drifted
     * apart without either of them failing. */
    const JitterOffset expected[3] = {aa_halton(1), aa_halton(2), aa_halton(3)};
    NRR_ASSERT(std::fabs(expected[0].x) < 1e-6 && std::fabs(expected[0].y + 0.166666667f) < 1e-6,
               "aa_halton(1) must be Halton(2,3)'s first offset");
    NRR_ASSERT(std::fabs(expected[2].x - 0.25f) < 1e-6 && std::fabs(expected[2].y + 0.388888889f) < 1e-6,
               "aa_halton(3) must be Halton(2,3)'s third offset");

    const std::vector<float> scene = aa_ramp();
    PhaseAlignedAccumulator accumulator;
    std::vector<float> resolved;
    NRR_ASSERT(!accumulator.resolve(resolved), "a resolve with nothing accumulated must fail");
    for (int k = 0; k < 3; ++k) {
        const JitterOffset offset = aa_halton(k + 1);
        NRR_ASSERT(accumulator.add_frame(aa_capture(scene, offset), 1, aa_lo, aa_lo, aa_hi, aa_hi, offset),
                   "a valid frame must be accepted");
    }
    NRR_EXPECT_EQ(accumulator.frame_count(), 3u, "three frames must have been accumulated");

    NRR_ASSERT(accumulator.resolve(resolved), "a resolve after three frames must succeed");
    NRR_EXPECT_EQ(resolved.size(), static_cast<size_t>(aa_hi) * aa_hi,
                  "the resolve must have the output resolution");
    for (int i = 0; i < 6; ++i) {
        const size_t index = static_cast<size_t>(aa_points[i][0]) * aa_hi
                           + static_cast<size_t>(aa_points[i][1]);
        NRR_ASSERT(std::fabs(static_cast<double>(resolved[index]) - aa_resolved[i]) < kTolerance,
                   "resolved sample " + std::to_string(aa_points[i][0]) + "," + std::to_string(aa_points[i][1])
                   + " must match the Python reference; got " + std::to_string(resolved[index])
                   + " against " + std::to_string(aa_resolved[i]));
    }

    /* One frame placed with the capture's sign. On a ramp this equals the three-frame mean above - a
     * linear function is its own average under a shift - so the two pin the placement without pinning
     * the division, which the zone-plate constants in the next test do instead. */
    const JitterOffset first = aa_halton(1);
    PhaseAlignedAccumulator one_frame, flipped;
    NRR_ASSERT(one_frame.add_frame(aa_capture(scene, first), 1, aa_lo, aa_lo, aa_hi, aa_hi, first),
               "a single frame must be accepted");
    std::vector<float> one;
    NRR_ASSERT(one_frame.resolve(one), "a single-frame resolve must succeed");

    /* The same frame with the mirrored sign: the check that the pinned placement is the capture's
     * direction and not its mirror. The values differ in the third decimal - the offset times the ramp
     * slope - which is precisely the size of the misalignment being corrected. */
    NRR_ASSERT(flipped.add_frame(aa_capture(scene, first), 1, aa_lo, aa_lo, aa_hi, aa_hi,
                                 JitterOffset(-first.x, -first.y)),
               "a frame placed with the mirrored sign must still be accepted");
    std::vector<float> wrong;
    NRR_ASSERT(flipped.resolve(wrong), "the mirrored resolve must succeed");

    for (int i = 0; i < 2; ++i) {
        const size_t index = static_cast<size_t>(aa_wrong_points[i][0]) * aa_hi
                           + static_cast<size_t>(aa_wrong_points[i][1]);
        NRR_ASSERT(std::fabs(static_cast<double>(one[index]) - aa_one_frame[i]) < kTolerance,
                   "the capture's sign must place the frame where the Python reference puts it; got "
                   + std::to_string(one[index]) + " against " + std::to_string(aa_one_frame[i]));
        NRR_ASSERT(std::fabs(static_cast<double>(wrong[index]) - aa_wrong[i]) < kTolerance,
                   "the mirrored sign must place the frame where the Python reference puts *it*; got "
                   + std::to_string(wrong[index]) + " against " + std::to_string(aa_wrong[i]));
        NRR_ASSERT(std::fabs(static_cast<double>(wrong[index]) - static_cast<double>(one[index])) > 1e-3,
                   "the two signs must not produce the same frame, or this test proves nothing");
    }
}

/* The claim the accumulator exists for, measured: integrating frames whose samples fell on different
 * sub-pixel positions beats one frame, and beats de-jittering every frame and then averaging - the
 * operation that corrects geometry per frame and, by putting every frame back onto the same grid,
 * removes the diversity an integration is meant to use. Python's numbers on this fixture are 0.199397
 * single, 0.149468 de-jittered, 0.136076 phase-aligned, 0.156270 phase-aligned with the mirrored sign,
 * i.e. 1.000 / 0.750 / 0.682 / 0.784 of the single-sample error. */
NRR_TEST(test_aa_accumulator_integrates_distinct_subpixel_samples) {
    using namespace aa_fixture;
    const int kFrames = 8;
    const std::vector<float> reference = aa_plate_reference();
    const std::vector<double> weights = aa_edge_weights(reference);

    std::vector<float> single;
    NRR_ASSERT(upsample_bilinear_nchw(aa_point_frame(JitterOffset(0.0f, 0.0f)), 1, aa_lo, aa_lo,
                                      aa_hi, aa_hi, single),
               "upsampling an un-jittered frame must succeed");
    for (int i = 0; i < 3; ++i) {
        const size_t index = static_cast<size_t>(aa_plate_points[i][0]) * aa_hi
                           + static_cast<size_t>(aa_plate_points[i][1]);
        NRR_ASSERT(std::fabs(static_cast<double>(single[index]) - aa_plate_single[i]) < 1e-5,
                   "the un-jittered frame's upsample must match the Python reference; got "
                   + std::to_string(single[index]) + " against " + std::to_string(aa_plate_single[i]));
    }

    PhaseAlignedAccumulator accumulator, mirrored;
    std::vector<float> de_jittered(static_cast<size_t>(aa_hi) * aa_hi, 0.0f);
    for (int k = 1; k <= kFrames; ++k) {
        const JitterOffset offset = aa_halton(k);
        const std::vector<float> frame = aa_point_frame(offset);
        NRR_ASSERT(accumulator.add_frame(frame, 1, aa_lo, aa_lo, aa_hi, aa_hi, offset),
                   "every frame of the sequence must be accepted");
        NRR_ASSERT(mirrored.add_frame(frame, 1, aa_lo, aa_lo, aa_hi, aa_hi,
                                      JitterOffset(-offset.x, -offset.y)),
                   "the mirrored accumulator must accept the same frames");

        /* The operation being replaced: correct this frame where it was rendered, then upsample it to
         * the output grid and average. It uses the shipped correction, so this column is the real
         * alternative rather than a straw man. */
        std::vector<float> corrected, upsampled;
        NRR_ASSERT(dejitter_nchw(frame, 1, aa_lo, aa_lo, offset, corrected),
                   "de-jittering a frame must succeed");
        NRR_ASSERT(upsample_bilinear_nchw(corrected, 1, aa_lo, aa_lo, aa_hi, aa_hi, upsampled),
                   "upsampling a de-jittered frame must succeed");
        for (size_t i = 0; i < de_jittered.size(); ++i) {
            de_jittered[i] += upsampled[i];
        }
    }
    for (size_t i = 0; i < de_jittered.size(); ++i) {
        de_jittered[i] /= static_cast<float>(kFrames);
    }

    std::vector<float> aligned, wrong;
    NRR_ASSERT(accumulator.resolve(aligned), "the accumulated resolve must succeed");
    NRR_ASSERT(mirrored.resolve(wrong), "the mirrored resolve must succeed");

    const double single_edge = aa_edge_error(single, reference, weights);
    const double de_jittered_edge = aa_edge_error(de_jittered, reference, weights);
    const double aligned_edge = aa_edge_error(aligned, reference, weights);
    const double wrong_edge = aa_edge_error(wrong, reference, weights);
    const std::string ratios = "single " + std::to_string(single_edge)
                             + ", de-jittered " + std::to_string(de_jittered_edge)
                             + ", aligned " + std::to_string(aligned_edge)
                             + ", mirrored " + std::to_string(wrong_edge);

    NRR_ASSERT(aligned_edge < single_edge * 0.85,
               "integrating distinct sub-pixel samples must beat one frame by a wide margin; got " + ratios);
    NRR_ASSERT(aligned_edge < de_jittered_edge * 0.95,
               "it must also beat de-jittering every frame and averaging them; got " + ratios);
    NRR_ASSERT(aligned_edge < wrong_edge * 0.95,
               "and it must beat the same integration with the mirrored sign; got " + ratios);

    /* The accumulation itself, pinned. This fixture is not linear, so unlike the ramp it can see the
     * mean. Tolerance 1e-5 rather than 1e-6: the frames here are float32 while the mirror is float64,
     * and the plate has steep local gradients - 3.3 cycles per frame pixel at the rim. */
    for (int i = 0; i < 3; ++i) {
        const size_t index = static_cast<size_t>(aa_plate_points[i][0]) * aa_hi
                           + static_cast<size_t>(aa_plate_points[i][1]);
        NRR_ASSERT(std::fabs(static_cast<double>(aligned[index]) - aa_plate_resolved[i]) < 1e-5,
                   "accumulated sample " + std::to_string(aa_plate_points[i][0]) + ","
                   + std::to_string(aa_plate_points[i][1]) + " must match the Python reference; got "
                   + std::to_string(aligned[index]) + " against " + std::to_string(aa_plate_resolved[i]));
    }
}

/* A sequence has one output grid and one channel count, and a frame that was rendered for a different
 * display is refused rather than reinterpreted - silently averaging samples placed for another grid
 * would be a wrong picture with no error anywhere. Refusal also has to leave the accumulator usable,
 * so the failure paths are checked for side effects rather than only for their return value. */
NRR_TEST(test_aa_accumulator_refuses_mixed_grids_and_bad_shapes) {
    using namespace aa_fixture;
    const std::vector<float> frame(static_cast<size_t>(aa_lo) * aa_lo, 0.5f);

    PhaseAlignedAccumulator accumulator;
    std::vector<float> out(4, 7.0f);

    /* Nothing accumulated: a resolve must refuse rather than fabricate a frame. */
    NRR_ASSERT(!accumulator.resolve(out), "a resolve with no frames must fail");
    NRR_EXPECT_EQ(out[0], 7.0f, "a refused resolve must not touch the output");

    NRR_ASSERT(!accumulator.add_frame(frame, 0, aa_lo, aa_lo, aa_hi, aa_hi, JitterOffset()),
               "a zero channel count must be refused");
    NRR_ASSERT(!accumulator.add_frame(frame, 1, 0, aa_lo, aa_hi, aa_hi, JitterOffset()),
               "a zero frame width must be refused");
    NRR_ASSERT(!accumulator.add_frame(frame, 1, aa_lo, aa_lo, 0, aa_hi, JitterOffset()),
               "a zero output width must be refused");
    NRR_ASSERT(!accumulator.add_frame(std::vector<float>(10, 0.0f), 1, aa_lo, aa_lo, aa_hi, aa_hi,
                                      JitterOffset()),
               "a short frame must be refused rather than read past its end");
    NRR_EXPECT_EQ(accumulator.frame_count(), 0u, "a refused frame must not count as accumulated");
    NRR_ASSERT(!accumulator.resolve(out), "and none of them may have left anything to resolve");

    /* One accepted frame, and then attempts to fold a different sequence into it. */
    NRR_ASSERT(accumulator.add_frame(frame, 1, aa_lo, aa_lo, aa_hi, aa_hi, JitterOffset()),
               "the first frame must be accepted");
    std::vector<float> first;
    NRR_ASSERT(accumulator.resolve(first), "one frame must resolve");
    NRR_ASSERT(!accumulator.add_frame(frame, 3, aa_lo, aa_lo, aa_hi, aa_hi, JitterOffset()),
               "a different channel count must be refused, not reinterpreted");
    NRR_ASSERT(!accumulator.add_frame(frame, 1, aa_lo, aa_lo, aa_hi / 2, aa_hi, JitterOffset()),
               "a different output grid must be refused");
    NRR_EXPECT_EQ(accumulator.frame_count(), 1u, "a refused frame must not count as accumulated");

    std::vector<float> unchanged;
    NRR_ASSERT(accumulator.resolve(unchanged), "the accumulator must still resolve");
    for (size_t i = 0; i < first.size(); ++i) {
        NRR_ASSERT(unchanged[i] == first[i],
                   "a refused frame must leave the accumulated sum exactly as it was");
    }
    NRR_EXPECT_EQ(accumulator.out_width(), aa_hi, "the grid must be the one the accepted frame set");
    NRR_EXPECT_EQ(accumulator.channels(), 1, "the channel count must be the accepted frame's");

    /* A reset has to discard, not merely restart the count. */
    accumulator.reset();
    NRR_EXPECT_EQ(accumulator.frame_count(), 0u, "a reset must clear the count");
    NRR_ASSERT(!accumulator.resolve(out), "a reset must leave nothing to resolve");
    NRR_ASSERT(accumulator.add_frame(frame, 1, aa_lo, aa_lo, aa_hi, aa_hi, JitterOffset()),
               "and the accumulator must be usable again, with its grid chosen afresh");
}

/* The resize the accumulator places through, on its own. The same-size case has to be exact rather
 * than merely close - it is the path taken when display and render resolution match, and a half-pixel
 * convention error would appear here as a small uniform blur that nothing else in the suite notices. */
NRR_TEST(test_aa_upsample_is_the_identity_at_native_resolution) {
    using namespace aa_fixture;
    const std::vector<float> source = aa_ramp();
    std::vector<float> out;
    NRR_ASSERT(upsample_bilinear_nchw(source, 1, aa_hi, aa_hi, aa_hi, aa_hi, out),
               "a same-size resize must succeed");
    NRR_EXPECT_EQ(out.size(), source.size(), "a same-size resize must not change the size");
    for (size_t i = 0; i < source.size(); ++i) {
        if (out[i] != source[i]) {
            NRR_ASSERT(false, "a same-size resize must be exactly the identity");
        }
    }

    /* A constant must stay constant at any scale: that is what a normalised filter does, and an
     * off-by-half kernel or double-weighted edge would show up as a ramp towards the border. */
    const std::vector<float> flat(static_cast<size_t>(aa_lo) * aa_lo, 0.25f);
    std::vector<float> doubled;
    NRR_ASSERT(upsample_bilinear_nchw(flat, 1, aa_lo, aa_lo, aa_hi, aa_hi, doubled),
               "an upsample must succeed");
    for (size_t i = 0; i < doubled.size(); ++i) {
        NRR_ASSERT(std::fabs(doubled[i] - 0.25f) < 1e-6f,
                   "a constant frame must upsample to the same constant");
    }

    /* Planar layout: channel 1 must be read from its own plane, not from channel 0's rows. */
    const size_t plane = static_cast<size_t>(aa_lo) * aa_lo;
    std::vector<float> two_channel(plane * 2, 0.0f);
    for (size_t i = 0; i < plane; ++i) {
        two_channel[plane + i] = 0.75f;
    }
    std::vector<float> both;
    NRR_ASSERT(upsample_bilinear_nchw(two_channel, 2, aa_lo, aa_lo, aa_hi, aa_hi, both),
               "a two-channel upsample must succeed");
    const size_t out_plane = static_cast<size_t>(aa_hi) * aa_hi;
    NRR_ASSERT(std::fabs(both[out_plane / 2]) < 1e-6f, "channel 0 must keep its own values");
    NRR_ASSERT(std::fabs(both[out_plane + out_plane / 2] - 0.75f) < 1e-6f,
               "channel 1 must keep its own values");

    NRR_ASSERT(!upsample_bilinear_nchw(flat, 1, aa_lo, aa_lo, 0, aa_hi, out),
               "a zero output width must be refused");
    NRR_ASSERT(!upsample_bilinear_nchw(flat, 1, 0, 0, aa_hi, aa_hi, out),
               "a zero source size must be refused");
    NRR_ASSERT(!upsample_bilinear_nchw(std::vector<float>(10, 0.0f), 1, aa_lo, aa_lo, aa_hi, aa_hi, out),
               "a short source must be refused rather than read past its end");
}

} // namespace test
} // namespace nrr